#!/bin/sh
#BK June 2009

if [ "`which valac`" = "" ];then
 echo "You need the Vala compiler. Please load the 'devx' SFS file first."
 exit
fi

[ -f ./Pictureviewer ] && rm -f ./Pictureviewer

valac -C --pkg=gtk+-2.0 --pkg=poppler-glib --pkg=gdk-pixbuf-2.0 main.gs pictureviewclass.gs

gcc `pkg-config --cflags gtk+-2.0 --libs gtk+-2.0` `pkg-config --cflags poppler-glib --libs poppler-glib` `pkg-config --cflags gdk-pixbuf-2.0 --libs gdk-pixbuf-2.0` main.c pictureviewclass.c -o Pictureviewer

[ -f ./Pictureviewer ] && strip --strip-unneeded Pictureviewer
sync
