#!/bin/sh

####
#
# addShortcut: To be used with the
#  jwmConfigMgr and keyboard scripts
#
# Author: thoughtjourney
# Date: 22/08/2005
#
# Modified by kwiller on 07-May-2006
#  to allow use of multiple mask keys
#
#
####

#----------variables----------->
PRO="addShortcut"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path
. /etc/rc.d/f4puppy5

#-----------add shortcut------->

if [ "$ADDMASK" = "mask (optional)" ] || [ "$ADDMASK" = "" ] ; then
   MASKKEY=
   P=
else
. $SCRIPT_DIR/func -testInput
fi

if [ -z $MASKKEY ]; then
   SED_ADD=\<Key\ key=\"$ADDKEY\"\>exec:$ADDACTION\<\/Key\>
else
   SED_ADD=\<Key\ mask=\"$MASKKEY\"\ key=\"$ADDKEY\"\>exec:$ADDACTION\<\/Key\>
fi

SEDCOMP=$InsSC$SED_ADD
sed "$SEDCOMP" $personalFILE > $personalFILE2
SED_RV=$?
#------------confirm------------>

TEST=`grep -c "$SED_ADD" $personalFILE2`
. $SCRIPT_DIR/func -checkconf

if [ $TEST -eq 1 ] && [ -z "$CHECKCONF" ] ; then
   cp $personalFILE2 $personalFILE
   Xdialog --title "Shortcut_Added" --msgbox "The following shortcut has been added\n\n
$MASKKEY $P $ADDKEY  $ADDACTION\n\n" 0 0
else
   Xdialog --title "Error" --msgbox "There was an error writing your shortcut to file.\n
   Output of \'grep -c\' $SED_ADD $personalFILE2 : \n
$TEST \n\n
Output of \`jwm -p 2>FILE\` :\n
$CHECKCONF \n\n
Please try again" 0 0
fi

exit
