#!/bin/sh


########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:47:33·GMT+1·2011
#
#
#
#
#
########################################################################

####
#
# addShortcut: to be used with the 
# jwmConfigMgr and keyboard scripts
# 
# author: thoughtjourney
# date: 22/08/2005
#
# modified by kwiller on 07-May-2006
# to allow use of multiple mask keys
#
#
####

#----------variables----------->
PRO="/addShortcut"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

#-----------add shortcut------->

if [ "$ADDMASK" = "mask (optional)" ] || [ "$ADDMASK" = "" ] ; then
   MASKKEY=
   P=
else
. $SCRIPT_DIR/func -testInput
fi

if [ -z $MASKKEY ]; then
   SED_ADD=\<Key\ key=\"$ADDKEY\"\>exec:$ADDACTION\<\/Key\>
else
   SED_ADD=\<Key\ mask=\"$MASKKEY\"\ key=\"$ADDKEY\"\>exec:$ADDACTION\<\/Key\>
fi

SEDCOMP=$InsSC$SED_ADD
sed "$SEDCOMP" $PersonalFile > $PersonalFile2

#------------confirm------------>

TEST=`grep -c "$SED_ADD" $PersonalFile2`
. $SCRIPT_DIR/func -checkconf

if [ $TEST -eq 1 ] && [ -z "$CHECKCONF" ] ; then
   cp $PersonalFile2 $PersonalFile
   Xdialog --title "Shortcut_Added" --msgbox "The following shortcut has been added\n\n 
$MASKKEY $P $ADDKEY  $ADDACTION\n\n" 0 0
else
   Xdialog --title "Error" --msgbox "There was an error writing your shortcut to file.\n
   Output of \'grep -c\' $SED_ADD $PersonalFile2 : \n
$TEST \n\n
Output of \`jwm -p 2>FILE\` :\n
$CHECKCONF \n\n
Please try again" 0 0
fi

exit