#!/bin/sh

####
#
# changeKey: To be used with the
#  jwmConfigMgr and keyboard scripts
# Provides gui for changing or deleting
#  a shortcut
#
# Author: thoughtjourney
# Date: 22/08/2005
#
# Modified by kwiller on 07-May-2006
#  to allow use of multiple mask keys
#
#
####

#------------variables--------------->>
PRO="changeKey"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

#-----find key value and mask value--->>

if [ $MASK -eq 1 ]; then
   M=`echo $KEY | awk -F\" '/key/ {print $2}'`
   K=`echo $KEY | awk -F\" '/key/ {print $4}'`
   echo $DBG 30 M: $M
   echo $DBG 31 K: $K
else
   K=`echo $KEY | awk -F\" '/key/ {print $2}'`
   echo $DBG 34 K: $K
fi
echo $DBG 36 key: $KEY

A=`echo $KEY | cut -f 2 -d " " | cut -f 2 -d ":"`
##------------write current key details to a file--------->>

echo "old|$M|$K|$A" > $tmpSCO
sync

#-------find line in config file------>>

if [ $MASK -eq 1 ]; then
   RES=`echo $KEY | awk -F_ '/mask/ {print $1 " " $2}'`
else
   RES=$KEY
fi

echo $DBG 52 res: $RES

KEYLINE=`grep "$RES" /root/.jwm/jwmrc-personal`

#xmessage -name "Current Details" -nearmouse "Current shortcut details:  $KEYLINE" &
   echo $DBG 57$KEYLINE
   # A=`echo $KEYLINE | awk -F\> '/key/ {print $2}' | awk -F\< '/Key/ {print $1}'`


##------write to temp file------------>>

MASKKEY=

if [ -z $M  ]; then
   echo -e "KEY:        $K\nACTION:  $A" > $tmpSC
else
  echo "$M" > $tmpAM
  sed -e "s#A#Alt-#" \
      -e "s#C#Ctrl-#" \
      -e "s#H#Hyper-#" \
      -e "s#M#Meta-#" \
      -e "s#S#Shift-#" \
      -e "s#P#Super-#" $tmpAM > $tmpMK
  SED_RV=$?
  MASKKEY=`cat $tmpMK`
  rm -f $tmpAM
  rm -f $tmpMK

  echo -e "KEY COMBO:  $MASKKEY$K\nACTION:           $A" > $tmpSC
fi
#   echo A: $A >> /tmp/shortcut

##---taskbar config for jwmConfigMgr--->>

export Change_Shortcut="
 <vbox>
  <frame Shortcut Details>
   <hbox>
    <edit><input file>$tmpSC</input><width>300</width><height>45</height></edit>
   </hbox>
  </frame>
  <frame Delete>
   <hbox>
    <pixmap><input file>$MINI_ICONS_DIR/mini-cross.xpm</input></pixmap>
    <checkbox>
      <label>Delete this shortcut?</label>
      <default>no</default>
      <action>if true disable:MSK</action>
      <action>if true disable:KY</action>
      <action>if false enable:MSK</action>
      <action>if false enable:KY</action>
      <variable>CHECK</variable>
    </checkbox>
   </hbox>
  </frame>
  <frame Change Shortcut>
   <hbox>
    <text><label>Enter Mask (optional):</label></text>
    <entry>
     <default>mask</default>
     <visible>enabled</visible>
      <variable>MSK</variable>
    </entry>
    <text><label>Enter Key:</label></text>
    <entry>
     <default>key</default>
     <visible>enabled</visible>
      <variable>KY</variable>
    </entry>
   </hbox>
  </frame>
   <hbox>
   <button ok>
     <action>confirmKey &</action>
     <action>EXIT:ok</action>
   </button>
   <button help>
      <action>defaulthtmlviewer http://www.joewing.net/programs/jwm/config.shtml#keys &</action>
   </button>
   <button cancel></button>
   </hbox>
 </vbox>"

##----------run------------>>
cd $SCRIPT_DIR
export PATH="$PATH:."
gtkdialog3 --program Change_Shortcut

##-------cleanup---------->>
unset Change_Shortcut

export PATH=$PATH1



