#!/bin/sh

#########################
#
# Confirms the keyboard shortcut changes and saves them
#
# For use with the jwmConfigMgr & keyboard scripts
#
# Author: thoughtjourney
# Date: 18/08/2005
#
#########################

##--------variables---------->>
PRO="confirmKey"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

##------preparation---------->>
Mold=`cat $tmpSCO | cut -f 2 -d "|"`
KeyO=`cat $tmpSCO | cut -f 3 -d "|"`
A=`cat $tmpSCO | cut -f 4 -d "|"`
if [ "$MSK" = "mask" ] || [ -z "$MSK" ] && [ "$CHECK" != "true" ] ;then
echo $DBG 'if loop accepted'
   MASKKEY=
   P=
else
ADDMASK=$MSK
. $SCRIPT_DIR/func -testInput
fi

#-------delete??------->
####1
if [ $CHECK = "true" ]; then
echo $DBG 33 $CHECK
   #-----mask and key---->
  #####2
   if [ -z $Mold ];then
Xdialog --title "Delete Shortcut?"\
                  --yesno "KEY   : $KeyO\n\
ACTION: $A\n\n\
Are you sure you wish to delete this shortcut?\n\n" 0 0
YN=$?
     #####3
      if [ $YN = "1" ]; then
         exit 0
      else
         DEL_SED=/y\ key=\"$KeyO\"\>/d
         P=""
      fi
     #####3
   #-------key only----->
   else
Xdialog --title "Delete Shortcut?"\
                  --yesno "MASK  : $Mold\n\
KEY   : $KeyO\n\
ACTION: $A\n\n\
Are you sure you wish to delete this shortcut?\n\n" 0 0
YN1=$?
     #####4
      if [ $YN1 = "1" ]; then
         exit 0
      else
         DEL_SED=/Key\ mask=\"$Mold\"\ key=\"$KeyO\"\>/d
      fi
     #####4
    fi
   #####2
   sed "$DEL_SED" $personalFILE >$personalFILE2
   SED_RV=$?
   mv $personalFILE2 $personalFILE
Xdialog --title "Shortcut_Deleted" --msgbox "The following shortcut has been deleted\n\n
$Mold $P $KeyO $A\n\n" 0 0
sync
echo $DBG 73 what now
unset Change_Shortcut
exit 0

echo $DBG 75 now 'else'
#------change---------->
else
  #---previous shortcut had no mask--->
 #####5
  if [ -z $Mold ]; then

     echo $DBG 72 NEWMASK: $MSK
    #####6
     if [ -z $MASKKEY ];then

        #--new shortcut doesn't have mask-->
        GAP="y key="
        CHANGE_SED=s!y\ key=\"$KeyO\"\>!y\ key=\"$NEWKEY\"\>!g
        sed -e "$CHANGE_SED" $personalFILE > $personalFILE2
        SED_RV=$?
        P=""
     else
        #--new shortcut has mask-->
        CHANGE_SED=s!Key\ key=\"$KeyO\"\>!Key\ mask=\"$MASKKEY\"\ key=\"$NEWKEY\"\>!g
        sed -e "$CHANGE_SED" $personalFILE > $personalFILE2
        SED_RV=$?
     fi
    #####6
   else
   #---previous shortcut had mask--->
    #####7
     if [ -z $MASKKEY ];then

        #--new shortcut doesn't have mask-->
        CHANGE_SED=s!y\ mask=\"$Mold\"\ key=\"$KeyO\"\>!y\ key=\"$NEWKEY\"\>!g
        sed -e "$CHANGE_SED" $personalFILE > $personalFILE2
        SED_RV=$?
        P=""
     else
        #--new shortcut has mask-->
        CHANGE_SED=s!Key\ mask=\"$Mold\"\ key=\"$KeyO\"\>!Key\ mask=\"$MASKKEY\"\ key=\"$NEWKEY\"\>!g
        echo $DBG $CHANGE_SED
        sed -e "$CHANGE_SED" $personalFILE > $personalFILE2
        SED_RV=$?
     fi
    #####7
  fi
 #####5

fi
####1

#---------confirm-------->
cp $personalFILE2 $personalFILE

Xdialog --title "Shortcut_Changed" --msgbox "The shortcut has been changed to\n\n
$MASKKEY $P $NEWKEY  $A\n\n" 0 0

sync
exit 0

