#!/bin/sh

SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

case $1 in

-icon)

FILE=`Xdialog --title "Please select your file" --fselect /usr/local/lib/X11/mini-icons/ 28 48 2>&1`

. $SCRIPT_DIR/func -fileselect

if [ "$FILE" = "" ]; then
exit
fi

echo "$FILE" > $ICO
;;

-xec)

FILE=`Xdialog --title "Please select your file" --fselect /usr/bin 28 48 2>&1`

. $SCRIPT_DIR/func -fileselect

if [ "$FILE" = "" ]; then
exit
fi

echo "$FILE" > $EXC
;;
esac