#!/bin/bash


########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:48:17·GMT+1·2011
#
#
#
#
#
########################################################################

##----focus model configuration for JWM---->>

#--------variables---------->>
PRO="/focusModel"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

PF=1
SET_CLICK=`grep -c "$CLICK" $PersonalFile`

if [ $SET_CLICK -eq 1 ]; then
    CLICK_ON=ON
    SLOPPY_ON=off
else
    CLICK_ON=off
    SLOPPY_ON=ON
    VALUE="sloppy"
fi

#----------dialogue-------->>

#!/bin/sh

Xdialog --title "Focus Model" \
        --radiolist "Choose between the sloppy and click focus models:\n\n\
First, a little note on what these focus models are:\n\n\
SLOPPY FOCUS\n\
The window that is under the mouse pointer is the\n\
window that has the focus. The focus is changed\n\
by pointing at another window, there is no need\n\
to click in it as well.\n\n\
CLICK TO FOCUS\n\
The model used by Microsoft Windows.\n\
The active window is selected by mouse click.\n\n" 0 0 2 \
"click"  "click-to-focus" $CLICK_ON \
"sloppy" "sloppy focus" $SLOPPY_ON 2> $TmpIB

retval=$?

#--------clean exit------->>
. $SCRIPT_DIR/func -simpleexit

#--------preparation------>>

CHOICE=`cat $TmpIB`
rm -f $TmpIB

if [ -z $CHOICE ]; then
   CHOICE="click"
fi
	
SEDFOCUS=s!Model\>${VALUE}!Model\>${CHOICE}!g

#---------save changes----->>
sed -e "$SEDFOCUS" $PersonalFile > $PersonalFileTmp

mv $PersonalFileTmp $PersonalFile

#----notify of result----->>

RES=`grep -c ">$CHOICE" $PersonalFile`
PATTERN=" Focus model"

if [ $RES -eq 1 ]; then
. $SCRIPT_DIR/func -notify
fi

exit 0

