#!/bin/bash
##########################
#
# gtk2jwm
# this script integrates
# the default jwm theme 
# with the current gtk 
# theme.
#
# author: thoughtjourney
# date: 28/08/2005
#
# Hacked BK Feb 2006 for JWM 1.4
# Abused by Dougal, Dec 2006
#########################
## Latest update: July 14th: add gradient support for JWM
# BK jan 2008: integrated into jwmconfig2.

########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:48:32·GMT+1·2011
#
#
#
#
#
########################################################################



##-------------variables---------------->>
PRO="/gtk2jwm"
SCRIPT_DIR="/usr/local/jwmconfig3"		
. $SCRIPT_DIR/path

MENU_BG=
ACTIVE_BG=
FOREGROUND="black"
DEFAULT=
FULL_COLOUR=255

##------get relevant gtk colours-------->>
cd $ThemeFileDir
CURRCOL="`ls -a --time=atime | grep  colors | head -n 1`" # find last modified files
CURRTHE="`ls -a --time=atime | grep  jwmrc | head -n 1`"

cp -f $ColorFile $ColorFileBak
cp -f $ThemeFile $ThemeFileBak
cp -f $CURRCOL $ColorFile
cp -f $CURRTHE $ThemeFile

. $ColorFile # File to get the colorvalues from

if [ -f $TclGtkFile ]; then
rm -f $TclGtkFile ; fi 

if [ -z "$MENU_BG" ]; then
if [ -f $ColorFileBak ]; then
 cp -f $ColorFileBak $ColorFile ; fi
 pidof jwm >/dev/null && jwm -restart
 exit 2

else 
 # set variables for tcl/tk apps:
 ## need to make sure they're not blank
 # if test ! -f $TclGtkFile; then echo > $TclGtkFile; fi
 [ "$MENU_BG" ] && echo  "bg_normal=$MENU_BG" >> $TclGtkFile
 [ "$ACTIVE_BG" ] && echo  "bg_selected=$ACTIVE_BG" >> $TclGtkFile
 [ "$PAGER_BG" ] && echo  "bg_active=$PAGER_BG" >> $TclGtkFile
 [ "$FOREGROUND" ] && echo  "fg_normal=$FOREGROUND" >> $TclGtkFile
 [ "$FG_SELECTED" ] && echo  "fg_selected=$FG_SELECTED" >> $TclGtkFile
 
. $SCRIPT_DIR/func -gradientcolors
  
. $SCRIPT_DIR/func -themedef

fi

echo "$DefTheme" > "$ThemeFile"

#########
#John Doe created code for the applet backgrounds, old jwmconfig, port here...
PATTERN="virtual desktops"

. $SCRIPT_DIR/func -trayapply


#end John Doe's code.
########

sync
pidof jwm >/dev/null && jwm -restart
