#!/bin/bash
##########################
#
# gtk2jwm
# This script integrates
# the default jwm theme
# with the current gtk
# theme.
#
# Author: thoughtjourney
# Date: 28/08/2005
#
# Hacked BK Feb 2006 for JWM 1.4
# Abused by Dougal, Dec 2006
#########################

## Latest update: July 14th: add gradient support for JWM
# BK jan 2008: integrated into jwmconfig2.


##-------------variables---------------->>
PRO="gtk2jwm"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path

MENU_BG=
ACTIVE_BG=
FOREGROUND="black"
DEFAULT=
FULL_COLOUR=255

##------get relevant gtk colours-------->>
cd $themeFILEdir
CURRCOL="`ls -a --time=atime | grep  colors | head -n 1`" # find last modified files
CURRTHE="`ls -a --time=atime | grep  jwmrc | head -n 1`"

cp -f $colorFILE $colorFILEbak
cp -f $themeFILE $themeFILEbak
cp -f $CURRCOL $colorFILE
cp -f $CURRTHE $themeFILE

. $colorFILE # File to get the colorvalues from

if [ -f $TclGTKfile ]; then
rm -f $TclGTKfile ; fi

if [ -z "$MENU_BG" ]; then
if [ -f $colorFILEbak ]; then
 cp -f $colorFILEbak $colorFILE ; fi
 pidof jwm >/dev/null && jwm -restart
 exit 2

else
 # set variables for tcl/tk apps:
 ## need to make sure they're not blank
 # if test ! -f $TclGTKfile; then echo > $TclGTKfile; fi
 [ "$MENU_BG" ] && echo  "bg_normal=$MENU_BG" >> $TclGTKfile
 [ "$ACTIVE_BG" ] && echo  "bg_selected=$ACTIVE_BG" >> $TclGTKfile
 [ "$PAGER_BG" ] && echo  "bg_active=$PAGER_BG" >> $TclGTKfile
 [ "$FOREGROUND" ] && echo  "fg_normal=$FOREGROUND" >> $TclGTKfile
 [ "$FG_SELECTED" ] && echo  "fg_selected=$FG_SELECTED" >> $TclGTKfile

. $SCRIPT_DIR/func -gradientcolors

. $SCRIPT_DIR/func -themedef

fi

echo "$DefTheme" > "$themeFILE"

#########
#John Doe created code for the applet backgrounds, old jwmconfig, port here...
PATTERN="virtual desktops"

. $SCRIPT_DIR/func -trayapply


#end John Doe's code.
########

sync
pidof jwm >/dev/null && jwm -restart
