#!/bin/bash

#############################
#
#  GUI to configure JWM keyboard
#  shortcuts
#
#  For use with the jwmConfigMgr
#
#  Author: thoughtjourney
#  Date: 13/08/2005
#
#
#############################

##-------variables----------->>
PRO="keyboard"
SCRIPT_DIR="/usr/local/jwmconfig3"
. "$SCRIPT_DIR/path"
. /etc/rc.d/f4puppy5


KEY=
PATH1=$PATH


##--------key list----------->>

# awk '/key/ {print $2 "_" $3}' $HOME_DIR/jwmrc-personal | awk -F\> '/key/ {print $1 " " $2}' | awk -F\< '/key/ {print $1}' > $SCRIPT_DIR/cuts
# awk '/key/ {print $2 "_" $3}' $personalFILE | awk -F\> '/key/ {print $1 " " $2}' | awk -F\< '/key/ {print $1}' > $keyL
. "$SCRIPT_DIR/func" -listSC
sl="`echo '1 / 5' | bc -l`"
##---------GUI--------------->>

export Keyboard_Shortcuts="
<window title=\"JWM Configuration Manager\" icon-name=\"gtk-preferences\">
<vbox>
  <frame Description>
    <hbox>
   <pixmap><input file>$MINI_ICONS_DIR/mini-keyboard.xpm</input></pixmap>
      <text>
        <label>You can configure your keyboard shortcuts here.</label>
      </text>
    </hbox>
  </frame>

  <frame Current Shortcuts>
    <hbox>
      <text><label>You can delete or change a shortcut by selecting it below.</label></text>
    </hbox>
    <hbox>
       <text><label>Note that changes will appear next time you hit the refresh button.</label></text>
    </hbox>
    <table>
      <label>KeyCombo</label>
      <variable>KEY</variable>
      <input>more $keyL</input>
      <action>$SCRIPT_DIR/changeKey &</action>
       <action>"$SCRIPT_DIR/'func -listSC'" &</action>
       <action>sleep $sl</action>
       <action type=\"clear\">KEY</action>
       <action>refresh:KEY</action>
      <width>500</width><height>180</height>
    </table>
    <hbox>
     <button><input file stock=\"gtk-refresh\"></input><label>REFRESH</label>
      <action>"$SCRIPT_DIR/'func -listSC'" &</action>
        <action>sleep $sl</action>
        <action type=\"clear\">KEY</action>
       <action>Refresh:KEY</action>
     </button>
    </hbox>
  </frame>
  <frame Add Shortcut>
    <hbox><text><label>Add a new shortcut by filling in the boxes below. Click the button to add your shortcut.</label></text></hbox>
    <hbox>
     <entry>
      <default>mask (optional)</default>
      <visible>enabled</visible>
      <variable>ADDMASK</variable>
     </entry>
     <entry>
      <default>key</default>
      <visible>enabled</visible>
      <variable>ADDKEY</variable>
     </entry>
     <entry>
      <default>action</default>
      <visible>enabled</visible>
      <variable>ADDACTION</variable>
     </entry>
     <button>
      <label>Add</label>
      <input file>$MINI_ICONS_DIR/mini-keyboard.xpm</input>
      <action>$SCRIPT_DIR/addShortcut &</action>
     </button>
    </hbox>
  </frame>
  <frame Quick Info>
    <pixmap><input file>$MINI_ICONS_DIR/info16.xpm</input></pixmap>
    <edit>
      <input file>$SCRIPT_DIR/keyConfigHelp</input>
      <width>600</width><height>140</height>
    </edit>
  </frame>
  <hbox>

    <button>
    <input file>$MINI_ICONS_DIR/geany.xpm</input>
        <label>Edit File</label>
        <action>defaulttexteditor "$personalFILE" &</action>
    </button>
    <button ok>
      <action>rm -f $keyL</action>
      <action type=\"exit\">OK</action>
    </button>
    <button help>
      <action>defaulthtmlviewer http://www.joewing.net/programs/jwm/config.shtml#keys &</action>
    </button>
    <button>
    <label>Exit</label>
    <input file stock=\"gtk-quit\"></input>
    <action>EXIT:ok</action>
    </button>
  </hbox>
</vbox>
</window>
"

#------------run------------>>

export PATH="$PATH:."
gtkdialog3 --program Keyboard_Shortcuts

#----------cleanup--------->>

rm -f "$keyL"
unset Keyboard_Shortcuts
export PATH="$PATH1"

exit 0
