#!/bin/sh

sleep 2

while [ -n "`ps | grep 'file-selector -xec' | grep -v 'grep'`" -o -n "`ps | grep 'file-selector -icon' | grep -v 'grep'`" ] ; do
sleep 1.5
done

killall panel-buttons-refresh

exit


###
#<action>sleep 3 ; while [ -n \"`ps | grep 'file-selector -xec' | grep -v 'grep'`\" -o -n \"`ps | grep 'file-selector -icon' | grep -v 'grep'`\" ] ; do sleep 1.5 ; echo h ; done</action>
