#!/bin/bash
#
# Code adapted for Puppy 1.0.9, JWM 1.7
# by Kwiller on 07-May-2006
#
###################
#v3.99 normal height now 28, changed from 26. changed short 18 -> 20.

##-----taskbarHeight----->>
PRO="/taskbarHeight"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path


#-----Backup current settings----->>
. $SCRIPT_DIR/func -backup2

#----Set defaults---->>
IS_SHRT=off
IS_NORM=ON
IS_TALL=off
IS_XTTL=off
CRHT="NORMAL"

#----Are current settings non-default---->>
SET_TALL=`grep -c "height=\"$TALL\"" $TrayFile`

if [ "$SET_TALL" -eq "1" ]; then
    IS_SHRT=off
    IS_NORM=off
    IS_TALL=ON
    IS_XTTL=off
    CRHT="TALL"
else
    SET_SHRT=`grep -c "height=\"$SHRT\"" $TrayFile`

    if [ "$SET_SHRT" -eq "1" ]; then
        IS_SHRT=ON
        IS_NORM=off
        IS_TALL=off
        IS_XTTL=off
        CRHT="SHORT"
    else
        SET_XTTL=`grep -c "height=\"$XTTL\"" $TrayFile`

        if [ "$SET_XTTL" -eq "1" ]; then
            IS_SHRT=off
            IS_NORM=off
            IS_TALL=off
            IS_XTTL=ON
            CRHT="TALLER"
        fi
    fi
fi
SEDSHRT=s!height=\".*\"!height=\"$SHRT\"!g
SEDNORM=s!height=\".*\"!height=\"$NORM\"!g
SEDTALL=s!height=\".*\"!height=\"$TALL\"!g
SEDXTTL=s!height=\".*\"!height=\"$XTTL\"!g

#-------------gui----------->>

Xdialog --backtitle "JWM Taskbar Configuration" \
	--title "Taskbar" \
        --radiolist "Choose a tray height option" 18 46 4 \
"SHORT"  "About 70% of Normal." $IS_SHRT \
"NORMAL"  "The default height" $IS_NORM \
"TALL"  "About 130% of Normal." $IS_TALL \
"TALLER"  "About 160% of normal" $IS_XTTL 2>$TmpCL

retval=$?

#--------cancel pressed----->>
.$SCRIPT_DIR/func -cancel

#---------save changes----->>

HGHT=`cat $TmpCL`

#-----If there are new settings chosen then make the changes----->>
if [ "$HGHT" != "$CRHT" ]; then
  case $HGHT in
     "SHORT") sed -e "$SEDSHRT" $TrayFile > $TrayFileTmp
              ;;
    "NORMAL") sed -e "$SEDNORM" $TrayFile > $TrayFileTmp
              ;;
      "TALL") sed -e "$SEDTALL" $TrayFile > $TrayFileTmp
              ;;
    "TALLER") sed -e "$SEDXTTL" $TrayFile > $TrayFileTmp
              ;;
  esac
  mv $TrayFileTmp $TrayFile
fi

#------check new configuration----->>
. $SCRIPT_DIR/func -checkconf

#----notify of result----->>
case $HGHT in
     "SHORT") RES=`grep -c "height=\"$SHRT\"" $TrayFile`
              ;;
    "NORMAL") RES=`grep -c "height=\"$NORM\"" $TrayFile`
              ;;
      "TALL") RES=`grep -c "height=\"$TALL\"" $TrayFile`
              ;;
    "TALLER") RES=`grep -c "height=\"$XTTL\"" $TrayFile`
              ;;
esac
CHOICE=$HGHT
PATTERN="Panel"
PF=0
. $SCRIPT_DIR/func -notify
echo 'ICONWIPE' > /tmp/pup_event_icon_change_flag
#--------clean exit------->>
rm -f $TmpCL
exit 0
