#!/bin/bash


########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:49:31·GMT+1·2011
#
#
#
#
#
########################################################################

##---taskbar config for jwmConfigMgr--->>

##-------variables------->>
PRO="/taskbar"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path


##----------gui---------->>
export TASKBAR_CFG="
<window title=\"JWM Configuration Manager\" icon-name=\"gtk-preferences\">
<vbox>
 <frame Tray Configuration Options>
  <hbox>
    <text><label>Virtual Desktops</label></text>
    <button>
     <input file>$MINI_ICONS_DIR/mini-maxwide.xpm</input>
     <action>$SCRIPT_DIR/virtualDesk &</action>
    </button>
  </hbox>
  <hbox>
    <text><label>Taskbar Autohide Option</label></text>
    <button>
     <input file>$MINI_ICONS_DIR/mini-maxwide.xpm</input>
     <action>$SCRIPT_DIR/taskbarHide &</action>
    </button>
  </hbox>
  <hbox>
    <text><label>Taskbar Height Option</label></text>
    <button>
     <input file>$MINI_ICONS_DIR/mini-maxwide.xpm</input>
     <action>$SCRIPT_DIR/taskbarHeight &</action>
    </button>
  </hbox>
  <hbox>
    <text><label>Taskbar Placement Option</label></text>
    <button>
     <input file>$MINI_ICONS_DIR/mini-maxwide.xpm</input>
     <action>$SCRIPT_DIR/taskbarPlace &</action>
    </button>
  </hbox>
  <hbox>
    <text><label>Program Insertion into Tray</label></text>
    <button>
     <input file>$MINI_ICONS_DIR/mini-maxwide.xpm</input>
     <action>$SCRIPT_DIR/trayInsert &</action>
    </button>
  </hbox>
 </frame>
 <frame Important>
  <hbox>
    <pixmap><input file>$MINI_ICONS_DIR/info16.xpm</input></pixmap>
    <text><label>JWM must be restarted for changes to take effect</label></text>
  </hbox>
 </frame>
 <hbox>
   <button ok><action type=\"exit\">OK</action></button>
 </hbox>
</vbox>
</window>
"

##---------run------------>>
gtkdialog3 --program TASKBAR_CFG


##------cleanup----------->>
unset TASKBAR_CFG	
#clear	


