#!/bin/bash
#
# Code adapted for Puppy 1.0.9, JWM 1.7
# by Kwiller on 07-May-2006
#
###################
#v3.99 normal height now 28, changed from 26. changed short 18 -> 20.

########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:49:39·GMT+1·2011
#
#
#
#
#
########################################################################


##-----taskbarHeight----->>
PRO="/taskbarHeight"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path


#-----Backup current settings----->>
. $SCRIPT_DIR/func -backup2

#----Set defaults---->>
IS_SHRT=off
IS_NORM=ON
IS_TALL=off
IS_XTTL=off
CRHT="NORMAL"

#----Are current settings non-default---->>
SET_TALL=`grep -c "height=\"$TALL\"" $TrayFile`

if [ "$SET_TALL" -eq "1" ]; then
    IS_SHRT=off
    IS_NORM=off
    IS_TALL=ON
    IS_XTTL=off
    CRHT="TALL"
else
    SET_SHRT=`grep -c "height=\"$SHRT\"" $TrayFile`

    if [ "$SET_SHRT" -eq "1" ]; then
        IS_SHRT=ON
        IS_NORM=off
        IS_TALL=off
        IS_XTTL=off
        CRHT="SHORT"
    else
        SET_XTTL=`grep -c "height=\"$XTTL\"" $TrayFile`

        if [ "$SET_XTTL" -eq "1" ]; then
            IS_SHRT=off
            IS_NORM=off
            IS_TALL=off
            IS_XTTL=ON
            CRHT="TALLER"
        fi
    fi
fi
SEDSHRT=s!height=\".*\"!height=\"$SHRT\"!g
SEDNORM="s!height=\".*\"!height=\"$NORM\"!g"
SEDTALL=s!height=\".*\"!height=\"$TALL\"!g
SEDXTTL=s!height=\".*\"!height=\"$XTTL\"!g

#-------------gui----------->>

Xdialog --backtitle "JWM Taskbar Configuration" \
	--title "Taskbar" \
        --radiolist "Choose a tray height option" 18 46 4 \
"SHORT"  "About 70% of Normal." $IS_SHRT \
"NORMAL"  "The default height" $IS_NORM \
"TALL"  "About 130% of Normal." $IS_TALL \
"TALLER"  "About 160% of normal" $IS_XTTL 2>$TmpCL

retval=$?

#--------cancel pressed----->>
. $SCRIPT_DIR/func -cancel

#---------save changes----->>

if test "`wc -l $TmpCL | cut -f 1 -d ' '`" -gt 1 ; then
HGHT=`cat $TmpCL | tail -n1`
else
HGHT=`cat $TmpCL`
fi

#-----If there are new settings chosen then make the changes----->>
if [ "$HGHT" != "$CRHT" ]; then

  case "$HGHT" in
     "SHORT") sed -e "$SEDSHRT" <$TrayFile >$TrayFileTmp ;;
    "NORMAL") sed -e "$SEDNORM" <$TrayFile >$TrayFileTmp ;;
      "TALL") sed -e "$SEDTALL" <$TrayFile >$TrayFileTmp ;;
    "TALLER") sed -e "$SEDXTTL" <$TrayFile >$TrayFileTmp ;;
     *) echo "something went wrong"
     CHOICE=$HGHT
	PATTERN="Panel"
	PF=0
	. $SCRIPT_DIR/func -notify 
    ;;
  esac
  
  mv $TrayFileTmp $TrayFile
fi

#------check new configuration----->>
. $SCRIPT_DIR/func -checkconf

#----notify of result----->>
case $HGHT in
     "SHORT") RES=`grep -c "height=\"$SHRT\"" $TrayFile`
              ;;
    "NORMAL") RES=`grep -c "height=\"$NORM\"" $TrayFile`
              ;;
      "TALL") RES=`grep -c "height=\"$TALL\"" $TrayFile`
              ;;
    "TALLER") RES=`grep -c "height=\"$XTTL\"" $TrayFile`
              ;;
esac

CHOICE=$HGHT
PATTERN="Panel"
PF=0
. $SCRIPT_DIR/func -notify

#--------clean exit------->>
rm -f $TmpCL
echo 'ICONWIPE' > /tmp/pup_event_icon_change_flag
exit 0
