#!/bin/bash
#
# Code adapted for Puppy 1.0.9, JWM 1.7
# by Kwiller on 6-May-2006
#
###################

########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:49:46·GMT+1·2011
#
#
#
#
#
########################################################################


##-----taskbarPlace----->>
PRO="/taskbarConfig"
SCRIPT_DIR="/usr/local/jwmconfig3"
. "$SCRIPT_DIR"/path


#-----Backup current settings----->>
. "$SCRIPT_DIR"/func -backup2

#----Set defaults---->>
AUTO_OFF='ON'
AUTO_SET='off'

#----Are current settings non-default---->>
SET_AHD=`grep -c "autohide=\"$ISSET\"" "$TrayFile"`

if [ "$SET_AHD" -eq "1" ]; then
    AUTO_OFF='off'
    AUTO_SET='ON'
fi
SEDSET=s!autohide=\"$ISOFF\"!autohide=\"$ISSET\"!g
SEDOFF=s!autohide=\"$ISSET\"!autohide=\"$ISOFF\"!g
##---end defaults--->

#-------------gui----------->>

Xdialog --backtitle "JWM Taskbar Configuration" \
	--title "Taskbar" \
        --radiolist "Choose a tray autohide option" 13 46 2 \
"OFF"  "Tray Autohide off." $AUTO_OFF \
"ON"    "Tray Autohide on" $AUTO_SET 2>"$TmpCL"

retval=$?

#--------cancel pressed----->>
. "$SCRIPT_DIR"/func -cancel

#---------save changes----->>

OPTN=`cat "$TmpCL" | tail -n1`

#-----If there new settings chosen then make the changes----->>
if [ "$OPTN" = "ON" ]; then
  if [ "$SET_AHD" -eq "0" ]; then
    sed -e "$SEDSET" "$TrayFile" > "$TrayFileTmp"
    mv "$TrayFileTmp" "$TrayFile"
  fi
else
  if [ "$SET_AHD" -eq "1" ]; then
    sed -e "$SEDOFF" "$TrayFile" > "$TrayFileTmp"
    mv "$TrayFileTmp" "$TrayFile"
  fi
fi

#------check new configuration----->>
. "$SCRIPT_DIR"/func -checkconf

#----notify of result----->>
if [ "$OPTN" = "ON" ]; then
  RES=`grep -c "autohide=\"$ISSET\"" "$TrayFile"`
else
  RES=`grep -c "autohide=\"$ISOFF\"" "$TrayFile"`
fi

CHOICE="$OPTN"
PATTERN=" to autohide"
. "$SCRIPT_DIR"/func -notify

#--------clean exit------->>
rm -f "$TmpCL"
exit 0
