#!/bin/sh
#(c) Copyright Jan 2008 Barry Kauler www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
# Written jan 2008 for Puppy Linux.
#v431 improvements by Patriot.

#  <text><label>\"${CHARPAD}\"</label></text>
PRO="theme_switcher"
SCRIPT_DIR="/usr/local/jwmconfig3"
. $SCRIPT_DIR/path
. /etc/rc.d/f4puppy5

ICONSETSGUI=""
for oneTHEME in `find /root/.jwm/themes/ -mindepth 1 -maxdepth 1 -type f | grep 'jwmrc' | sed -e 's/-jwmrc//'`
do
 ONETHEME="`basename $oneTHEME`"
 ICONSETSGUI="$ICONSETSGUI
 <hbox>
  <pixmap><input file>/root/.jwm/themes/${oneTHEME}-tray.png</input></pixmap>
  <pixmap><input file>/root/.jwm/themes/${oneTHEME}-window.png</input></pixmap>
  <vbox>
   <pixmap><input file>/usr/local/lib/X11/pixmaps/invisible96x8.png</input></pixmap>
   <button><label>${oneTHEME}</label></button>
  </vbox>
 </hbox>
"

done

export ICONSWITCHGUI="
<window title=\"Puppy JWM Theme Switcher\" icon-name=\"gtk-convert\">
 <vbox>
  <text><label>JWM is the window manager, handling window borders and tray (taskbar) appearance, whereas the GTK theme is inside each window. Choose a JWM theme that matches or compliments the current GTK theme</label></text>

  ${ICONSETSGUI}

  <hbox>
   <button><input file stock=\"gtk-quit\"></input><label>QUIT</label></button>
  </hbox>
 </vbox>
</window>"

RETSTUFF="`gtkdialog3 --program=ICONSWITCHGUI`"

eval "$RETSTUFF"

NEWTHEME="$EXIT"
[ "$NEWTHEME" = "" ] && exit
[ ! -f $ThemeDir/${NEWTHEME}-jwmrc ] && exit

if [ "$NEWTHEME" != "" ];then
 #select chosen theme...
 echo $DBG$PRO 51
 cp -f $themeFILE $themeFILEbak
 cp -f $ThemeDir/${NEWTHEME}-jwmrc $themeFILE
 #set correct backgrounds for applets...
 echo $DBG/$PRO 55
 echo $colorFILE
 echo $colorFILEbak
 cp -f $colorFILE $colorFILEbak
 echo $DBG/$PRO 57
 cp -f $ThemeDir/${NEWTHEME}-colors $colorFILE
 echo $DBG/$PRO 59
 #...note, /root/.xinitrc reads this file to set background for absvolume.
 #...note, jwm_colors is written to by /usr/local/jwmconfig2/gtk2jwm script

#. /root/.jwm/jwm_colors #gives MENU_BG, PAGER_BG

 #########
 #John Doe created code for the applet backgrounds, old jwmconfig, port here...

 #end John Doe's code.
 ########

  # Patriot Sep 2009
  # Attempting some robustness
  # Update only for known -bg option applets: blinky and xload

. $SCRIPT_DIR/func -trayapply2


fi
  sync
  rm -f $trayFILE.new
  pidof jwm >$OUT && jwm -restart

###END###
