#!/bin/sh
#(c) Copyright Jan 2008 Barry Kauler www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#written jan 2008 for Puppy Linux.
#v431 improvements by Patriot.

########################################################################
#
#
#
#
#
# /dev/hda8:
# LABEL="MacPup431_O2"
# UUID="6d9a8e91-c301-4ff8-9875-97ec708cbee8"
# TYPE="ext3"
# DISTRO_NAME='Puppy'
# DISTRO_VERSION=431
# DISTRO_BINARY_COMPAT='puppy'
# DISTRO_FILE_PREFIX='pup'
# DISTRO_COMPAT_VERSION='4'
# PUPMODE=2
# KERNVER=2.6.37.4-KRG-i486-StagingDrivers-2
# PUP_HOME='/'
# SATADRIVES='·'
# USBDRIVES='·sda·'
# Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686·GNU/Linux
# X·Window·System·Version·1.3.0
# Release·Date:·19·April·2007
# X·Protocol·Version·11,·Revision·0,·Release·1.3
# Build·Operating·System:·UNKNOWN·
# Current·Operating·System:·Linux·puppypc·2.6.37.4-KRG-i486-StagingDrivers-2·#4·SMP·Thu·Mar·17·06:05:58·GMT-8·2011·i686
# Build·Date:·28·November·2007
# $LANG=de_DE@euro
# today=So·30.·Okt·12:50:02·GMT+1·2011
#
#
#
#
#
########################################################################


#  <text><label>\"${CHARPAD}\"</label></text>
PRO="/theme_switcher"
SCRIPT_DIR="/usr/local/jwmconfig3"
. "$SCRIPT_DIR"/path

ICONSETSGUI=""
#for ONETHEME in `find /root/.jwm/themes/ -mindepth 1 -maxdepth 1 -type f | grep 'jwmrc' | sed -e 's/-jwmrc//' | tr '\n' ' '`
THEMES=`find "$hoMe"/.jwm/themes/ -mindepth 1 -maxdepth 1 -type f | grep 'jwmrc' | sed -e 's/-jwmrc//' | tr '\n' ' '`
for ONETHEME in $THEMES 
do
 ONETHEME="`basename $ONETHEME`"
 ICONSETSGUI="$ICONSETSGUI
 <hbox>
  <pixmap><input file>$hoMe/.jwm/themes/${ONETHEME}-tray.png</input></pixmap>
  <pixmap><input file>$hoMe/.jwm/themes/${ONETHEME}-window.png</input></pixmap>
  <vbox>
   <pixmap><input file>/usr/local/lib/X11/pixmaps/invisible96x8.png</input></pixmap>
   <button><label>${ONETHEME}</label></button>
  </vbox>
 </hbox>
"

done

export ICONSWITCHGUI="
<window title=\"Puppy JWM Theme Switcher\" icon-name=\"gtk-convert\">
 <vbox>
  <text><label>JWM is the window manager, handling window borders and tray (taskbar) appearance, whereas the GTK theme is inside each window. Choose a JWM theme that matches or compliments the current GTK theme</label></text>

  ${ICONSETSGUI}
  
  <hbox>
   <button><input file stock=\"gtk-quit\"></input><label>QUIT</label></button>
  </hbox>
 </vbox>
</window>"

RETSTUFF="`gtkdialog3 --program=ICONSWITCHGUI`"

eval "$RETSTUFF"

NEWTHEME="$EXIT"
[ "$NEWTHEME" = "" ] && exit
[ ! -f "$ThemeDir"/"${NEWTHEME}"-jwmrc ] && exit

if [ "$NEWTHEME" != "" ];then
 #select chosen theme...
 echo $DBG$PRO 51 
 cp -f "$ThemeFile" "$ThemeFileBak"
 cp -f "$ThemeDir"/"${NEWTHEME}"-jwmrc "$ThemeFile"
 #set correct backgrounds for applets...
 echo $DBG$PRO 55
 echo $ColorFile
 echo $ColorFileBak
 cp -f "$ColorFile" "$ColorFileBak"
 echo $DBG$PRO 57
 cp -f "$ThemeDir"/"${NEWTHEME}"-colors "$ColorFile"
 echo $DBG$PRO 59
 #...note, /root/.xinitrc reads this file to set background for absvolume.
 #...note, jwm_colors is written to by /usr/local/jwmconfig2/gtk2jwm script

#. /root/.jwm/jwm_colors #gives MENU_BG, PAGER_BG

 #########
 #John Doe created code for the applet backgrounds, old jwmconfig, port here...

 #end John Doe's code.
 ########

  # Patriot Sep 2009
  # Attempting some robustness
  # Update only for known -bg option applets: blinky and xload

. "$SCRIPT_DIR"/func -trayapply2

  
fi
  sync
  rm -f "$TrayFile".trayapply2
  pidof jwm >/dev/null && jwm -restart

###END###
