#!/bin/bash


_usage(){
RV=${1:-0}
shift
EXTRA_MSG=`gettext "$*"`

MSG="
$0 :

# TODO ????
"

MSG=`gettext "$MSG"`
test "$EXTRA_MSG" && echo "$EXTRA_MSG
"
echo "$MSG
"

exit $RV
}

case $* in
-h|*help|*usage) _usage;;
esac


GOAL='/root/GitHub.d/KarlGodt_ForkWoof.Push.D/woof-code/rootfs-skeleton'


rm -f /root/PUPPYscripts.list
for i in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/X11/bin;
do grep -I -H -m1 -i -E 'BK|Kauler|Barry|B\.K\.|T2 |t\-2|rxvt' $i/* | grep '#' >>/root/PUPPYscripts.list;
done

OldIFS="$IFS"
IFS=':'
while read filename rest
do

dn="${filename%/*}"

test -e "${GOAL}/$filename" && continue

echo "$filename" "${GOAL}/${dn}/"

cp -a --remove-destination "$filename" "${GOAL}/${dn}/"

done</root/PUPPYscripts.list

IFS="$OldIFS"


