#!/bin/bash

GOAL='/root/GitHub.d/KarlGodt_ForkWoof.Push.D/woof-code/rootfs-skeleton'


rm -f /root/PUPPYscripts.list
for i in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/X11/bin;
do grep -I -H -m1 -i -E 'BK|Kauler|Barry|B\.K\.|T2 |t\-2|rxvt' $i/* | grep '#' >>/root/PUPPYscripts.list;
done

OldIFS="$IFS"
IFS=':'
while read filename rest
do

dn="${filename%/*}"

test -e "${GOAL}/$filename" && continue

echo "$filename" "${GOAL}/${dn}/"

cp -a --remove-destination "$filename" "${GOAL}/${dn}/"

done</root/PUPPYscripts.list

IFS="$OldIFS"


