#!/bin/sh
#BK called from /root/.xinitrc
#v410 remove icons when drives removed.
#v410 omit icon if optical drive; defer it to pup_event_frontend_d
#w014 bugfix, refresh icons if removable drive swapped when PC turned off.

Version='1.1-getopts luci-218-Puppy_Linux_511 KRG'

usage(){
	echo "
	$0 [ -f|-h|-v]
	-f		force rebuilding of desktop drive icons
	-h		show this message
	-v		be more verbose
	-V		show version
	" >&2
	exit $1
}

while getopts Vvhf option; do
case $option in
V) echo -e "\n$0: Version '$Version'\nTry -h for more info\n";exit 0;;
v) VERBOSE=1;;
h) usage 0;;
f) FORCE=1;;
*) usage 1;;
esac
done
[ "$VERBOSE" ] && set -x

export LANG=C
. /etc/eventmanager #has RAMSAVEINTERVAL, ICONDESK, ICONPARTITIONS, HOTPLUGNOISY, HOTPLUGON, FLOPPYICON.

. /etc/rc.d/functions4puppy5

if [ "`ps --no-headers -C ROX-Filer`" ];then
     #PINBOARD=`ps --no-headers -C ROX-Filer|rev|awk '{print $1}'|rev`
     #PINBOARD=`ps | grep ROX-Filer|grep -v 'grep'|rev|awk '{print $1}'|rev`
     PINBOARD=`ps | grep ROX-Filer|grep -v 'grep'|awk '{print $6}'`
fi
#[ -f "$PINBOARD" ] || { echo "ROX-Filer apparently not running";exit "$?"; }
if [ ! -f "$PINBOARD" ];then
PINBOARD=$HOME/Choices/ROX-Filer/PuppyPin
fi

drvDir="$HOME/Choices/Puppy/.pup_event"

#ePUPPYPIN="`grep -v '$drvDir/drive_' /root/Choices/ROX-Filer/PuppyPin | grep -v '</pinboard>'`"
ePUPPYPIN=`grep -v "$drvDir/drive_" "$PINBOARD" | grep -v '</pinboard>'`

#v403 /usr/sbin/eventmanager creates this file if all icons need to be rebuilt...
if [ ! "$FORCE" ];then
 if [ -f /tmp/pup_event_icon_change_flag ];then
  rm -f /tmp/pup_event_icon_change_flag
  echo "$ePUPPYPIN" >  "$PINBOARD" #/root/Choices/ROX-Filer/PuppyPin
  echo '</pinboard>' >> "$PINBOARD" #/root/Choices/ROX-Filer/PuppyPin
   rm -rf $drvDir/drive_* 2>/dev/null
   #if [ "$DISPLAY" ];then
    #if [ "`ps --no-headers -C ROX-Filer`" ];then
     #PINBOARD=`ps --no-headers -C ROX-Filer|rev|awk '{print $1}'|rev`
     #PINBOARD=`ps | grep ROX-Filer|grep -v 'grep'|rev|awk '{print $1}'|rev`
     #rox -p "$PINBOARD"
    #fi
   #fi
 exit $?
 fi
else
 echo "$ePUPPYPIN" >  /root/Choices/ROX-Filer/PuppyPin
 echo '</pinboard>' >> /root/Choices/ROX-Filer/PuppyPin
  rm -rf $drvDir/drive_* 2>/dev/null
   if [ "$DISPLAY" ];then
    if [ "`ps --no-headers -C ROX-Filer`" ];then
     #PINBOARD=`ps --no-headers -C ROX-Filer|rev|awk '{print $1}'|rev`
     #PINBOARD=`ps | grep ROX-Filer|grep -v 'grep'|rev|awk '{print $1}'|rev`
      PINBOARD=`ps | grep ROX-Filer|grep -v 'grep'|awk '{print $6}' |tail -n1`
     [ -f "$PINBOARD" ] && rox -p "$PINBOARD"
    fi
    if [ "`ps --no-headers -C pup_event_frontend_d`" ];then
     echo 'ICONWIPE' > /tmp/pup_event_icon_change_flag
    fi
   fi
 exit $?
fi

#remove all invalid drive icons off desktop...
echo -n "" > /tmp/pup_event_ok_pin
if [ "$ICONDESK" = "false" ];then
 #leave single 'drives' icon on desktop...
 #grep "$drvDir/drive_drive" /root/Choices/ROX-Filer/PuppyPin >> /tmp/pup_event_ok_pin
 grep "$drvDir/drive_drive" "$PINBOARD" >> /tmp/pup_event_ok_pin
 rm -rf "$drvDir"/drive_[^d]* 2>/dev/null #delete all except drive_drives.
else

 #v410 Delete drive_ directories for removed drives...
 #note, this will not detect removed optical and floppy discs (see /sbin/pup_event_frontend_d).
 #Get the directory names for the drives only, not the partitions, to avoid redundant iterations through the for-loop.
 DIR_DRVS="`ls -1 "$drvDir" | sed 's/drive_//' | grep -E "^hd.$|^sd.$|^sr|^mmcblk.$" | tr '\n' ' '`"
 for ONEDRV in $DIR_DRVS
 do
  [ ! -d "$drvDir/drive_$ONEDRV" ] && continue
  [ ! -e "/sys/block/${ONEDRV}" ] && rm -rf "$drvDir"/drive_"${ONEDRV}"*
 done

 for ONEDRV in `ls -1 /sys/block | grep -vE 'loop|ram' | tr '\n' ' '`
 do
  odPATTERN="$drvDir/drive_${ONEDRV}"
  OKDRV="`grep "$odPATTERN" "$PINBOARD"`" #/root/Choices/ROX-Filer/PuppyPin
  if [ "$OKDRV" = "" ];then
   rm -rf "$drvDir"/drive_"${ONEDRV}"* 2>/dev/null
  else
   [ ! -d "$drvDir/drive_${ONEDRV}" ] && continue #v408
   DRVCUT="`echo -n "$ONEDRV" | cut -c 1,2`" #v410
   [ "$DRVCUT" = "sr" ] && continue #v410 omit icon if optical drive; defer it to pup_event_frontend_d
   [ "$DRVCUT" = "sc" ] && continue #v410 scd, ditto.
   if [ "$DRVCUT" = "hd" ];then
    MEDIACAT="`cat /proc/ide/${ONEDRV}/media`"
    [ "$MEDIACAT" = "cdrom" ] && continue #v410 omit icon if optical drive; defer it to pup_event_frontend_d
   fi
   #w014 user may have swapped removable drives while pc turned off...
   DRVMODEL1="`grep -o '<Summary>.*Size:' "$drvDir/drive_${ONEDRV}/AppInfo.xml" | cut -f 2-20 -d ' ' | rev | cut -f 2-20 -d ' ' | rev`"
   #note, this must be same as done in /sbin/probedisk2...
   DRVMODEL2="`cat /sys/block/$ONEDRV/device/vendor | tr -s ' '``cat /sys/block/${ONEDRV}/device/model | tr -s ' '`"
   if [ "$DRVMODEL1" != "$DRVMODEL2" ];then
    rm -rf "$drvDir"/drive_"${ONEDRV}"* 2>/dev/null
    continue
   fi
   echo "$OKDRV" >> /tmp/pup_event_ok_pin
  fi
 done

fi

#if [ "`cat /tmp/pup_event_ok_pin`" != "" ];then
 echo "$ePUPPYPIN" > "$PINBOARD" #/root/Choices/ROX-Filer/PuppyPin
 cat /tmp/pup_event_ok_pin >> "$PINBOARD" #/root/Choices/ROX-Filer/PuppyPin
 echo '</pinboard>' >> "$PINBOARD" #/root/Choices/ROX-Filer/PuppyPin
#fi

###END###
