#!/bin/sh

usage (){
	echo "
$0 [-h|-d|-v] [-g|-b|-l|-L|-s|-S|-X|-x|-z] DIR_NAME/
	-h) help: show this usage

	-g) gzip (default) '`which gzip`'
	-b) bzip2          '`which bzip2`'
	-l) lzop           '`which lzop`'
	-L) lzma           '`which lzma`'
	-s) squashfs3 gz   '`which mksquashfs3`'
	-S) squashfs4 gz   '`which mksquashfs4`'
	-X) squashfs4 xz   '`which mksquashfs4`'
	-x) xz             '`which xz`'
	-Z) compress       '`which compress||tar --help |grep -w '\-Z'|awk '{print $1 $2}'`'
	-z) zip            '`which zip`'
	Script to create a .tar of a directory with the above compressions.
	Without option given,defaults to the old and proven gzip
	compression.
	-d) debug through 'set -x'
	-v) verbose output and options to binaries
	"
	exit $1
}
OUTPUT='/dev/null'
while getopts gbhlLsSXxzdv opt;do
case $opt in
g) COMPRESS_BIN='gzip';OPT='-g';EXT='.gz';PET_EXT='.pet';;
b) COMPRESS_BIN='bzip2';OPT='-b';EXT='.bz2';PET_EXT='.b2pet';;
h) usage 0;;
l) COMPRESS_BIN='lzop';OPT='-l';EXT='.lzo';PET_EXT='.lopet';;
L) COMPRESS_BIN='lzma';OPT='-L';EXT='.lzma';PET_EXT='.lapet';;
s) COMPRESS_BIN='mksquashfs3';OPT='-s';EXT='.sfs3';PET_EXT='.s3pet';;
S) COMPRESS_BIN='mksquashfs4';OPT='-S';EXT='.sfs4';PET_EXT='.s4pet';;
X) COMPRESS_BIN='mksquashfs4';OPT='-X';EXT='.sfs4x';COMPRESS_OPT='xz';PET_EXT='.s4xpet';;
x) COMPRESS_BIN='xz';OPT='-x';EXT='.xz';PET_EXT='.xzpet';;
z) COMPRESS_BIN='zip';OPT='-z';EXT='.zip';PET_EXT='.zipet';;
Z) COMPRESS_BIN='compress';OPT='-Z';EXT='.Z';PET_EXT='.Zpet'
if [ ! "`which $COMPRESS_BIN`" ];then
COMPRESS_BIN='tar'
[ "`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
;;
d) set -x;;
v) VERBOSE='-v';LONG_VERBOSE='--verbose';OUTPUT='&2';;
*) usage 1;;
esac;done

[ "$COMPRESS_BIN" ] || { COMPRESS_BIN='gzip';OPT='-g';EXT='.gz';PET_EXT='.pet'; }
[ "`which $COMPRESS_BIN`" ] || { echo "'$COMPRESS_BIN' apparenty not installed (in the PATH)";exit 1; }

#[ "$2" ] && shift
#for i in `seq 2 1 $#`;do shift;done
while [ "$2" ];do shift;done #leave only the last argument



if [ ! $1 ];then
 echo 'Usage: # dir2tgz <name of directory>'
 exit 1
fi

DIRNAME="`echo -n $1 | sed -e 's%/$%%'`"
DIRNAME="`basename $DIRNAME`"
if [ ! -d $DIRNAME ];then
 echo "Error: $DIRNAME not found. Must open terminal in same directory."
 exit 1
fi

echo "Converting directory $DIRNAME to $DIRNAME.tar.gz..."

tar -c -f ${DIRNAME}.tar ${DIRNAME}/

#gzip ${DIRNAME}.tar
$COMPRESS_BIN $COMPRESS_OPT ${DIRNAME}.tar

sync
echo "Done"
