#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_dir2sfs"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/sbin/dir2sfs"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

Version='1.1-getopts Puppy-Linux-4.3.0 KRG'
usage (){
    echo "
$0 [-h|-d|-v] [-g|-b|-l|-L|-s|-S|-X|-x] DIR_NAME/
    -h) help: show this usage

    -g) gzip (default) '`which gzip`'
    -b) bzip2          '`which bzip2`'
    -l) lzop           '`which lzop`'
    -L) lzma           '`which lzma`'
    -s) squashfs3 gz   '`which mksquashfs3`'
    -S) squashfs4 gz   '`which mksquashfs4`'
    -X) squashfs4 xz   '`which mksquashfs4`'
    -x) xz             '`which xz`'
    -z) zip            '`which zip`'
    -Z) compress       '`which compress`'
    Script to create a .sfs from a dir with the above compressions.
    Without option given,defaults to the old and proven gzip
    compression.
    -d) debug through 'set -x'
    -v) verbose output and options to binaries
    "
    exit $1
}
OUTPUT=/dev/null;ERR=/dev/null
while getopts gbhlLsSXxZzdv opt;do
case $opt in
g) COMPRESS_BIN='gzip'; OPT='-g';EXT='gz'; PET_EXT='pet';;
b) COMPRESS_BIN='bzip2';OPT='-b';EXT='bz2';PET_EXT='b2pet';;
h) usage 0;;
l) COMPRESS_BIN='lzop';OPT='-l';EXT='lzo'; PET_EXT='lopet';;
L) COMPRESS_BIN='lzma';OPT='-L';EXT='lzma';PET_EXT='lapet';;
s) COMPRESS_BIN='mksquashfs3';OPT='-s';EXT='sfs3';PET_EXT='s3pet';;
S) COMPRESS_BIN='mksquashfs4';OPT='-S';EXT='sfs4';PET_EXT='s4pet';;
X) COMPRESS_BIN='mksquashfs4';OPT='-X';EXT='sfs4x';COMPRESS_OPT='xz';PET_EXT='s4xpet';;
x) COMPRESS_BIN='xz'; OPT='-x';EXT='xz'; PET_EXT='xzpet';;
z) COMPRESS_BIN='zip';OPT='-z';EXT='zip';PET_EXT='zipet';;
Z) COMPRESS_BIN='compress';OPT='-Z';EXT='.Z';PET_EXT='Zpet'
if [ ! "`which $COMPRESS_BIN`" ];then
COMPRESS_BIN='tar'
[ "`$COMPRESS_BIN --help |grep -w '\-Z'`" ] || COMPRESS_BIN='';fi
;;
d) set -x;;
v) VERBOSE='-v';LONG_VERBOSE='--verbose';OUTPUT=/dev/stdout;ERR=/dev/stderr;;
*) usage 1;;
esac;done

[ "$COMPRESS_BIN" ] || { COMPRESS_BIN='mksquashfs4';EXT='sfs';PET_EXT='s4pet'; }
[ "`which $COMPRESS_BIN`" ] || { echo "'$COMPRESS_BIN' apparenty not installed (in the PATH)";exit 1; }

#[ "$2" ] && shift
#for i in `seq 2 1 $#`;do shift;done
while [ "$2" ];do shift;done #leave only the last argument

. /etc/DISTRO_SPECS

echo "P-1:'$1'"

t=`echo "$1" | sed "s/\/$//"`
z=`echo "$1" | sed "s/\/$//"`


echo "t='$t'"
echo "z='$z'"


if [ ! -d "$t" ];then

  echo "error: no valid folder specified!"
  exit 0

fi

### if no _versionnummer in the end, get it from system
check=`echo $t | sed "s/\(.*\)_[0-9][0-9][0-9]$/\1/"`

#echo --- $check

if [ "$check" == "$t" ];then

  v=$DISTRO_VERSION
  z="${check}_$v"

fi
#echo $t - $z


if [ -f "$z.${EXT}" ];then

  echo "$z.${EXT} already exists, refusing to overwrite it!"
  exit 0

fi

#mksquashfs "$t" "$z.sfs"
$COMPRESS_BIN $COMPRESS_OPT "$t" "$z.${EXT}"
md5sum "$z.${EXT}" > "$z.${EXT}-md5.txt"
sync


echo
echo
s=`du -m "$z.${EXT}" | sed "s/\s.*//"`
echo "created: $z.${EXT} ( $s MB )"
echo "created: $z.${EXT}-md5.txt"
echo
echo "...byebye..."
echo
# Very End of this file 'sbin/dir2sfs' #
###END###
