#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_dir2tgz"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/sbin/dir2tgz"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

if [ ! $1 ];then
 echo 'Usage: # dir2tgz <name of directory>'
 exit 1
fi

DIRNAME="`echo -n $1 | sed -e 's%/$%%'`"
DIRNAME="`basename $DIRNAME`"
if [ ! -d $DIRNAME ];then
 echo "Error: $DIRNAME not found. Must open terminal in same directory."
 exit 1
fi

echo "Converting directory $DIRNAME to $DIRNAME.tar.gz..."

tar -c -f ${DIRNAME}.tar ${DIRNAME}/

gzip ${DIRNAME}.tar

sync
echo "Done"
# Very End of this file 'sbin/dir2tgz' #
###END###
