#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_load_consolefont"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/sbin/load_consolefont"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#(c) Copyright Barry Kauler 2012, license GPL3 (usr/share/doc/legal)
#a console font gets loaded in the initrd, or failing that in rc.country.
#i was also loading it in /usr/sbin/quicksetup is locale is changed.
#however, we have problems with it getting "dropped", which seems to happen when run X.
#so, i have created this script that will call whenever we exit from X, such as
#in xwin and in xorgwizard. thanks to L18L for investigating this.

#note, en locale will have empty /etc/fontmap...
[ ! -s /etc/fontmap ] && exit

FONTMAP="`cat /etc/fontmap`"

case $FONTMAP in
 LatArCyrHeb-16.psfu)
  setfont /lib/consolefonts/${FONTMAP}.gz -C /dev/tty1
 ;;
 *) #LatGrkCyr-8x16.psfu
  zcat /lib/consolefonts/${FONTMAP}.gz | loadfont
 ;;
esac

###END###
