#!/bin/ash

exec 1>>/tmp/photplug.log 2>&1

alias sed='busybox sed'
alias grep='busybox grep'
#alias awk='busybox awk' ##awk: applet not found

env #DEBUG

_install_fw_tar(){
test -d /lib/modules/all-firmware/ || return 1
local RV a
FIRMWARETAR=`find /lib/modules/all-firmware/ -maxdepth 1 -type f -iname "*${FIRMWARE%.*}*.tar.gz"`
for a in $FIRMWARETAR; do
/bin/tar $VERB -C / --strip-components=1 -xzf ${a}
RV=$((RV+$?))
done
return ${RV:-2}
}
_install_fw_bin(){
test -d /lib/modules/all-firmware/ || return 1
local RV a
FIRMWAREBIN=`find /lib/modules/all-firmware/ -type f -ipath "*/lib/firmware/*${FIRMWARE%.*}*"`
for a in $FIRMWAREBIN; do
cp $VERB -a ${a} /lib/firmware/
RV=$((RV+$?))
done
return ${RV:-2}
}
_load_fw(){
FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
test "$FIRMWAREBIN" || {
_install_fw_tar || _install_fw_bin
FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
test "$FIRMWAREBIN" || exit 1
}
test -f "$FIRMWAREBIN" || exit 1
echo "FIRMWAREBIN='$FIRMWAREBIN'"
echo 1 > /sys/$DEVPATH/loading
cat "$FIRMWAREBIN" > /sys/$DEVPATH/data
[ $? = 0 ] || echo "ERROR loading '$FIRMWAREBIN'"
echo 0 >/sys/$DEVPATH/loading
}
_load_module(){
        echo "MODALIAS='$MODALIAS'" #DEBUG
        #eval `modprobe -b -D "$MODALIAS"| grep -vE '^install|^blacklist|^options'`
        #exit
        LIST=`modprobe -b -D "$MODALIAS" | grep -vE '^install|^blacklist|^options' | sed 's%.*\(/.*\)\.k.*%\1%'`
        for m in $LIST ; do
        modprobe -b $Q $VERB "${m##*/}"
        done
}
_make_device(){

test "$DEVNAME" || DEVNAME="${SUBSYSTEM}/${DEVPATH##*/}"
test -e /dev/$DEVNAME && return 0

case $SUBSYSTEM in
block|partition) NOD=b;;
#'')              NOD='';;
*)               NOD=c;;
esac

DEV="/${DEVNAME}"
mkdir $VERB -p "/dev/${DEV%/*}"
echo "Creating /dev/$DEVNAME $NOD $MAJOR $MINOR .."
mknod /dev/$DEVNAME $NOD $MAJOR $MINOR
}

case $ACTION in
add)

#echo $MODALIAS #DEBUG
[ "$MODALIAS" ] && _load_module

[ "$MAJOR" -a "$MINOR" -a "$SUBSYSTEM" ] && { [ "$DEVNAME" -o "$DEVPATH" ] && _make_device; }

[ "$FIRMWARE" ] && _load_fw

;;
firmware) #not needed since k-3.7 :
#Teach the kernel to load firmware files directly from the filesystem instead of using udev
#http://kernelnewbies.org/Linux_3.7

#http://stackoverflow.com/questions/950107/how-does-linux-kernel-know-where-to-look-for-driver-firmware
test "$FIRMWARE" || exit 1
_load_fw
;;
*)
echo "
Unhandled ACTION '$ACTION'"
;;
esac
echo
