#!/bin/ash

exec 1>>/tmp/photplug.log 2>&1

#alias sed='busybox sed'
#alias grep='busybox grep'
#alias awk='busybox awk' ##awk: applet not found

echo
env

case $ACTION in
add)
[ "$MODALIAS" ] && {
        echo "MODALIAS='$MODALIAS'"
        LIST=`modprobe -b -D "$MODALIAS" | grep -vE '^install|^blacklist|^options' | sed 's%.*\(/.*\)\.k.*%\1%'`
        for m in $LIST ; do
        modprobe -b -v "${m##*/}"
        done

}

[ "$MAJOR" -a "$MINOR" -a "$SUBSYSTEM" ] && { [ "$DEVNAME" -o "$DEVPATH" ] && {

test "$DEVNAME" || DEVNAME="${SUBSYSTEM}/${DEVPATH##*/}"

sed -n '/Block devices:/,$ p' /proc/devices | grep "$SUBSYSTEM" | awk '{print $1}' | grep -w "$MAJOR" && {
        test -e /dev/$DEVNAME && exit
        DEV="/${DEVNAME}"
        mkdir -p "/dev/${DEV%/*}"
        mknod /dev/$DEVNAME b $MAJOR $MINOR
        exit $? ; }

[ "$SUBSYSTEM" = sound ] && GPATTERN='alsa|sound' || GPATTERN="$SUBSYSTEM"
sed -n '/Character devices:/,/Block devices:/p' /proc/devices | grep -E "$GPATTERN" | awk '{print $1}' | grep -w "$MAJOR" && {
        test -e /dev/$DEVNAME && exit
        DEV="/${DEVNAME}"
        mkdir -p "/dev/${DEV%/*}"
        mknod /dev/$DEVNAME c $MAJOR $MINOR
        exit $? ; }
 }
}

test "$FIRMWARE" && {
#echo -n 1 > /sys/$DEVPATH/loading

FIRMWAREBIN=`ls /lib/firmware/$FIRMWARE`
test "$FIRMWAREBIN" || FIRMWAREBIN=`ls /lib/firmware/*/$FIRMWARE`
test "$FIRMWAREBIN" || FIRMWAREBIN=`find /lib/modules/all-firmware -xdev -name "$FIRMWARE"`

test "$FIRMWAREBIN" || exit 1
test -f "$FIRMWAREBIN" || exit 1
echo "FIRMWAREBIN='$FIRMWAREBIN'"

test "$DEVPATH" || exit 1
test -e /sys/$DEVPATH/loading || exit 1
echo -n 1 > /sys/$DEVPATH/loading

test -e /sys/$DEVPATH/data || exit 1
cat "$FIRMWAREBIN" > /sys/$DEVPATH/data
if [ $? = 0 ]; then
    echo 0 >/sys/$DEVPATH/loading
else
echo "ERROR loading '$FIRMWAREBIN'"
fi
}

;;

*)
echo "
Unhandled ACTION '$ACTION'"
;;
esac
#echo
