#!/bin/sh


PROG='/sbin/poweroff'

sleep 5
echo "Really want to poweroff ? [Yy] :"
read -t 60 K
[ "$K" ] || K=Y
if [  ! "$K" = "y" -a ! "$K" = "Y" ] ; then
echo -e "\\033[1;34m""OK , stopping $PROG""\\033[0;39m"
echo
exit
fi

/etc/rc.d/rc.shutdown
Err=$?
if [ "$Err" -ne 0 ] ; then
if [ -n "`mount | grep '/proc`" ] ; then
echo -e "\\033[0;31m""Something went wrong running /etc/rc.d/rc.shutdown""\\033[0;39m"
echo -e "\\033[1;31m""Error returncode is '$Err'""\\033[0;39m"
echo
exit
fi
fi

exec /bin/busybox poweroff
