#!/bin/ash
#set -n
if [ "`ps | grep 'X' | grep -v 'grep'`" != "" ]; then

read WM </etc/windowmanager

if [ "`ps | grep "$WM" | grep -v '\[' | grep -v 'grep'`" != "" ]; then

exec wmpoweroff #&
#exit
fi
fi

. /etc/rc.d/PUPSTATE
case $PUPMODE in 5) :
;;
*)
_f1(){
# todo 1:
openvt -c 7
setlogcons 7  #Redirect the kernel output to console N (0 for current)
openvt -s -- /etc/rc.d/rc.shutdown || exit
while :; do pidof rc.shutdown && sleep 1; done
}

_f2(){
# todo 2:
openvt -sw -- /etc/rc.d/rc.shutdown || exit
}

_f3(){
# todo 3:
curFGC=`fgconsole`
openvt -s fgconsole >/tmp/fgconsole.out
read FGC </tmp/fgconsole.out #&& rm /tmp/fgconsole.out
openvt -c $FGC
chvt $FGC
}

USED_CONS=`ps -o tty | grep -E '^4|^tty' | sort -u`
for atty in `seq 1 1 12`; do
echo "$USED_CONS" | grep -E "tty$atty$|,$atty$" && continue
NEW_TTY=$atty
break
done

test "$NEW_TTY"
echo NEW_TTY=$NEW_TTY
#openvt -c $NEW_TTY
deallocvt $NEW_TTY
setconsole /dev/tty$NEW_TTY
chvt $NEW_TTY
#setconsole /dev/tty$NEW_TTY

/etc/rc.d/rc.shutdown </dev/tty$NEW_TTY >/dev/tty$NEW_TTY
;;
esac
case "$?" in '199') exit 0;;
0) :;;
*) exit 1;;
esac

exec /bin/busybox poweroff
