#!/bin/sh
#110505 support sudo for non-root user.

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

USED_CONS=`busybox ps -o tty | grep -E '^4|^tty' | sort -u`
for atty in `seq 1 1 12`; do
echo "$USED_CONS" | grep -E "tty$atty$|,$atty$" && continue
NEW_TTY=$atty
break
done

test "$NEW_TTY"
echo NEW_TTY=$NEW_TTY
#openvt -c $NEW_TTY
deallocvt $NEW_TTY
setconsole /dev/tty$NEW_TTY
chvt $NEW_TTY
#setconsole /dev/tty$NEW_TTY

/etc/rc.d/rc.shutdown </dev/tty$NEW_TTY >/dev/tty$NEW_TTY
case "$?" in '199') exit 0;;
0) :;;
*) exit 1;;
esac

exec /bin/busybox poweroff
