#!/bin/ash


PROG='/sbin/poweroff'

TTY=`tty`
test -c "$TTY" || TTY=/dev/console


[ "$DEBUG" ] && {
sleep 5
beep -f 700 -l 500
echo -n "Really want to poweroff ? [Yy] :"
read -t 60 K
K=${K:-Y}
case "$K" in y|Y) :;;
*) echo -e "\\033[1;34m""OK , stopping $PROG""\\033[0;39m"
echo
exit 55
;;
esac
}

/etc/rc.d/rc.shutdown
Err=$?
if [ "$Err" -ne 0 ] ; then
if [ -n "`mount | grep '/proc'`" ] ; then
echo -e "\\033[0;31m""Something went wrong running /etc/rc.d/rc.shutdown""\\033[0;39m"
echo -e "\\033[1;31m""Error returncode is '$Err'""\\033[0;39m"
echo
exit $Err
fi
fi

exec /bin/busybox poweroff "$@"
