#!/bin/ash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="pup_probepart8"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/sbin/probepart9"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || . /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP='1'; TWO_VERSION='1'; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#


###
#
###

DEBUGX=
DEBUG=
trap "exit 1" HUP INT QUIT KILL TERM
echo "$0:DEBUG='$DEBUG'" >&2

OUT=/dev/null;ERR=$OUT

[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

example usage : DEBUG=1 probepart -d/dev/sdc1 /dev/sdd1 -m

PARAMETERS:
-V|--version : showing version information
-H|--help : show this usage information

-b   : show size in bits
-B   : Bytes
-kb  : 1000-kilo bits
-mb  : 1000-mega bits
-gb  : 1000-giga bits
-Kib : 1024-kilo bits
-Mib : 1024-mega bits
-Gib : 1024-giga bits
-kB  : 1000-kilo Bytes
-mB  : 1000-mega Bytes
-gB  : 1000-giga Bytes
-KiB : 1024-kilo Bytes
-MiB : 1024-mega Bytes
-GiB : 1024-giga Bytes
-k : show sizes in kilobytes (KiB) #compat.
-m : show sizes in megabytes (MiB) #compat.
Without one of the above parameters it is the value found in
/sys/class/block/drive/size
; usually as blocksize=512 formatted to bits .

$2
"
echo "$USAGE_MSG"
exit $1
}

__deprecated_get_options__(){
[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }

##
SIZE_FACTOR=1
SIZE_PARAM=`echo "$@" | grep -m1 -o -w -i -E '\-k|\-m|\-b|\-B|\-kb|\-mb|\-gb|\-kib|\-mib|\-gib'`
  [ "$SIZE_PARAM" = '-b' ] && SIZE_FACTOR=1
  [ "$SIZE_PARAM" = '-B' ] && SIZE_FACTOR=8
 [ "$SIZE_PARAM" = '-kb' ] && SIZE_FACTOR=$((1*1000))
 [ "$SIZE_PARAM" = '-mb' ] && SIZE_FACTOR=$((1*1000*1000))
 [ "$SIZE_PARAM" = '-gb' ] && SIZE_FACTOR=$((1*1000*1000*1000))
 [ "$SIZE_PARAM" = '-KB' ] && SIZE_FACTOR=$((8*1000))
 [ "$SIZE_PARAM" = '-MB' ] && SIZE_FACTOR=$((8*1000*1000))
 [ "$SIZE_PARAM" = '-GB' ] && SIZE_FACTOR=$((8*1000*1000*1000))
[ "$SIZE_PARAM" = '-kib' ] && SIZE_FACTOR=$((1*1024))
[ "$SIZE_PARAM" = '-mib' ] && SIZE_FACTOR=$((1*1024*1024))
[ "$SIZE_PARAM" = '-gib' ] && SIZE_FACTOR=$((1*1024*1024*1024))
[ "$SIZE_PARAM" = '-KIB' ] && SIZE_FACTOR=$((8*1024))
  [ "$SIZE_PARAM" = '-k' ] && SIZE_FACTOR=$((8*1024))  ##compat.
[ "$SIZE_PARAM" = '-MIB' ] && SIZE_FACTOR=$((8*1024*1024))
  [ "$SIZE_PARAM" = '-m' ] && SIZE_FACTOR=$((8*1024*1024))  ##compat.
[ "$SIZE_PARAM" = '-GIB' ] && SIZE_FACTOR=$((8*1024*1024*1024))
}

_getopts(){
[ "$DEVICE" ] && { echo "Omitting $*" >&2; return 1; }
    local OPTION OPTIND OPTARG OPTERR
getopts d:: OPTION
case $OPTION in
d) : DEVICE="$DEVICE\\|$OPTARG"
   : DEVICE="$DEVICE|$OPTARG"
     DEVICE=$OPTARG
;;
esac
: DEVICE=`echo "$DEVICE" | sed 's!/dev/!!g;s!^\\\*!!;s!^|*!!;s!|*$!!'`
DEVICE=${DEVICE##*/}
echo "DEVICE='$DEVICE'" >&2
}

SIZE_FACTOR=1
while [ $# -gt 0 ]; do
case $1 in
*help|-H|-h) usage 0;;
*version|-V) echo "$0 -version $Version";exit 0;;
-?ignore*floppy|-?no*floppy) NO_FLOPPY=1;;
-b)SIZE_FACTOR=1;;
-B)SIZE_FACTOR=8;;
-kb)SIZE_FACTOR=$((1*1000));;
-mb)SIZE_FACTOR=$((1*1000*1000));;
-gb)SIZE_FACTOR=$((1*1000*1000*1000));;
-kB)SIZE_FACTOR=$((8*1000));;
-mB)SIZE_FACTOR=$((8*1000*1000));;
-gB)SIZE_FACTOR=$((8*1000*1000*1000));;
-kib)SIZE_FACTOR=$((1*1024));;
-mib)SIZE_FACTOR=$((1*1024*1024));;
-gib)SIZE_FACTOR=$((1*1024*1024*1024));;
-K[Ii]B|-k)SIZE_FACTOR=$((8*1024));;
-M[Ii]B|-m)SIZE_FACTOR=$((8*1024*1024));;
-G[Ii]B)SIZE_FACTOR=$((8*1024*1024*1024));;
-d)  _getopts $1 $2; shift;;
-d*) _getopts $1;;
*) _notice "Unrecognized option '$1'.";;
esac
shift
done

_do_disktype(){
    if test "$NO_FLOPPY"; then
    case $1 in fd*) echo "skipped";return 0;;esac
    fi
    disktype /dev/"$1" 2>>$ERR |grep -iE 'file system|Swap' |tail -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'
}

_get_filesystem(){
    _debugx "6"
    if test "$NO_FLOPPY"; then
    case $1 in fd*) FSTYPE=skipped; return 0;;esac
    fi
    _debugx "7"
    _debug "guess_fstype:"
    : [ "$FSTYPE" = 'not inserted' ] && FSTYPE=`guess_fstype /dev/"$1" 2>>$ERR`  #+++2013-12-27 awful fd hack...
    [ "$FSTYPE" ]  || FSTYPE=`guess_fstype /dev/"$1" 2>>$ERR`
    : [ "$FSTYPE" = 'unknown' ] && { FSTYPE=`disktype /dev/"$1" 2>>$ERR |grep -iE 'file system|Swap|squashfs' | sed 's/Linux//'|tail -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | tr -d '[[:punct:]]'` || FSTYE='not inserted'; }
    _debug "guess_fstype^"
     _debugx "8"
      # 2014-10-29 blkid for reiser4  #2014-11-02 busybox blkid for exFAT
      _debugx "FSTYPE='$FSTYPE'"
     [ "$FSTYPE" = 'unknown' ] && { FSTYPE=`blkid /dev/"$1" |grep -o ' TYPE="[[:alnum:]_]*"' | cut -f2 -d'"'` || FSTYPE=unknown; }
      _debugx "FSTYPE='$FSTYPE'"
      case $FSTYPE in   ## reiser v3 or v4
      *reiser*|*Reiser*|*REISER*)  FSTYPE=`_command blkid /dev/"$1" |grep -o ' TYPE="[[:alnum:]_]*"' | cut -f2 -d'"'`
      _debugx "FSTYPE='$FSTYPE'"
      esac

     [ "$FSTYPE" ] || FSTYPE=unknown
       _debug "FSTYPE='$FSTYPE'"

     case $REMOVEABLE in
     1)  _debug $1 is REMOVEABLE
        _debugx "FSTYPE='$FSTYPE'"
     [ "$FSTYPE" = 'unknown' ] && { FSTYPE=`disktype /dev/"$1" 2>>$ERR |grep -iE 'file system|Swap|squashfs'` && FSTYPE=`echo "$FSTYPE" | sed 's/Linux//'|tail -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | tr -d '[[:punct:]]'` || FSTYPE='not inserted'; }

    ;;
    0)  _debug $1 is not REMOVEABLE
     :
    ;;
    *)  _debug $1 has set '$REMOVEABLE' as REMOVEABLE
     :
    ;;
    esac
    [ "$FSTYPE" ]  || FSTYPE=unknown
}

_do_cddetect(){
    case $1 in fd*) return;; esac  #removable, [[ bash = x* ]]; not ash
    cddetect_quick -d/dev/"$1" &>$OUT && FSTYPE=`_do_disktype "$1"` || FSTYPE='not inserted'
}

_get_fdisk(){  #fdisk launches floppy engine, needed for ^fstype^ of ext'd partition
FDISK=`LC_ALL=C fdisk -l |grep '^/dev/' |tr -s '[[:blank:]]' |sed 's!\(/dev/[[:alnum:]]*\) \([[:digit:]]*\) \(.*\)!\1 N \2 \3!'`
}

_get_sfdisk(){  # launches floppy engine
FDISK=`LC_ALL=C sfdisk -l |grep '^/dev/' |tr -s '[[:blank:]]' |sed 's!\(/dev/[[:alnum:]]*\) \([[:digit:]]*\) \(.*\)!\1 N \2 \3!'`
}

_get_cfdisk(){
 test "$DEVICE" || return 1
#bash-3.00# cfdisk -P s /dev/sdb
#Partition Table for /dev/sdb
#
#               First       Last
# # Type       Sector      Sector   Offset    Length   Filesystem Type (ID) Flag
#-- ------- ----------- ----------- ------ ----------- -------------------- ----
# 1 Primary           0   101097044     63   101097045 HPFS/NTFS (07)       Boot
# 2 Primary   101097045   202210154      0   101113110 Linux (83)           None
# 3 Primary   202210155   404372114      0   202161960 Linux (83)           None
# 4 Primary   404372115  1953520064      0  1549147950 Extended (05)        None
# 5 Logical   404372115   470479589     63    66107475 Linux (83)           None

#bash-3.00# cfdisk -P r /dev/sda
#FATAL ERROR: Bad logical partition 6: enlarged logical partitions overlap
 cfdisk -P s /dev/$DEVICE
}

_get_parted(){ # launches floppy engine
#bash-3.00# parted -l | grep '^[ 0-9]\+'
# 1      32.3kB  50.0GB  50.0GB  primary   ext3
# 2      50.0GB  99.9GB  50.0GB  primary   ext3
# 3      99.9GB  125GB   25.0GB  primary   ext3         boot
# 4      125GB   500GB   375GB   extended
# 5      125GB   129GB   4006MB  logical   linux-swap

 parted -l
}

while read maj min drive rest; do
[ "$maj" ]   || continue
[ "$min" ]   || continue
[ "$drive" ] || continue
: [ "$DEVICE" ] && { case $drive in ${DEVICE##*/}*) :;;*) continue;; esac; }
[ "$DEVICE" ] && { case $DEVICE in *[0-9]) case $drive in ${DEVICE}) : echo 1 ok; :;;*) : echo 2 cont; continue;; esac;; *) case $drive in ${DEVICE}*) : echo 3 ok; :;;*) : echo 4 cont; continue;; esac;; esac; }
[ -f /sys/class/block/$drive/size ] || continue
_debugx "Step 1"
SIZE='';FSTYPE='';
read SIZE </sys/class/block/$drive/size && SIZE=$((SIZE*512*8)) || continue
[ "$SIZE" = $((2*512*8)) ] && { _get_fdisk
SIZE=$((`echo "$FDISK" |grep -w "^/dev/$drive" | awk '{print $5}' |sed 's#[^[:digit:]]##g'`*2*512*8));
                                      FSTYPE=`echo "$FDISK" |grep -w "^/dev/$drive" |cut -f7- -d ' '`; }
SIZE=$((SIZE/SIZE_FACTOR))
REMOVEABLE=0
_debugx "Step 2"
case $drive in
*[0-9])

 if   [ -r /sys/class/block/$drive/removable ]; then
 read REMOVEABLE </sys/class/block/$drive/removable
 elif [ -r /sys/class/block/$drive/device/removable ]; then
 read REMOVEABLE </sys/class/block/$drive/device/removable
 fi
 _debugx "Step 3"
 [ "$REMOVEABLE" = 0 ] || { case $drive in sr*|scd*) _do_cddetect "$drive";; esac; }
 _debugx "Step 4"
  _get_filesystem "$drive"
 _debugx "Step 5"
  echo "/dev/$drive|$FSTYPE|$SIZE" >&1
;;

*)
if [ -d /sys/class/block/$drive/device ]; then
 read REMOVEABLE </sys/class/block/$drive/removable
 if [ "$REMOVEABLE" = 1 ]; then
 if grep $Q -w '5' /sys/class/block/$drive/device/type >>$OUT; then
 _do_cddetect "$drive"
 _get_filesystem "$drive"
 echo "/dev/$drive|$FSTYPE|$SIZE" >&1
 fi;fi
fi
;;
esac

done </proc/diskstats

echo "$0:END" >&2
# Very End of this file 'sbin/probepart7' #
###END###
