#!/bin/ash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_probedisk2"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script to show recognized drives. Used by pup_event_frontend_d."

MY_SELF="/sbin/probedisk2"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

#!/bin/busybox-1.18.5-ST-98all-1379KB ash
#/root/my-applications/bin/kash
#/bin/bash
#bash-3.00.16-orig bash_3.2
#
#busybox-1.20.0-ST
#busybox-1.18.5-ST-98all-1379KB    busybox-1.21.1_upx9
#busybox-1.19.4-ST-98all-1388KB    busybox_1.18.3_STATIC_upx9_648KB
#
#LGPL 2007 Puppy Linux www.puppyos.com
#based on probedisk3 written by Dougal.
#small mods by BK 16 june 2007
# 21 Jun 2007 BK: force /proc update for usb drives.
#v3.93 10 dec 2007 BK: updated for 2.6.24 kernel, no /dev/hd*.
#v3.97 31jan2008 BK: refinement for detecting kernels with /dev/hd* drives.
#v4.01 10may2008 BK: bugfix for detecting if usb drive.
#v4.01 10may2008 BK: new 2nd-param categories. named 'probedisk2'.
#v4.01 21may2008 BK: zip and ls120 now categorized as 'floppy'.
#v4.02 9jun08 BK: correct detection of usb floppy.
#v403 fixed excessive spaces in description field.
#v406 support for old kernel, /proc/ide, /dev/hd*.

mountpoint $Q /sys >>$OUT || _exit 2 "/sys not mounted."

[ "$DEBUGT" ] && date +%N >&2
###KRG Fr 31. Aug 23:34:58 GMT+1 2012

PUP_EVENT_DIR="$HOME/Choices/Puppy/pup_event"
###KRG Mon Jul  8 22:35:19 GMT+1 2013

function_size(){
  if [ -f /sys/block/$oneDRV/size ] ; then
  read blocks_512 </sys/block/$oneDRV/size
  blocks_1024=$(( blocks_512/2 ))
  blocks_1000=$(( blocks_512 * 512 / 1000 ))
   if [ "$blocks_1024" -gt $((1024*1024)) ] ; then
   #GB
   SIZE_I=$(( blocks_1024 / 1024 / 1024 ))
   SIZE_K=$(( blocks_1000 / 1000 / 1000 ))
   SIZES="${SIZE_K}/${SIZE_I} G"
   elif [ "$blocks_1024" -gt 1024 ] ; then
   SIZE_I=$(( blocks_1024 / 1024 ))
   SIZE_K=$(( blocks_1000 / 1000 ))
   SIZES="${SIZE_K}/${SIZE_I} M"
   else
   SIZE_I=$blocks_1024
   SIZE_K=$blocks_1000
   SIZES="${SIZE_K}/${SIZE_I} K"
   fi
  else
  SIZES='not available'
  fi
}

function_partitions(){
  PARTITIONS=`LC_ALL=C ls -1v /sys/class/block/$oneDRV |grep -o '[[:digit:]]\+' |sort -n |tr '\n' ' '`
}

###KRGMon Jul  8 22:35:19 GMT+1 2013

. /etc/rc.d/PUPSTATE
#ATADRIVES is all ide/sata drives (not usb) (which all have /dev/sd notation).
#if old kernel supporting /dev/hd* then using SATADRIVES variable...
INTERNAL_SD_DRIVES="$SATADRIVES"
[ "$ATADRIVES" ] && INTERNAL_SD_DRIVES="$ATADRIVES"
_debug "DBG: intSDdrv=$INTERNAL_SD_DRIVES , usb=$USB_SATAD , ATA=$SATADRIVES , SATA=$ATADRIVES"

[ "$DEBUGT" ] && date +%N >&2
if [ -f "$PUP_EVENT_DIR"/usb-drive-log-probedisk ];then #force /proc upate mechanism
 for oneUSBDRV in `cat "$PUP_EVENT_DIR"/usb-drive-log-probedisk`
 do
  #disktype /dev/$oneUSBDRV > /dev/null 2>&1
  #dd if=/dev/$oneUSBDRV of=/dev/null bs=512 count=1 >>$OUT 2>>$ERR #v4.01 faster.
  (true </dev/$oneTESTDRV) >>$OUT 2>>$ERR
 done
fi
[ "$DEBUGT" ] && date +%N >&2

#crap, right now, /sys/block does not show my hdb cd/dvd drive, but it is in
#/proc/ide. pathetic kernel! oh well...
if [ ! -e /proc/ide ];then #v3.97
 ALLDRVS=`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd'`
else
 mountpoint $Q /proc >>$OUT || _exit 2 "/proc not mounted."
 ALLDRVS=`ls -1 /sys/block | grep -E '^scd|^sd|^mmc|^sr|^fd'`
`ls -1 /proc/ide | grep '^hd'`
fi
#note: after further testing, the 2.6.21.5 kernel exhibits inconsistent behaviour for hd devices, best to avoid.

[ "$DEBUGT" ] && date +%N >&2

for oneDRV in $ALLDRVS
do

  test -f /sys/block/$oneDRV/size && read SIZE </sys/block/$oneDRV/size

  case $oneDRV in
   hd*) # ide device, look in /proc/ide for info
     test -f /proc/ide/$oneDRV/media && read MEDIA </proc/ide/$oneDRV/media
     [ "$MEDIA" = "disk" ]  && MEDIA="drive"
     [ "$MEDIA" = "cdrom" ] && MEDIA="optical" #cdrom
     test -f /proc/ide/$oneDRV/model && read dINFO </proc/ide/$oneDRV/model
   ;;
   sd*) # scsi devices, look in /sys/block (all appear as Direct-Access)
     MEDIA="drive"
     test -f /sys/block/$oneDRV/device/vendor && read VENDOR </sys/block/$oneDRV/device/vendor
     test -f /sys/block/$oneDRV/device/model  && read MODEL  </sys/block/$oneDRV/device/model
     dINFO="$VENDOR $MODEL"
     DRVNAMES="$DRVNAMES `echo -n "$oneDRV" | cut -b 1-3` "

     #log if usb drive (not a sata drive)... v4.01...
      #if [ "`/bin/find /sys/devices -name "$oneDRV" | grep 'usb' | grep 'block'`" != "" ] ; then
      if [ "`readlink -f "/sys/block/$oneDRV" | grep 'usb'`" ] ; then
      MEDIA="usbdrv" #v4.01
      echo "$oneDRV" >> "$PUP_EVENT_DIR"/usb-drive-log-probedisk
      sort -u "$PUP_EVENT_DIR"/usb-drive-log-probedisk > /tmp/usb-drive-log-probedisk-tmp
      mv $VERB -f /tmp/usb-drive-log-probedisk-tmp "$PUP_EVENT_DIR"/usb-drive-log-probedisk
      #find out if a usb floppy drive...

      #if [ -f /sys/block/${oneDRV}/size ];then
      # [ "`cat /sys/block/${oneDRV}/size`" = "2880" ] && MEDIA="floppy"
      #fi
      test "$SIZE" = 2880 && MEDIA="floppy"

      if [ -f /sys/block/${oneDRV}/device/model ];then
       [ "`grep -E ' FDD| UF000x|Floppy|USB\-FDU|^FD\-|FLOPPY' /sys/block/${oneDRV}/device/model`" ] && MEDIA="floppy"
      fi
     # [ -f /sys/block/${oneDRV}/device/model ] && \
     #  grep $Q -E ' FDD| UF000x|Floppy|USB\-FDU|^FD\-|FLOPPY' /sys/block/${oneDRV}/device/model && \
     #   MEDIA="floppy"

     #else
      #find out if it is a removable internal drive (zip, ls120, etc)...
      elif [ -e /sys/block/${oneDRV}/removable ];then
       grep $Q -w '1' /sys/block/${oneDRV}/removable && MEDIA="floppy"
     #fi
     fi

   ;;
   scd*|sr*) #  scsi cdroms
     MEDIA="optical"
     test -f /sys/block/$oneDRV/device/vendor && read VENDOR </sys/block/$oneDRV/device/vendor
     test -f /sys/block/$oneDRV/device/model  && read MODEL  </sys/block/$oneDRV/device/model
     test "$VENDOR" || VENDOR='V unk'
     test "$MODEL"  || MODEL='P unk'
     dINFO="$VENDOR $MODEL"
   ;;
   mmc*) #/dev/mmcblk0
     MEDIA="card"
     #dINFO="MMC/SD: `cat /sys/block/$oneDRV/device/name`"
     test -f /sys/block/$oneDRV/device/name && read NAME </sys/block/$oneDRV/device/name
     test "$NAME" || NAME='VP unk'
     dINFO="MMC/SD: $NAME"
   ;;
    fd*)
     MEDIA='floppy'
     dINFO='Generic 1440KB'
   ;;
   *)
     continue
   ;;
  esac

  dINFO=`echo "$dINFO" | sed '/^$/d'`
  [ "$dINFO" ] || dINFO="SorryDiskWontTell"

     if  test "$SIZES" -a "$PARTITIONS"; then
   echo "/dev/$oneDRV|$MEDIA|$dINFO|$SIZES|$PARTITIONS"
   elif  test "$SIZES"; then
   echo "/dev/$oneDRV|$MEDIA|$dINFO|$SIZES"
   elif  test "$PARTITIONS"; then
   echo "/dev/$oneDRV|$MEDIA|$dINFO|$PARTITIONS"
   else
   echo "/dev/$oneDRV|$MEDIA|$dINFO"
     fi
   unset MEDIA dINFO SIZE SIZES PARTITIONS
   [ "$DEBUGT" ] && date +%N >&2

done
[ "$DEBUGT" ] && date +%N    >&2

#mounted drives/partitions...
MNTDDEVS=`awk -F'/' '/^\/dev\// {print $3}' /proc/mounts | grep -E '^hd|^sd|^scd|^sr|^mmc|^fd'`

#find out if a mounted device has been unplugged...
#for hotplug drives, remove it and it will disappear from /sys/block, however
#still shows up in 'mount' if hasn't been unmounted.
for oneMNTD in $MNTDDEVS
do
 case $oneMNTD in
  hd*|sd*|sr*)
   MNTDDRV="${oneMNTD:0:3}"
   ;;
  scd*)
   MNTDDRV="${oneMNTD:0:4}"
   ;;
  mmc*)
   MNTDDRV="${oneMNTD:0:7}"
   ;;
  *) echo "Unhandled '$oneMNTD'";;
 esac

 #prints to system log and to stderr...
  [ "$ALLDRVS" -a "$MNTDDRV" ] && { [ "`echo "$ALLDRVS" | grep "$MNTDDRV"`" ] || logger -s "$0: WARNING: UNPLUGGED '$oneMNTD' still listed in /proc/mounts"; }
done
[ "$DEBUGT" ] && date +%N  >&2
###END###
exit 0
