#!/bin/ash
#(c) Copyright 2008 Barry Kauler puppylinux.com
#2008 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#called via udev rule /etc/udev/rules.d/50-udev-puppy-basic.rules
#i pulled this code out of /sbin/pup_event_backend_d, see 4.1alpha3.
#all of the uevent variables (exs: MODALIAS, SUBSYSTEM) are available here.
#NOTICE: If the full 'udev' package, with utility 'udevd' is installed, rc.sysinit
#   will run 'udevd' instead of 'pup_event_backend_d' and this script will be used.
#v409 bugfix, FIRMWARE may have form 'subdir/firmware-file'.
#w004 LANG=C, faster. /bin/ash, even faster.


###KRG Fr 31. Aug 23:34:58 GMT+1 2012



trap "exit 1" HUP INT QUIT KILL TERM


OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x


Version='1.1'


usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

-V|--version : showing version information
-H|--help : show this usage information

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
exit $1
}

[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }



###KRG Fr 31. Aug 23:34:58 GMT+1 2012

export LANG=C #w004

LocalLOG='/tmp/pup_eve_bac_mod_fir.log'
TIME='date +%M.%S.%N'
echo $$ 1.0 `$TIME` " FIRMWARE=$FIRMWARE" >> $LocalLOG
echo $$ 1.1 `$TIME` " MODALIAS=$MODALIAS" >> $LocalLOG
echo $$ 1.2 `$TIME` "SUBSYSTEM=$SUBSYSTEM" >> $LocalLOG
echo $$ 1.3 `$TIME` "  DEVPATH=$DEVPATH" >> $LocalLOG

baseFIRMWARE=`basename $FIRMWARE` #v409
fndFIRMWARE=`find /lib/firmware -type f -name ${baseFIRMWARE}`

if [ "$fndFIRMWARE" != "" ];then
 echo 1 > /sys$DEVPATH/loading
 cat "$fndFIRMWARE" > /sys$DEVPATH/data
 echo 0 > /sys$DEVPATH/loading
else
 echo -1 > /sys$DEVPATH/loading
fi

###END###
