#!/bin/ash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_pup_event_backend_firmware"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/sbin/pup_event_backend_firmware"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#(c) Copyright 2008 Barry Kauler puppylinux.com
#2008 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#called via udev rule /etc/udev/rules.d/50-udev-puppy-basic.rules
#i pulled this code out of /sbin/pup_event_backend_d, see 4.1alpha3.
#all of the uevent variables (exs: MODALIAS, SUBSYSTEM) are available here.
#NOTICE: If the full 'udev' package, with utility 'udevd' is installed, rc.sysinit
#   will run 'udevd' instead of 'pup_event_backend_d' and this script will be used.
#v409 bugfix, FIRMWARE may have form 'subdir/firmware-file'.
#w004 LANG=C, faster. /bin/ash, even faster.

export LANG=C #w004

LocalLOG='/tmp/pup_eve_bac_mod_fir.log'
TIME='date +%M.%S.%N'
echo $$ 1.0 `$TIME` " FIRMWARE=$FIRMWARE" >> $LocalLOG
echo $$ 1.1 `$TIME` " MODALIAS=$MODALIAS" >> $LocalLOG
echo $$ 1.2 `$TIME` "SUBSYSTEM=$SUBSYSTEM" >> $LocalLOG
echo $$ 1.3 `$TIME` "  DEVPATH=$DEVPATH" >> $LocalLOG


baseFIRMWARE="`basename $FIRMWARE`" #v409
fndFIRMWARE="`find /lib/firmware -type f -name ${baseFIRMWARE}`"

if [ "$fndFIRMWARE" != "" ];then
 echo 1 > /sys$DEVPATH/loading
 cat "$fndFIRMWARE" > /sys$DEVPATH/data
 echo 0 > /sys$DEVPATH/loading
else
 echo -1 > /sys$DEVPATH/loading
fi

###END###
