#!/bin/sh
# Puppy/Woof does not use runlevels.
# /etc/init.d/dbus (in Ubuntu) runs 'runlevel' command at startup.
# Um, so I am providing a dummy here
# (it is normally in the sysvinit pkg)...

  _TITLE_=runlevel
_VERSION_=1.0omega
_COMMENT_="Replacement for the sysvinit command"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

#detect if a chrooted environment...
if [ ! -e /proc/mounts ];then
 echo "unknown"
 exit
fi

XSTATUS="no"
[ -z $DISPLAY ] || XSTATUS="yes"

if [ "$XSTATUS" = "no" ];then
 echo "2 3" #previous and current runlevels.
else
 echo "3 5"
fi
# Very End of this file 'sbin/runlevel' #
###END###
