#!/bin/sh
#LGPL 2007 www.puppylinux.com
# Replaces test-eide in Antonio Gallo's libhardware package.
#BarryK 19 June 2007

  _TITLE_=
_COMMENT_=""

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG=""
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

#hd* disk devices, mask off partitions...
#ALLDRVS="`grep ' hd' /proc/diskstats | tr -s ' ' | cut -f 4 -d ' ' | grep -v 'hd.*[0-9]$' | tr '\n' ' '`"
#no, has to be done this way...
ALLDRVS="`ls -1 /proc/ide | grep '^hd[a-z]'`"

for oneDRV in $ALLDRVS
do
 MEDIA="`cat /proc/ide/$oneDRV/media`"
 INFO="`cat /proc/ide/$oneDRV/model`"
 echo "/dev/$oneDRV - $MEDIA - $INFO"
done

###END###
