#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_focusModel"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/jwmconfig2/focusModel"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

##----focus model configuration for JWM---->>

#--------variables---------->>

CLICK='<FocusModel>click</FocusModel>'
SLOPPY='<FocusModel>sloppy</FocusModel>'
CONFIG="/root/.jwm/jwmrc-personal"
CONF="/root/.jwm/jwmrc-personal-temp"
CONF2="/root/.jwm/jwmrc-personal-temp2"
TMP="/tmp/inputbox.tmp.$$"

CHOICE=click
CLICK_ON=ON
SLOPPY_ON=off
VALUE="click"
SET_CLICK=`grep -c "$CLICK" $CONFIG`


if [ $SET_CLICK -eq 1 ]; then
    CLICK_ON=ON
    SLOPPY_ON=off
else
    CLICK_ON=off
    SLOPPY_ON=ON
    VALUE="sloppy"
fi

#----------dialogue-------->>

#!/bin/bash
# REM: Xdialog radiolist pre-defined "tag" "item" status_var
Xdialog --title "Focus Model" \
        --radiolist "Choose between the sloppy and click focus models:\n\n\
First, a little note on what these focus models are:\n\n\
SLOPPY FOCUS\n\
The window that is under the mouse pointer is the\n\
window that has the focus. The focus is changed\n\
by pointing at another window, there is no need\n\
to click in it as well.\n\n\
CLICK TO FOCUS\n\
The model used by Microsoft Windows.\n\
The active window is selected by mouse click.\n\n" 0 0 2 \
"click"  "click-to-focus" $CLICK_ON \
"sloppy" "sloppy focus" $SLOPPY_ON 2> $TMP

retval=$?

#--------clean exit------->>
case $retval in
  1)
    exit 0;;
  255)
    exit 0;;
esac

#--------preparation------>>

CHOICE=`cat $TMP`
rm -f $TMP

if [ -z $CHOICE ]; then
   CHOICE="click"
fi

SEDFOCUS=s!Model\>${VALUE}!Model\>${CHOICE}!g


#---------save changes----->>


sed -e "$SEDFOCUS" $CONFIG > $CONF

mv $CONF $CONFIG
rm -f $CONF2

#----notify of result----->>

RES=`grep -c ">$CHOICE" $CONFIG`

if [ $RES -eq 1 ]; then
    # REM: Xdialog msgbox
    Xdialog --title "Change_saved" --msgbox "Set to $CHOICE focus model" 0 0
fi

exit 0
