#!/bin/bash
##Quickpet 299 sv_SE 
#please translate this file and if possible keep the descriptions the same length or shorter 
#language=svenska
#translator=MinHundHettePerro (A.K.A/alias MHHP) - A native swede, who never had a swedish-speaking computer, but still thinks it's important to have things written in our own language, even though, mostly only the very young  would actually NEED this tranlation (for the understanding of the text, not for using the program ;) ).
#Översättare=MinHundHettePerro (alias MHHP) - En infödd svensk som aldrig haft en svensktalande dator, men som ändå tycker det är viktigt att ha saker skrivna på vårt eget språk, även om egentligen endast de mycket unga verkligen skulle BEHÖVA den här översättningen (för att förstå texten, inte för att använda programmet ;) ).
 

##################                    PLEASE NOTE                               ###############
#if you are unfamiliar with coding then you may notice "\n" in some lines                     #
#this means "new line" and it is important. I realise grammar is different in each language   #
#do place this "\n" every 6 to 10 words or 40 to 50 characters                                #
##################                  THANK  YOU                                  ###############

#Buttons and warnings - Knappar och varningar
export LOC_OK="Ok"
export LOC_CANCEL="Avbryt"
export LOC_ERROR="Fel"
export LOC_WARNING="Varning"
export LOC_YES="Ja"
export LOC_NO="Nej"
export LOC_QUIT="Avsluta"
export LOC_HELP="Hjälp"
export LOC_INFO="Info"
export LOC_FILE="Arkiv" 

#browser installer - Webläsarinstallerare
export LOC_001="Välkommen till"
export LOC_002="Vänligen, anslut till internet och välj därefter en Webläsare."
export LOC_003="Observera"
export LOC_004="Om du har mindre än 256 MB RAMminne rekommederas att du skapar en sparfil innan du installerar en webläsare."
export LOC_005="Enkel webläsare - installerad"
export LOC_006="Klicka för att installera Firefox"
export LOC_007="Klicka för att installera Seamonkey"
export LOC_008="Klicka för att installera Chromium"
export LOC_009="Klicka för att installera Opera"
export LOC_010="Klicka för att välja den medföljande enkla webläsaren som förvald webläsare."

#yaf messages
export LOC_101="FEL: Kan inte ladda ner. Vänligen, anslut till Internet."
export LOC_102="Vänta ..."
export LOC_103="FEL: Uppdateringssidan svarar inte. Kontrollera din anslutning eller försök igen senare."
export LOC_104="Du har redan den senaste uppdateringen för Lucid Puppy."
export LOC_105="För tillfället finns det inga uppdateringar för Lucid Puppy"
export LOC_106a="Vänta medan"
export LOC_106b="laddas ner. Du kommer sedan att ombedas att bekräfta installationen."
export LOC_107="Anslutningen avslutades. Försök igen senare."
export LOC_108="FEL: Nedladdningen misslyckades. Försök igen senare. Om nedladdningen påbörjades, kommer den att återupptas där den avbröts."
export LOC_109="FEL: Installationen av paketet misslyckades, försök igen."
export LOC_110a="Installationen av"
export LOC_110b="lyckades."
export LOC_111=" är nu satt som förvald webläsare."
export LOC_112="Quickpet körs redan. Vänta ..."
export LOC_113="Vänta, försöker lokalisera paketet ..."

#xmessages
#export LOC_201=deprecated
export LOC_202="Välkommen till Lucid Puppys Quickpet\!
	Det finns tre huvudflikar för Pet-paket, Puppys paketformat. Pet-paket är enkla att använda. När du valt ett paket och klickar på dess ikon så 
laddas paketet ner från något av Puppys repositorier. Detta kan ta litet tid om du har en långsam anslutning, så ha tålamod. När paketet laddats 
ned öppnas Puppys Pakethanterare (Puppy Package Manager) som ställer några enkla frågor och, 
så länge du väljer OK, installerar paketet och gör det redo att användas. 
Ett meddelande om att installationen lyckats kommer visas längst upp på skärmen.
	I inställningarna för Quickpet kan du välja det av Puppys filrepositorier 
	som fungerar bäst för dig. Om något inte fungerar eller är för långsamt 
	kan du välja ett annat.
    Det finns en drivrutinsflik, under vilken du kan installera en lämplig grafikdrivrutin för ditt grafikkort. För Nvidia finns det andra drivrutiner i  
Puppys Pakethanterare i huvudmenyn. För Radeon- och Intelkort rekommenderas \"Xorg High\"-paketet.  
	Det finns också en extra flik, Nyheter. Den är för nyheter om Lucid Puppy, 
med fixar och nya funktioner.
	Om du stöter på problem, finns en hjälpfil i Hjälpmenyn.
	Glöm inte att du också kan installera paket från Puppys vanliga pakethanterare, Puppy Package 
Manager, som du finner i Puppys huvudmeny. Även paket i Lucid Lynx .deb-format kan installeras.
	Hoppas du blir nöjd med Lucid Puppy."          ##changed Update for news
export LOC_203="Observera att nedanstående är länkar till 
applikationer som är kompilerade och paketerade av Puppy Linux-entusiaster. 
Ingen garanti lämnas, dock. De flesta faller under
Gnu GPL-licensen och dess varianter. De flesta av dessa program uppdateras 
regelbundet och är därför inte lämpliga att lagra i ett mer statiskt repositorium. 
Oftast får du här den senaste, stabila versionen, så att du håller ditt 
operativsystem uppdaterat med den senaste utvecklingen.
För att använda den här funktionen måste du ha en webläsare installerad. 
Klicka på webläsarikonen på skrivbordet för att ladda ner och installera en webläsare." #No changes  :)
export LOC_204="Om Quickpet inte fungerar för dig, förtvivla inte.
Alla paket finns tillgängliga i Puppys pakethanterare som nås från \"Install\"-ikonen på skrivbordet.
Du kan klicka på \"Quickpet on The Web\" så öppnas en websida där paketen 
kan laddas ner från direktlänkar. På sidan fås också tillgång till uppdateringar. 
Länkar finns också till andra program som har rapporterats fungera i Lucid Puppy under Fler Program-fliken.
	Du kan ändra ditt nedladdningsrepositorium i Arkivmenyn - Inställningar, till 
	en närmare plats eller till en spegelplats som fungerar bättre för dig. Dina inställningar sparas.  Du kan också ändra den förvalda inställningen att nedladdade paket (i /root.quickpet/Downloads) tas bort efter installationen till att spara dessa. 
	Nedladdade paket sparas i din sparfil (pupsave)/installation. Du kan se 
	vad som finns där genom att klicka på Nedladdningskatalog-menyn, och även 
	flytta dessa paket någonannanstans om du skulle vilja. Du kan också rensa 
	din Nedladdningskatalog med Rensa Nedladdade Paket i menyn om du valt att inte automatiskt ta bort dem.
	Det finns även en meny för SFS-filer. Detta är ett speciellt paketformat 
	som vanligen används för relativt stora program, vilka då kan installeras 
	utan att tära på utrymmet i din sparfil (pupsave). För mer information, klicka på 
SFS-Information i menyn.
Upplev Lucid Puppy!
Puppygänget." ##changed #Quickpet has a new option to save or delete downloads. Default is delete.

#gtkdialog Be careful with escape character "\" here.. 
#prefs
export LOC_298="Avmarkera rutan för att behålla dina nedladdade paket."             ####these 2 are new
export LOC_299="Rutan är markerad som standard."
export LOC_300="Puppys Pakethanterare \n \"Puppy Package Manager\""
export LOC_301="Alternativ för Quickpet"
export LOC_302="Ändringar genomförs när du klickar på OK."
export LOC_303="Välj ett repositorium."
#main gui
export LOC_304="Inställningar"
export LOC_305="på nätet"
export LOC_306="Juridiskt"
export LOC_307="Hjälp"
export LOC_308="LäsMig"
export LOC_309="Välkommen till"
export LOC_310="Detta är ett snabbalternativ till Puppys vanliga Pakethanterare (Puppy's Package Manager). Om du klickar på en paketikon så laddas paketet automatiskt ner och installeras."
export LOC_311="Populära Pet-paket"
export LOC_312="InternetPet-paket"
export LOC_313="Användbara Pet-paket"
export LOC_314="Drivrutiner"
export LOC_315="Nyheter"
export LOC_316="Välj ett Paket att installera"
export LOC_317="Välj en Webläsare eller E-postklient att installera"
export LOC_318="Välj ett Pet-Paket"
export LOC_319="Välj en Drivrutin"
export LOC_350="Fler Program"
export LOC_351="Nedladdningskatalog"
export LOC_352="Rensa Nedladdade Paket" 
export LOC_355="Om" 
export LOC_356="Videorapport" ##New in "File" menu
#Tooltips
export LOC_353="Om du klickar här visas nedladdade paket som sparats. Du kan dra dem till och släppa dem någon annanstans om du vill spara dem och rensa nedladdningskatalogen. Detta sparar dig litet utrymme i din sparfil (pupsave-fil)."
export LOC_354="Klicka här om du vill ta bort alla nedladdade paket"

#pets
export LOC_320="Gimp   Kraftfull Bildredigerare 23 MB" 
export LOC_321="Pwidgets  Små Skrivbordsapplikationer 283 KB"
export LOC_322="Audacity  Kraftfull Musikredigerare 6,7 MB"
export LOC_323="Songbird Mångfunktionell Musikhanterare 17 MB"
export LOC_324="Wine  Kör Windowsprogram 17 MB"
export LOC_325="Clan Bomber  Spännande Spel 5,3 MB"
export LOC_326="Google Earth  (Kräver högprestandagrafik) 44 MB" ###ADDED July 13
#internet
export LOC_501="Firefox  Populär Mozilla-Webläsare 15 MB"
export LOC_502="Seamonkey  Komplett Internetpaket 15 MB"
export LOC_503="Chromium  Ubuntu Chrome-Webläsare 23 MB"
export LOC_504="Opera  Snabbt Webläsarpaket 16 MB"
export LOC_505="Thunderbird  Mozillas E-postklient 12 MB"
export LOC_506="Kompozer  Websideshanterare/redigerare 9,2 MB"
#more pets
export LOC_601="Vlc Mångsidig Mediaspelare 28 MB" 
export LOC_602="Dia Diagramredigerare 4,3 MB"
export LOC_603="Cinelerra Videoredigerare 15 MB"
export LOC_604="JRE Java Runtime Environment 36 MB"
export LOC_605="Pdfedit  PDF-redigerare  5,2 MB" 
export LOC_606="Inkscape Vektorgrafikredigerare  23 MB"

#Drivers
######### MANY CHANGES THIS SECTION ########### check everything please  #Drivers
export LOC_389="Kontrollera att du har minst 80 MB ledigt utrymme innan du installerar en grafikdrivrutin." ##NEW
export LOC_390="En del system kräver att dessa extra drivrutiner installeras för att fullt ut kunna utnyttja dess funktioner." ##ALL NEW
#export LOC_391="RadeonHD For later model ATI Video Cards 372KB" deprecated, no harm to leave it though
export LOC_392B="Välj din rekommenderade drivrutin."
export LOC_392C="Det rekommenderas att du väljer den senaste drivrutinen för ditt kort."
export LOC_392Att="För äldre nVidiakort"
export LOC_392Btt="För medelålders, samt några nyare, nVidiakort"
export LOC_392Ctt="För nyare nVidiakort"
export LOC_392_96="Nvidia-96.43.16 7,4 MB"
export LOC_392_173="Nvidia-173.14.25 10 MB"
export LOC_392_256="Nvidia-256.35 14 MB"
export LOC_392x="Xorg High -GLX För Radeon- och Intelkort 14 MB"
export LOC_392h="Klicka här för installationshjälp."
#export LOC_392j="Nvidia-glx For later model Nvidia Video Cards" deprecated
export LOC_392a="Nvidia-glx För senare modeller av Nvidia Grafikkort."
export LOC_392tt="Om du klickar här får du förslag på tre drivrutiner. Om du inte vet vilken av dem du behöver, klicka på knappen ovanför." ##changed
export LOC_392vid="Klicka här för att testa ditt grafikkort."
export LOC_392ttvid="Här undersöks vilket grafikkort du har, så att du kan avgöra vilken drivrutin du behöver." 
export LOC_700="\n Om du vet att det är en ganska ny \n modell, klicka då \"Nej\" och \n installera nVidiadrivrutinen i Quickpet.\n Annars, klicka \"Ja\" och nVidias hemsida öppnas i din webläsare. \n Det finns andra nVidiadrivrutiner i Puppys Pakethanterare. \n Ditt kort är av modellen: \n "
export LOC_701="\n Använd Xorg_High-paketet i Quickpet"
export LOC_702="Du har"
export LOC_703="Du har"   #hmmm duplicated because different in French, Please run gui "test-vid" to see the context needed for your language###########
export LOC_704="Grafikkort"
export LOC_705="Klicka på knappen för att öppna din webläsare och översätta ovanstående text." ###New.. too hard to translate here, better let browser do it.
export LOC_706="Du måste ha en webläsare med svenska installerat."
#News
#Update IS now "News"
#export LOC_500="" deleted
export LOC_500B="Den här stora knappen tar dig till Lucid Puppys websida med senaste nyheter om Lucid Puppy. Av och till kommer uppdateringar för Lucid Puppy erbjudas på denna sida." ##New

#Xdialog ###deprecated
#export LOC_401="Lucid Puppy Driver Install"
#export LOC_402="You have chosen to install"
#export LOC_403="\nPlease note: There will be a message pop up when you install \n your nVidia driver, write the information down. \nWould you like to continue?"
#Clear Downloads
export LOC_801="Rensa Nedladdade Paket."
export LOC_802="Du har valt att rensa nedladdade paket. \nÄr du säker?" ##NEW! suggested by YoN.. good idea! Remember though, default is now delete but now there is a choice in Preferences

#END

