#!/bin/sh
#(c) Copyright Barry Kauler 2012, license GPL3 (/usr/share/doc/legal)
#call from: /usr/sbin/delayedrun, quicksetup, ...
#120331 ping -4 for ipv4, refer: http://murga-linux.com/puppy/viewtopic.php?p=616090#616090

_TITLE_=checkinternet
_VERSION_=1.0omega
_COMMENT_="CLI to ping google.com"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
 set +e
 source /etc/rc.d/f4puppy5 && {
 set +n
 source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."

ADD_PARAMETER_LIST=
ADD_PARAMETERS=
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
for i in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
} || echo "Warning : No /etc/rc.d/f4puppy5 installed."

export LANG=C

IFCONFIG="`ifconfig | grep '^[pwe]' | grep -v 'wmaster'`"
[ ! "$IFCONFIG" ] && exit 1 #no network connection.

ping -4 -c 1 8.8.8.8 #64.233.169.103 #google 111110 address no longer responding.
[ $? -ne 0 ] && exit 2 #ip address not accessable.

ping -4 -c 1 www.google.com
[ $? -ne 0 ] && exit 3 #domain name address not accessable.

exit 0 #success
###END###
