#!/bin/sh
#Barry Kauler 2007 www.puppylinux.com
#GPL license /usr/share/doc/legal/gpl-2.0.txt
#100526 add option to choose hardware clock set to local time or UTC.


test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG=""
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

export CountryWizard="
<window title=\"Puppy Setup: Country Settings\" icon-name=\"gtk-preferences\">
 <vbox>

  <hbox>
   <text>
    <label>Choose keyboard layout for your country...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-keyboard.xpm</input>
    <action>/usr/sbin/input-wizard &</action>
   </button>
  </hbox>

  <hbox>
   <text>
    <label>Choose hardware clock set to local-time or UTC...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-clock.xpm</input>
    <action>/usr/sbin/set_hwclock_type &</action>
   </button>
  </hbox>

  <hbox>
   <text>
    <label>Set the timezone for your region...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-clock.xpm</input>
    <action>/usr/sbin/timezone-set &</action>
   </button>
  </hbox>

  <hbox>
   <text>
    <label>Choose your locale (font-set/money/date-format)...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-font.xpm</input>
    <action>/usr/sbin/chooselocale &</action>
   </button>
  </hbox>

  <hbox>
   <button ok></button>
  </hbox>
 </vbox>
</window>
"

gtkdialog3 --program=CountryWizard

###END###
