#!/bin/sh


test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG=""
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}


DLG1="
 <wtitle>Puppy Linux Printer Manager</wtitle>
 <vbox>
  <text><label>Welcome to the Printer manager!</label></text>


  <frame Printer Management >
  <hbox>
     <text><label>Click the button to install a new Printer. </label></text>

   <vbox>
    <button>
     <input file>/usr/local/lib/X11/pixmaps/printer.png</input>
     <action>/usr/sbin/cups_shell2 &</action>
    </button>
       </vbox>
       </hbox>
    <text><label>\" \"</label></text>

  <hbox>
   <text><label>If you want to do General Printer Maintenance click this Button.</label></text>
   <vbox>
    <button>
     <input file>/usr/local/lib/X11/pixmaps/configuration48.png</input>
     <action>defaultbrowser http://localhost:631/ &</action>
    </button>
   </vbox>
   </hbox>
   <text><label>\"      \"</label></text>

  <hbox>
     <text><label>Once Your Finished Installing the Printer Click this Button and it will delete 19MB of extra drivers freeing up some space. </label></text>
   <vbox>
    <button>
     <input file>/usr/local/lib/X11/pixmaps/editdelete.png</input>
     <action>rm -rf /usr/share/cups/model/gutenprint/5.2</action>
    </button>
       </vbox>
       </hbox>
    <text><label>\" \"</label></text>

   <button cancel></button>
</frame>


 </vbox>





"

echo "$DLG1" | gtkdialog2 --stdin

###END###

