#!/bin/ash
# ROX App.: Click image files to mount & unmount. by: Terry Becker    aka: SunBurnt
# File types = ".2fs, .3fs, .sfs, .iso, & initrd.gz".
#v423 detect wrong squashfs version 3.x or 4.x.
#v424 advise of sfs-version-converter.

###KRG Fr 31. Aug 23:34:58 GMT+1 2012


########################################################################
#
# CHANGES by Karl Reimer Godt
# 01.0 : added xmessage dialog if already mounted to choose actions :
#        Quit,ROX-Filer,console,Unmount,Unmountall,MountAnotherTime
# 02.0 : position of removal of $mntPT changed in code
# 03.0 : double quoted all $imgFILE AND $mntPT in case of spaces
# 04.0 : added support for these extensions :
#        .squashfs, .sqfs, .squashfs.img -> .sfs
#        .ext3fs.img -> ext3
#        .iso -> iso9660 || udf || * ( using 'disktype' command )
#
# /dev/sda5:
# LABEL="MacPup430_F3"
# UUID="07443de5-1fab-4656-a3ab-7b1c14ccc8c8"
# TYPE="ext3"
# DISTRO_VERSION=430            #481·#416·#218·#478······#####change·this·as·required#####
# DISTRO_BINARY_COMPAT="puppy"  #"ubuntu"·#"puppy"·#####change·this·as·required#####
# case·$DISTRO_BINARY_COMPAT·in
# puppy)·#built·entirely·from·Puppy·v2.x·or·v3.x·or·4.x·pet·pkgs.
# DISTRO_NAME="Puppy"
# DISTRO_FILE_PREFIX="pup"      #"ppa"·#"ppa4"·#"pup2"··#pup4··###CHANGE·AS·REQUIRED,·recommend·limit·four·characters###
# DISTRO_COMPAT_VERSION="4"     #"2"··#4·····###CHANGE·AS·REQUIRED,·recommend·single·digit·5,·4,·3,·or·2###
# ;;
# esac
# PUPMODE=2
# KERNVER=2.6.30.7-KRG-i586
# ATADRIVES='·sda'
# USB_SATAD=''
# PUP_HOME='/'
# Linux·puppypc·2.6.30.7-KRG-i586·#2·SMP·Tue·Jan·4·15:42:45·CET·2011·i686·GNU/Linux
# Xserver=/usr/X11R7/bin/Xvesa_stripped_upx9
# $LANG=en_US
# today=Thu·Oct·27·11:44:41·CEST·2011
# TODO1 : cleanup my code
# TODO2 : cleanup original code
# TODO3 : observe fuser -c and fuser -m
# TODO4 : Kernel 3.x.x ready ~FIXED
# TODO5 : create grepPatternMntPt
# TODO6 : both fuser parts into one func
# TODO7 : adopt the code from npierce
#
########################################################################

Version='1.2-getopts Macpup_Foxy_3-Puppy-Linux-430/2 KRG'
test -f /etc/rc.d/f4puppy5 && source /etc/rc.d/f4puppy5

xmTITLE="PuppyFileMount"

usage (){
MSG="
$0 [-V|-v|-d|-h|-l] FILENAME.sfs
Script to mount and unmount
loop image, iso and squashfs files
[ by simple left click ] .

-V) show version
-v) verbose
-d) debug
-h) show this usage
-l) log to /tmp/filemnt.log
"
echo "$MSG"
[ "$DISPLAY" ] && xmessage -bg lightgreen -title "$xmTITLE" "$MSG"
exit $1
}
case $@ in
*-?help|*-?"help "*|-?help) usage 0;;
-?version) echo -e "\n$0: Version '$Version'\n";exit 0;;
esac
OUT=/dev/null;ERR=$OUT
while getopts Vvdhl opt;do
case $opt in
V) echo -e "\n$0: Version '$Version'\n";exit 0;;
v) VERBOSE=1;VERB=-v;L_VERB=--verbose;A_VERB=-verbose;ERR=/dev/stderr;OUT=/dev/stdout;shift;;
d) DEBUG=1;set -x;shift;;
h) usage 0;;
l) shift;exec 1>>/tmp/filemnt.log 2>&1;;
*) :;;
esac;done

echo
echo '----------------------------------------------------------------------'
#v423...
KERNELVER=`uname -r`
KERNEL_MAJ=${KERNELVER:0:1}
KERNELSUBVER=`echo -n "$KERNELVER" | cut -f 3 -d '.' | cut -f 1 -d '-'`
SFSSTR='squashfs, version 4'
if [ "$KERNEL_MAJ" -lt 3 ]; then
[ "$KERNELSUBVER" -lt 29 ] && SFSSTR='squashfs, version 3'
fi

imgFILE="$1"
if [ -z "$imgFILE" ]; then usage 1; fi
[ -f "$imgFILE" ] || { echo "'$imgFILE' seems not to be here . Exit ."; exit 1; }

if [ "`basename "$imgFILE"`" = 'initrd' ]   ; then
 if [ "`file "$imgFILE" | grep -i 'cpio'`" ]; then
  cd `dirname "$imgFILE"`
  rm -rf initrd-tree
  mkdir initrd-tree
  cd initrd-tree
  cat ../initrd |cpio -i -d
  exit $?
 else
  gzip -9 "$imgFILE"; fi
  exit $?
fi

if [ "`basename "$imgFILE"`" = 'initrd.gz' ]; then
 if [ "`file "$imgFILE" | grep -i 'cpio'`" ]; then
  cd `dirname "$imgFILE"`
  rm -rf initrd-tree
  mkdir initrd-tree
  cd initrd-tree
  zcat ../initrd.gz |cpio -i -d
  exit $?
 else
  gunzip "$imgFILE"; fi
  exit $?
fi

if [ "`basename "$imgFILE"`" = 'initrd.xz' ]; then
 if [ "`file "$imgFILE" | grep -i 'cpio'`" ]; then
  cd `dirname "$imgFILE"`
  rm -rf initrd-tree
  mkdir initrd-tree
  cd initrd-tree
  xzcat ../initrd.xz |cpio -i -d
  exit $?
 else
   xz -d "$imgFILE"; fi
   exit $?
fi

if [ "`dirname "$imgFILE"`" = '\.' ]; then # 2
      imgFILE=`pwd``echo "$imgFILE" |sed 's/^\.//'`
fi # 2


#mntPT='/mnt/'`echo "$imgFILE" |sed "s#^\.##g" |sed "s#/#+#g"`
mntPT='/mnt/'`basename "$imgFILE"`.$$  ##my change
grepPatternMntPt=`echo "$mntPT" | sed 's#\([[:punct:]]\)#\\\1#g'`
grepPatternImgFile=`echo "$imgFILE" | sed 's#\([[:punct:]]\)#\\\1#g'`

imgFileBASE=`basename "$imgFILE"` #BK  ##only for yaf/xmessage message not too long

if [ ! -d "$mntPT" ] ;then # 5 ### file's not mounted, mount it

check_already_mounted_func(){

  #BK check if already mounted elsewhere...
  for oneLOOP in `mount | grep '^/dev/loop' | cut -f 1 -d ' '`
  do

   IMG_MTP=`losetup-FULL "$oneLOOP" | cut -f 2 -d '(' | cut -f 1 -d ')'`
   IMGBASE=`basename "$IMG_MTP"`
    #TODO 64 chars
    #bash-3.2# losetup-FULL /dev/loop1
    #/dev/loop1: [0700]:2579 (/mnt/xubuntu-11.10-desktop-i386.iso.29782/casper/filesystem.sq*)
                            #1234567890123456789012345678901234567890123456789012345678901234

    echo "IMGBASE='$IMGBASE' imgFileBASE='$imgFileBASE'" #TEST
    #not perfect, but paths may be symlinks...

    if [ "$IMGBASE" = "$imgFileBASE" ];then #if [ "$MNTDIMG" = "$imgFILE" ];then #6

     # If frugal install check if it is in use
     case "$IMG_MTP" in
     */pup_ro[0-9]*) IN_USE_BY_PUPPY="and in use by Puppy";;
     esac

     if [ -n "$DISPLAY" ] ; then #66
xmessage -buttons "

Just
Quit
-->:190,

Open ROX-
Filer window
-->:191,

Open
console
-->:192,

Just Unmount
$IMGBASE
-->:193,

Unmount all
$IMGBASE
-->:194,

Mount an-
other time
-->:199
" -title "$xmTITLE" "$imgFILE
is already mounted $IN_USE_BY_PUPPY .
Do you want to unmount it
or mount it to another mount point ?"

RETVAL=$?

if [ "$RETVAL" = "190" ] ; then #666  ## Quit
     exit

elif [ "$RETVAL" = "191" ] ; then #666  ## open a ROX-Filer window
       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
       rox "$mntPT"
       exit

elif [ "$RETVAL" = "192" ] ; then #666  ## console
       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
       cd "$mntPT"
       _debug "`pwd`"
       rxvt &
       exit

elif [ "$RETVAL" = "193" ] ; then #666  ## umount
       UNMOUNT='yes'
       mntPT=`busybox mount | grep "$IMGBASE" | head -n 1 | cut -f 3 -d ' '`
       return

elif [ "$RETVAL" = "194" ] ; then #666  ## umount ALL $IMGBASE
       UNMOUNT='yes'
       mntPT=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
       _debug 1 "$mntPT"
       MntPt2=`echo "$mntPT" | sed "1 d"` ## only umount all others exect one
       _debug 2 "$MntPt2"

       for i in $MntPt2 ; do
       GREP=`echo "$i" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
       _debug "$GREP"
       LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
       _debug "$LOOPD"
       #USEapps=`fuser -c $LOOPD`     ##---2011-10-27
       USEapps=`fuser -m "$MntPt2"`   ##+++2011-10-27
       _notice 3 "$USEapps"
       USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g'`
       _debugx 4 "$USEapps"

       # REM: kill signal - use your preferred signal
       #      Supported signals are listed by 'help trap'
       SIG=2
       for j in $USEapps ; do
       _debugx "fuser claims pid '$j' is using '$mntPT'"
       kill -$SIG $j
       done

       #: [ -n "$DISPLAY" ] && rox -D "$i"
       /bin/umount "$i"
       #: sleep 2
       #: rmdir "$i"
       done

       mntPT=`busybox mount | grep "$IMGBASE" | cut -f 3 -d ' '`
       return

else #666
     MOUNT='again'
     return
fi   ###666
else ##66      ##+++2011-10-27 to fix call from without X running
UNMOUNT='yes'  ##+++2011-10-27
fi ##66
fi #6
done

}
check_already_mounted_func

fi # 5

if [ -z "$UNMOUNT" ] ; then #55 == yes || [ -n "$MOUNT" ] == again

  # get file type from extension
  #Ext=`echo "$imgFILE" |sed 's/^.*\.//'`
  Ext=${imgFILE##*.}
  if [ "$Ext" = '2fs' ]; then #7
   Type='ext2'
  elif [ "$Ext" = '3fs' ]; then
   Type='ext3'
  elif [  "$imgFileBASE" = 'ext3fs.img' ]; then
   Type='ext3'
  elif [ "$Ext" = '4fs' ]; then #v423 planning for the future!
   Type='ext4'
  elif [ "$Ext" = 'sfs' -o "$Ext" = 'squashfs' -o "$Ext" = 'sqfs' ]; then
   Type='squashfs'
  elif [ "$imgFileBASE" = 'squashfs.img' ]; then
   Type='squashfs'
  elif [ "$Ext" = 'iso' ]; then
   #Fatdog fat16 first and iso9660 second  ###+++2013-03-02
   TYPES=`disktype "$imgFILE" |grep 'file system'`
   if [ "`echo "$TYPES" |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]' | grep -i 'UDF'`" ]; then
    Type=udf
   else
    Type=iso9660
   fi

  else
   Type=`disktype "$imgFILE" |grep 'file system' |head -n1 |awk '{print $1}' |tr '[A-Z]' '[a-z]'` ##+++2012-06-04 udf or iso9660
   #Type='iso9660' ##---2012-06-04
   # BK
   #elif [ "$imgFILE" = 'initrd.gz' ] ;then
   # Type='ext2'
   # gunzip $imgFILE             # handle gzip image file
   # imgFILE="echo "$imgFILE" |sed 's/.gz$//'"
  fi #7

  #v423 detect wrong squashfs version...
  if [ "$Type" = "squashfs" ];then #8
   DISK_TYPE=`disktype "${imgFILE}"`
   if [ "`echo "${DISK_TYPE}" | grep "$SFSSTR"`" = "" ];then #8.1
    xmessage -bg orange1 "$DISK_TYPE"
    if [ $KERNEL_MAJ = 2 -a $KERNELSUBVER -gt 28 ] || [ $KERNEL_MAJ -gt 2 ];then #8.1.1
     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This may be an older version 3.x squashfs file, not usable.
All Linux kernels around 2.6.29 or later require version 4.x squashfs files.
Note, there is an SFS-version-converter in the Utility menu, run that first."
    else #8.1.1
     [ -n "$DISPLAY" ] && xmessage -center -bg '#FFC0C0' "NOTICE: This may be a newer version 4.x squashfs file, not usable.
All Linux kernels around 2.6.28 or earlier require version 3.x squashfs files.
Note, there is an SFS-version-converter in the Utility menu, run that first."
    fi #8.1.1
    exit
   fi #8.1
  fi #8

  #Crate loop device if neccessary
  _mk_free_loop

  #Finally mount it

  #: mkdir -p "$mntPT"

  _debug "\n$0 : Mount: '$imgFILE'\n"
  /bin/mount $VERB -t $Type -o loop "$imgFILE" "$mntPT"
  Err=$?     ##+++2011-10-27

  if [ "$Err" -eq 0 ] || [ -n "`mount | grep "$mntPT"`" ];then #9
   if [ -n "$DISPLAY" ] ; then #99
    yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg green -text "SUCCESS! Click $imgFileBASE icon again to unmount it" & #BK
   fi #99
  else
  #: sleep 2s
  #: [ -d "$mntPT" ] && { [ -z "`ls -A "$mntPT" 2>/dev/null`" ] && rmdir "$mntPT"; }  ##+++2011-10-27 2014-11-11
  :
  fi #9

 else #55   [ -n "$UNMOUNT" ]                   ### file's mounted, unmount it

   [ -n "$DISPLAY" ] && {
    #: rox -D "$mntPT" #BK
    yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" &
   }
       GREP=`echo "$mntPT" | sed 's#\.#\\\.#g;s#\+#\\\+#g;s#-#\\\-#g'`
       _debug 1 "$GREP"
       LOOPD=$(busybox mount | grep "$GREP" | cut -f 1 -d ' ')
       _debug 2 "$LOOPD"
       #USEapps=`fuser -c $LOOPD`   ##---2011-10-27
       USEapps=`fuser -m "$mntPT"`  ##---2011-10-27
       _notice 3 "$USEapps"
       USEapps=`echo "$USEapps" | sed 's/[[:alpha:]]//g;s/[[:punct:]]//g'`
       _debugx 4 "$USEapps"

       # REM: kill signal - use your preferred signal
       #      Supported signals are listed by 'help trap'
       SIG=2
       for j in $USEapps; do
       _debugx "fuser claims pid '$j' is using '$mntPT'"
       kill -$SIG $j
       done

  #: sleep 2s
  #: echo '------------'
  _debug "\n$0 : UnMount: '$imgFILE'\n"
  /bin/umount "$mntPT"
  Err=$?
  #: echo '------------'
  #: [ -n "$DISPLAY" ] && yaf-splash -timeout 3 -font "8x16" -outline 0 -margin 4 -bg orange -text "Unmounting $imgFileBASE" #BK
  #: sleep 2s  ##+++2011-10-27

  #: [ -d "$mntPT" ] && { [ -z "`ls -A "$mntPT" 2>/dev/null`" ] && rmdir "$mntPT"; }
 fi #55

 if [ "$Err" -gt 0 ] ;then          # ERROR: mount/unmount # 9999
  [ -n "$DISPLAY" ] && xmessage -bg red -title "$xmTITLE" "Error... Returned <$Err> ... mounting or unmounting '$mntPT'"
  #: [ -d "$mntPT" ] && { [ -z "`ls -A "$mntPT" 2>/dev/null`" ] && rmdir "$mntPT"; }  ##+++2011-10-27
 fi # 9999



# Very End of this file 'usr/sbin/filemnt' #
###END###
