#!/bin/bash
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.

test -x /usr/local/Puppybackground/resource/puppybackgroundsetterwrapper || exit 1
/usr/local/Puppybackground/resource/puppybackgroundsetterwrapper -stretch "$@"

