#!/bin/sh


HOME_func(){  #KRG
home="$HOME"
[ "$home" = "/" ] && home="/root"
echo "home='$home'"
}  #KRG
HOME_func  #KRG

#if [ -n "$1" ] && [ `echo " $1" | grep -i -E -e '\ \-k|\ \-k[a-z]*|\ \-[a-z]*k|\ \-[a-z]*k[a-z]*'` != "" ] ; then
#killall -1 ROX-Filer
#fi

case $1 in
k|kill|-k|-kill|--kill)
killall -1 ROX-Filer;;
esac

exec rox -p $HOME/Choices/ROX-Filer/PuppyPin
