#!/bin/sh

  _TITLE_=Puppy_Restart_ROX_With_PuppyPin
_VERSION_=1.0omega
_COMMENT_="CLI to restart ROX"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

HOME_func(){  #KRG
home="$HOME"
[ "$home" = "/" ] && home="/root"
echo "home='$home'"
}  #KRG
HOME_func  #KRG

#if [ -n "$1" ] && [ `echo " $1" | grep -i -E -e '\ \-k|\ \-k[a-z]*|\ \-[a-z]*k|\ \-[a-z]*k[a-z]*'` != "" ] ; then
#killall -1 ROX-Filer
#fi

case $1 in
k|kill|-k|-kill|--kill)
killall -1 ROX-Filer;;
esac

exec rox -p $HOME/Choices/ROX-Filer/PuppyPin
# Very End of this file 'usr/sbin/fixitup' #
###END###
