#!/bin/sh
#v2.14 Puppy now has XDG menus.
#this script builds the menus from template files.
#Any templates can be placed into /etc/xdg/templates, and the file must be
#named to show its final destination. For example, the template for JWM:
# _root_.jwmrc
#...the '_' will be converted to a '/', so the generated JWM config file is:
# /root/.jwmrc
# 5jan2008: fbpanel,lxpanel support developed by plinej.

TEMPLATES="`ls -1 /etc/xdg/templates | tr '\n' ' '`"

for ONETPL in $TEMPLATES
do
 [ "$ONETPL" = "README.txt" ] && continue
 ONEDEST="`echo -n "$ONETPL" | sed -e 's/_/\//g'`"
 ONESRC="/etc/xdg/templates/$ONETPL"
 echo "Generating $ONEDEST..."

 [ -f $ONEDEST ] && mv -f $ONEDEST ${ONEDEST}-previous

 cat $ONESRC |
 while read ONELINE
 do
  EXECMENU="`echo -n "$ONELINE" | grep -o 'PUPPYMENU.*' | cut -f 2-5 -d ' '`"
  echo "$EXECMENU"
  if [ "$EXECMENU" = "" ];then
   echo "appending '$ONELINE' to $ONEDEST"
   echo "$ONELINE" >> $ONEDEST
  else
   echo "else ...?"
   ${EXECMENU} >> ${ONEDEST}
  fi
 done

done

#w001 support for fbpanel, lxpanel, openbox, fluxbox, pekwm...
[ `which tempicons` ] && tempicons
which tempicons
[ `which fbpanel_menu_refresh` ] && fbpanel_menu_refresh
which fbpanel_menu_refresh
[ `which lxpanel_menu_refresh` ] && lxpanel_menu_refresh
which lxpanel_menu_refresh
[ `which jwm2fluxbox` ] && jwm2fluxbox  ##current fluxbox_menu_refresh doesn't support menu icons while this does
which jwm2fluxbox
[ `which obmenu-refresh` ] && obmenu-refresh
which obmenu-refresh
[ `which jwm2pekwm` ] && jwm2pekwm
which jwm2pekwm
###END###
