#!/bin/sh
#(c) Copyright Barry Kauler 2006 www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#BK Aug/Sept 2007: bugfixes for v2.20, 2.21
#BK Oct 2007: bugfix new version xrandr v3.02
#v3.99 BK apr 2008: workaround for dual monitors.
#v404 change to xwininfo, tidyup.


###KRG Fr 31. Aug 23:34:58 GMT+1 2012

trap "exit 1" HUP INT QUIT KILL TERM

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETER ]

-V|--version : showing version information
-H|--help : show this usage information

PARAMETER by default is \$1 , which should contain
the full(absolute) path including the PuppyPin file .
If \$1 is ommitted defaults to '/root/Choices/ROX-Filer/PuppyPin' .

RUBBISH CODE IMHO : It gets the current x-maximum of the screen and
also the x-placement of the Xlock icon . It then replaces
all icon x-values same as the Xlock's icon with a value
x-maximum of the screen -32 . Only usefull in PUPMODE=5 environment for
broad panel LCD monitors . If the Xlock icon is missing or
placed to the left of screen, the code would error or revert customations.

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
echo "$USAGE_MESG"
exit $1
}

[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }

###KRG Fr 31. Aug 23:34:58 GMT+1 2012

PUPPYPIN="$1"
[ "$PUPPYPIN" = "" ] && PUPPYPIN="/root/Choices/ROX-Filer/PuppyPin"

SCREENX=`xwininfo -root | grep -o '\-geometry.*x' | cut -f 2 -d ' ' | cut -f 1 -d 'x'`

if [ "$SCREENX" ];then

 #find out current right side in PuppyPin...
 RIGHTX=`grep 'Xlock' $PUPPYPIN | cut -f 2 -d '"'` #'Geany fix

 #all icons on right side of screen will be relocated to correct right side...
 NEWRIGHTX=`expr $SCREENX - 32`
 if [ "$RIGHTX" ] ; then
 if [ "$RIGHTX" != "$NEWRIGHTX" ];then
  APATTERN="s/x=\"${RIGHTX}\"/x=\"${NEWRIGHTX}\"/"
  cat $PUPPYPIN | sed -e "$APATTERN" > /tmp/PuppyPin
  sync
  cp -f /tmp/PuppyPin $PUPPYPIN
 fi
 fi

fi


###END###
