#!/bin/ash
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.
#try prevent freememapplet escaping tray when jwm restarted.

if [ "`pidof freememapplet inotifywait`" ]; then
killall freememapplet inotifywait 2>>$ERR
sleep 2
fi
exec freememapplet "$@"
