#!/bin/ash
#try prevent freememapplet escaping tray when jwm restarted.
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.

killall freememapplet
sleep 2
exec freememapplet
