#!/bin/sh
#(c) Copyright Nov 2009 Barry Kauler puppylinux.com
#2009 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
# Code taken out of the icon_switcher gui app.
# I created this script for desk_icon_theme_jq8flat-1 pet pkg, called from pinstall.sh
#w002 first creation.
#w477 record name of theme in /etc/desktop_icon_theme

  _TITLE_=
_COMMENT_=

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && . /etc/rc.d/f4puppy5

#************
#KRG

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = 2 ] && set -x

Version=1.1-KRG-MacPup_O2

usage(){
MSG="
$0 [ help | version | NEWTHEME ]
NEWTHEME : Required.
"
echo "$MSG
$2"
exit $1
}
[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0
[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }

trap "exit" HUP INT QUIT ABRT KILL TERM

#KRG
#************


test "$*" && NEWTHEME="$1"

[ "$NEWTHEME" = "" ] && _exit 1 "Need NEWTHEME ."
[ ! -d /usr/local/lib/X11/themes/${NEWTHEME} ] && exit

for oneSVG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.svg`
do
 oneBASENAME=`basename $oneSVG .svg`
 rm -f /usr/local/lib/X11/pixmaps/${oneBASENAME}48.png
 rsvg-convert -w 48 -h 48 -o /usr/local/lib/X11/pixmaps/${oneBASENAME}48.png $oneSVG
 rm -f /usr/local/lib/X11/pixmaps/${oneBASENAME}24.png
 #rsvg-convert -w 24 -h 24 -o /tmp/${oneBASENAME}24.png $oneSVG
 ##if svg has transparency, JWM does not render properly in x16 bit color, screen out...
 #pngtopnm -mix /tmp/${oneBASENAME}24.png | pnmtopng > /usr/local/lib/X11/pixmaps/${oneBASENAME}24.png
 rsvg-convert -w 24 -h 24 -o /usr/local/lib/X11/pixmaps/${oneBASENAME}24.png $oneSVG
done
for onePNG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.png`
do
 oneBASENAME=`basename $onePNG .png`
 cp -f $onePNG /usr/local/lib/X11/pixmaps/
 touch -m /usr/local/lib/X11/pixmaps/${oneBASENAME}.png #v3.98
 xONEBASENAME=`basename $oneBASENAME 48`
 if [ "$xONEBASENAME" != "$oneBASENAME" ];then #scale to 24 pixels...
  pngtopnm -alpha $onePNG > /tmp/temp.pbm #separate transparency channel.
  pnmscale -reduce 2 /tmp/temp.pbm > /tmp/temp2.pbm 2>$ERR
  pngtopnm $onePNG | pnmscale -reduce 2 2>$ERR | pnmtopng -alpha=/tmp/temp2.pbm > /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png
  touch -m /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png #v3.98
 fi
done

#w477 record current theme...
echo -n "$NEWTHEME" > /etc/desktop_icon_theme

# rox -p=/root/Choices/ROX-Filer/PuppyPin
# jwm -restart

###END###
