#!/bin/sh
# Called from modemprobe.

  _TITLE_="Puppy_modemprobe_help"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
 set +e
 source /etc/rc.d/f4puppy5 && {
 set +n
 source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."

ADD_PARAMETER_LIST=
ADD_PARAMETERS=
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
for i in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
} || echo "Warning : No /etc/rc.d/f4puppy5 installed."

export HELPDIALOG="
<window title=\"PupDial modem probe help\" icon-name=\"gtk-connect\">
 <vbox>
 <text  use-markup=\"true\"><label>\"<b>ALSA modem driver</b>
A driver starting with the text 'snd_' is an ALSA sound driver, but some of these also support on-board modems (port ttySL0). Thus, you cannot blacklist such a driver as that will also kill the sound.

<b>/dev/modem</b>
If this does not exist then at bootup Puppy will assign /dev/modem to the first modem driver that is found. If two modem drivers have loaded and you want to use the second, there are various ways to do this:

1. Totally manual
Manually create /dev/modem linked to the required port. You can do this in a terminal like this for example: # ln -sf ttyS0 /dev/modem You should also edit the 'Modem' entry in /etc/wvdial.conf, ex: Modem = /dev/ttyS0.

2. Blacklist and erase
You can click the BLACKLIST button and blacklist the driver that you do not want, then click the ERASE button which will delete /dev/modem and initialize the 'Modem' entry in /etc/wvdial.conf. Then at next bootup the correct modem should get selected.

<b>Hardware modems</b>
Puppy may autodetect some hardware modems at bootup, for example USB hardware modems, but serial modems and true-hardware plugin cards (ISA or PCI bus) are not autodetected at bootup. However, the PROBE button will scan for these, and you can even fall back to the individual 'ttyS0', 'ttyS1', etc., buttons if PROBE did not work right.\"</label></text>


 </vbox>
</window>
"

gtkdialog3 --program=HELPDIALOG
# Very End of this file 'usr/sbin/modemprobe_help' #
###END###
