#!/bin/sh
##! /usr/sbin/gtkdialog3 -e
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.
#BK nov 2007 gui frontend for dict.

DICT_BIN=dico #dict

HAVE_INTERNET=`ifconfig | grep '^[[:alnum:]]\+' | awk '{print $1}'`

for one in $HAVE_INTERNET ; do
case $one in
lo) HOST="--host 127.0.0.1"

#lo        Link encap:Local Loopback
#          inet addr:127.0.0.1  Mask:255.0.0.0
#          UP LOOPBACK RUNNING  MTU:16436  Metric:1
#          RX packets:284 errors:0 dropped:0 overruns:0 frame:0
#          TX packets:284 errors:0 dropped:0 overruns:0 carrier:0
#          collisions:0 txqueuelen:0
#          RX bytes:23577 (23.0 KiB)  TX bytes:23577 (23.0 KiB)
#
;;
*)  HOST="";;
esac
done

echo -n "" > /tmp/pdict-results.txt

_make_dict_list(){
DICTLIST="`dict --dbs`"
}

_make_dico_list(){
# dico --dbs --host=127.0.0.1
#dico: Warning: Not enough credentials for authentication
#gcide "The Collaborative International Dictionary of English v.0.48"
#wn "WordNet (r) 3.0 (2006)"
#foldoc "The Free On-line Dictionary of Computing (26 July 2010)"
#jargon "The Jargon File (version 4.4.7, 29 Dec 2003)"
#vera ""
#devil ""
#elements ""
#easton ""
#bouvier "Bouvier's Law Dictionary, Revised 6th Ed (1856)"

DICTLIST="`dico --dbs --host=127.0.0.1`"
echo "$DICTLIST"
}

_make_dict_sh(){
echo '#/bin/sh' > /tmp/pdict-func1
echo 'dict -d $2 $1  >/tmp/pdict-results.txt 2>&1'  >> /tmp/pdict-func1
chmod 755 /tmp/pdict-func1
}

_make_dico_sh(){
echo '#/bin/sh' > /tmp/pdict-func1
#echo 'dico --host=127.0.0.1 -d $2 $1  >/tmp/pdict-results.txt 2>&1'  >> /tmp/pdict-func1
echo "dico $HOST"' -d $2 $1  >/tmp/pdict-results.txt 2>&1'  >> /tmp/pdict-func1
chmod 755 /tmp/pdict-func1
}

case $DICT_BIN in

dict) _make_dict_list
COMBOCONTENT="`echo "$DICTLIST" | tr "'" "_" | grep '^ ' | grep -v '^ \-' | sed -e 's/^ //' | sed -e 's/^/<item>/' | sed -e 's/$/<\/item>/'`" #'geany
COMBOCONTENT="<item>all        Search all databases</item>
${COMBOCONTENT}"

_make_dict_sh
;;

dico) _make_dico_list
COMBOCONTENT=`echo "$DICTLIST" | tr "'" "_" | sed -e 's/^/<item>/' | sed -e 's/$/<\/item>/'`
echo "$COMBOCONTENT"

_make_dico_sh
;;

*)    echo "DICT_BIN : unhandled '$DICT_BIN'";exit;;

esac


export MAIN_DIALOG="
<window title=\"Pdict dictionary and thesaurus\" icon-name=\"gtk-info\">
 <vbox>
  <hbox>
   <text><label>enter a word:</label></text>
   <entry activates-default=\"true\">
    <variable>WORD</variable>
   </entry>
   <button has-default=\"true\">
    <input file stock=\"gtk-find\"></input>
    <label>dict</label>
    <action>/tmp/pdict-func1 \$WORD \$MYCHOICE</action>
    <action>refresh:INFO</action>
   </button>
  </hbox>
  <text><label>Choose which online database (default is all):</label></text>
  <combobox>
   <variable>MYCHOICE</variable>
$COMBOCONTENT
  </combobox>
  <frame result:>
   <edit>
    <variable>INFO</variable>
    <input file>/tmp/pdict-results.txt</input>
    <width>450</width>
    <height>300</height>
   </edit>
  </frame>
  <hbox>
   <button>
    <label>exit</label>
    <input file stock=\"gtk-quit\"></input>
    <action type=\"exit\">EXIT</action>
   </button>
  </hbox>
 </vbox>
</window>
"

_handle_gtkrc(){
#i don't know enough about themes to do this any better...
#note, normal gtkrc is now ~/.gtkrc
cp -f /etc/gtk-2.0/gtkrcMONOSPACED /etc/gtk-2.0/gtkrc
echo '#!/bin/sh
 sleep 2
 rm -f /etc/gtk-2.0/gtkrc
' > /tmp/delaygtkrc.sh
chmod 755 /tmp/delaygtkrc.sh
/tmp/delaygtkrc.sh &
}

RETSTRING="`gtkdialog3 --program=MAIN_DIALOG`"

rm /tmp/pdict*

###END###
