#!/bin/sh
#BK dummy for now
#v407 install firmware tarball if not installed.

__old_header__(){
###KRG Fr 31. Aug 23:34:58 GMT+1 2012

trap "exit 1" HUP INT QUIT KILL TERM

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

-V|--version : showing version information
-H|--help : show this usage information

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
exit $1
}

[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }

###KRG Fr 31. Aug 23:34:58 GMT+1 2012
}

  _TITLE_=
_COMMENT_=

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

[ "`which pgprs-setup`" != "" ] && exec pgprs-setup

#xmessage "Currently only works with the Multitech GPRS modem.
#If the MT GPRS modem is plugged in, Puppy should have loaded
#the 'firmware tarball' which includes the /usr/bin/mt-gprs-setup
#script. If it isn't there, you get this message."

#install firmware tarball...
cp -f /lib/modules/all-firmware/pgprs.tar.gz /tmp/
cd /tmp
tar -zxf pgprs.tar.gz
cp -a --remove-destination /tmp/pgprs/* /
sync
cd /
/pinstall.pgprs.sh >$OUT 2>$ERR #execute script.
rm -f /pinstall.pgprs.sh >$OUT 2>$ERR

exec pgprs-setup
