#!/bin/ash
#BK dummy for now
#v407 install firmware tarball if not installed.
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.

[ "`which pgprs-setup`" ] && exec pgprs-setup

#xmessage "Currently only works with the Multitech GPRS modem.
#If the MT GPRS modem is plugged in, Puppy should have loaded
#the 'firmware tarball' which includes the /usr/bin/mt-gprs-setup
#script. If it isn't there, you get this message."

#install firmware tarball...
cp $VERB -f /lib/modules/all-firmware/pgprs.tar.gz /tmp/
cd /tmp
tar -zxf pgprs.tar.gz
cp $VERB -a --remove-destination /tmp/pgprs/* /
sync
cd /
/pinstall.pgprs.sh >$OUT 2>&1 #execute script.
rm -f /pinstall.pgprs.sh >$OUT 2>&1

exec pgprs-setup
