#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_plogout"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/sbin/plogout"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

window = fltk:Fl_Window(100, 100, 225, 400, "Exit");

secondButton = fltk:Fl_Button(20, 35, 180, 40, "Exit to prompt");
secondButton:color(219)
fourthButton = fltk:Fl_Button(20, 80, 180, 40, "Reboot Computer");
fourthButton:color(219)
fifthButton = fltk:Fl_Button(20, 125, 180, 40, "Shutdown Computer");
fifthButton:color(219)
sixthButton = fltk:Fl_Button(20, 170, 180, 40, "Restart X Server");
sixthButton:color(219)
eighthButton = fltk:Fl_Button(20,215,180,40, "e17");
eighthButton:color(219)
ninthButton = fltk:Fl_Button(20,260,180,40, "jwm");
ninthButton:color(219) 


quitButton1  = fltk:Fl_Button(20, 305, 180, 40, "Cancel");
quitButton1:color(1)

i=0


secondButton:callback(
	function(slider1)
                   a=io.popen('"/usr/sbin/exitprompt"');
                   os.exit();
	end)

fourthButton:callback(
	function(slider1)
                   a=io.popen('"/usr/bin/wmreboot"');
                   os.exit();
	end)
fifthButton:callback(
	function(slider1)
                   a=io.popen('"/usr/bin/wmpoweroff"');
                   os.exit();
	end)
sixthButton:callback(
	function(slider1)
                   a=io.popen('"/usr/bin/restartwm"');
                   os.exit();
	end)
eighthButton:callback(
    function(slider1)
	               a=io.popen('"/usr/bin/goe17go"');
				   os.exit();
	end) 
ninthButton:callback(
    function(slider1)
                   a=io.popen('"/usr/bin/gojwmgo"');
				   os.exit();
	end)	
				   				   	

function quit_callback(object)
      window:hide();
      os.exit()
end

window:callback(quit_callback)
quitButton1:callback(quit_callback)

Fl:background2(255,0,0)
Fl:scheme("plastic")
window:show()
Fl:run()
# Very End of this file 'usr/sbin/plogout' #
###END###
