#!/bin/sh
#BK play a dvd
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.

MYVIDOUT=""
[ "`readlink /usr/X11R7/bin/X`" = "Xvesa" ] && MYVIDOUT="-vo x11"

[ "`which mplayer`" != "" ] && exec gmplayer $MYVIDOUT dvd://1

exec defaultmediaplayer dvd://1

###END###
