#!/bin/sh

trap "exit 1" HUP INT QUIT KILL TERM

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

-V|--version : showing version information
-H|--help : show this usage information

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
exit $1
}

[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }


if [ ! -e /etc/modemdevice ];then
 echo "You have not setup your Internet connection yet"
 echo "1. First, run \"Modem Wizard\" to choose a modem"
 echo "2. Second, run \"Setup PPP Dialup\" to configure PPP"
 echo "3. ...come back here!"
 echo " "
 echo -n "Press ENTER key to continue..."
 read VAL1
else
 #/usr/sbin/ppp -c
 #sleep 10
 #now using gkdial...
 exec /usr/sbin/gkdial
fi
#echo -n "Press ENTER key to continue..."
#read VAL1

# have created a fvwm button (right side of screen) that waits
# for a window named "Blinky" and will swallow it...
#blinky -u 500 ppp0 &
# ...displays 2 modem leds, just like Windows.
# ...no, this isn't the right place to start Blinky.
