#!/bin/sh

  _TITLE_=pup_ppp_connect.sh
_COMMENT_="Cli wrapper for gkdial"

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
    for i in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

if [ ! -e /etc/modemdevice ];then
 echo "You have not setup your Internet connection yet"
 echo "1. First, run \"Modem Wizard\" to choose a modem"
 echo "2. Second, run \"Setup PPP Dialup\" to configure PPP"
 echo "3. ...come back here!"
 echo " "
 echo -n "Press ENTER key to continue..."
 read VAL1
else
 #/usr/sbin/ppp -c
 #sleep 10
 #now using gkdial...
 exec /usr/sbin/gkdial
fi
#echo -n "Press ENTER key to continue..."
#read VAL1

# have created a fvwm button (right side of screen) that waits
# for a window named "Blinky" and will swallow it...
#blinky -u 500 ppp0 &
# ...displays 2 modem leds, just like Windows.
# ...no, this isn't the right place to start Blinky.
