#!/bin/sh

  _TITLE_="pup_pppdisconnect.sh"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
 set +e
 source /etc/rc.d/f4puppy5 && {
 set +n
 source /etc/rc.d/f4puppy5; } || echo "WARNING : Could not source /etc/rc.d/f4puyppy5 ."

ADD_PARAMETER_LIST=
ADD_PARAMETERS=
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
for i in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
} || echo "Warning : No /etc/rc.d/f4puppy5 installed."

/usr/sbin/ppp -d
sleep 5
echo "Now disconnected from Internet"
echo -n "Press ENTER key to continue..."
read VAL1

# pppconnect started blinky, fvwm swallowed "Blinky" window,
# kill it...
#killall blinky
# Very End of this file 'usr/sbin/pppdisconnect' #
###END###
