#!/bin/sh
. /etc/rc.d/f4puppy5
# BATCHMARKER01 - Marker for Line-Position to bulk insert code into.

/usr/sbin/ppp -d
sleep 5
echo "Now disconnected from Internet"
echo -n "Press ENTER key to continue..."
read VAL1

# pppconnect started blinky, fvwm swallowed "Blinky" window,
# kill it...
#killall blinky
