#!/bin/sh
#BK july 2003


  _TITLE_=Puppy_PPP_Setup
_VERSION_=1.0omega
_COMMENT_="CLI to run ppp -s"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

if [ ! -e /etc/modemdevice ];then
 echo "You are not yet ready to configure the PPP..."
 echo "First run \"Modem Wizard\" to choose a modem"
 echo " "
else
 DEVM=`cat /etc/modemdevice`
 echo "You previously used \"Modem Wizard\" and chose $DEVM"
 echo "HOWEVER, /dev/modem has been linked to this, so PLEASE"
 echo "type \"modem\" when asked below for the modem device..."
 /usr/sbin/ppp -s
 sleep 1
fi
echo -n "Press ENTER key to continue..."
read VAL1
# Very End of this file 'usr/sbin/pppsetup' #
###END###
