#!/bin/sh
#Barry Kauler, Oct. 2011
# Called via udev /etc/udev/rules.d/88-puppy-autodetect.rules
#111007 first release.
#111010 maybe wait until delayedrun has done its stuff.


  _TITLE_=Puppy_Autodetect
_VERSION_=1.0omega
_COMMENT_="UDEV helper script to run pupcamera"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST="camera"
ADD_PARAMETERS="camera : Run pupcamera"
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

[ ! "$1" ] && exit
[ "`pidof X`" == "" ] && exit #X not running.
export PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/root/my-applications/bin'
export DISPLAY=':0'

#111010 maybe wait until delayedrun has done its stuff...
EXCNT=0
while [ ! -f /tmp/delayedrun_finished_flag ];do #see /usr/sbin/delayedrun.
 sleep 2
 EXCNT=$(($EXCNT + 1))
 [ $EXCNT -gt 10 ] && break #precaution
done


case $1 in
 camera)
  pupcamera &
 ;;

esac
# Very End of this file 'usr/sbin/pupautodetect' #
###END###
