#! /bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_quisp_shell"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/sbin/quisp_shell"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#(c) Copyright Barry Kauler August 2009, licence: GPL2
#this is a script to start and stop QUISP, using the hiawatha web server.
#v423 not using a separate httpd.conf anymorefor quisp and pplog.
#v425 lobster reports en_GB causes server error.

#************
#KRG

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = 2 ] && set -x

Version=1.1-KRG-MacPup_O2

usage(){
MSG="
$0 [ help | version ]
"
echo "$MSG
$2"
exit $1
}
[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0
[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }

trap "exit" HUP INT QUIT ABRT KILL TERM

#KRG
#************


export LANG=C #v425 overkill solution.

#note, also doing this in /etc/profile.d/quisp...
export SHSQL_DB='/root/Web-Server/Quisp'

error_func() {
 ERRMSG=`cat /tmp/hiawatha_error`
 xmessage -center -bg 'red' -buttons EXIT:10 -title "QUISP database client" "There was an error when attempting to start Hiawatha, this error message:

${ERRMSG}

Click EXIT button to quit:"
 exit
}

PSSTATUS=`ps`

#v423 remove...
#if [ "`echo "$PSSTATUS" | grep ' hiawatha'`" != "" ];then
# if [ "`echo "$PSSTATUS" | grep ' hiawatha' | grep '/root/Web\-Server'`" = "" ];then
#  xmessage -center -bg '#ffc0c0' -buttons START:10,EXIT:11 -title "QUISP database client" "QUISP requires the Hiawatha web server to be running.
#It is running, but unfortunately is configured for use with
#another application. It has to be killed now then restarted.
#Click the RESTART button to do this, otherwise click EXIT to quit."
#  [ $? -ne 10 ] && exit
#  hiawatha.run stop
#  sleep 1
#  echo '' > /tmp/hiawatha_error
#  hiawatha -c /root/Web-Server 2>/tmp/hiawatha_error
#  [ $? -ne 0 ] && error_func
# fi
#fi

if [ "`echo "$PSSTATUS" | grep ' hiawatha'`" = "" ];then
 xmessage -center -bg '#ffc0c0' -buttons START:10,EXIT:11,Introduction:15 -title "QUISP database client" "QUISP requires the Hiawatha web server to be running.
Click the 'START' button to do this, otherwise click 'EXIT' to abort.
Or, click 'Introduction' to read an introduction to QUISP..."
 RETVAL=$?
 [ $RETVAL -eq 15 ] && exec defaulthtmlviewer file:///usr/share/doc/quisp/quisp_overview.html
 [ $RETVAL -ne 10 ] && exit
 echo '' > /tmp/hiawatha_error
 #v423 no longer using separate httpd.conf...
 ##hiawatha will read /root/Web-Server/httpd.conf instead of the default
 ##/etc/hiawatha/httpd.conf...
 #hiawatha -c /root/Web-Server 2>/tmp/hiawatha_error
 hiawatha 2>/tmp/hiawatha_error
 [ $? -ne 0 ] && error_func
  cd /root/Web-Server #probably not required.
  exec defaulthtmlviewer http://127.0.0.1:80/cgi-bin/quisp.bin
fi

xmessage -center -bg 'orange' -buttons QUISP:10,STOP:11,EXIT:12 -title "QUISP database client" "
Click the 'QUISP' button to run the QUISP web interface.

The Hiawatha web server is currently running, which is required for QUISP.
If you want to stop the server and exit, click the 'STOP' button.

To just quit, click the 'EXIT' button:"

case $? in
 10)
  cd /root/Web-Server #probably not required.
  exec defaulthtmlviewer http://127.0.0.1:80/cgi-bin/quisp.bin
 ;;
 11)
  hiawatha.run stop
  exit
 ;;
 *)
  exit
 ;;
esac


###END###
