#!/bin/sh
# generic wrapper to run as spot (when currently running as root)
# (C) James Budiono 2012
# License: GPL version 3 or later
#130604 BK: slight mods. see also /usr/sbin/setup-spot (support/setup-spot in woof).

  _TITLE_=run_as_spot
_VERSION_=1.0omega
_COMMENT_="Wrapper to run apps as USER 'spot'"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST="APP & ARGS"
ADD_PARAMETERS="APP  : Program-Name to run
ARGS : Options to program-name"
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

[ ! $1 ] && exit
CWD=$(pwd)
APP="$1"; shift
ARGS=""
[ $1 ] && while [ "$1" ]; do ARGS="$ARGS \"$1\""; shift; done
if [ $(id -u) -eq 0 ]; then
 [ $XAUTHORITY ] && cp $XAUTHORITY /root/spot/.Xauthority 2>$ERR
 touch /root/spot/.Xauthority
 #following line is mostly there to catch any root:root files that may have got copied in...
 chown -R spot:spot /root/spot &
 export XAUTHORITY=/root/spot/.Xauthority
 export XDG_CONFIG_HOME=/root/spot/.config
 export XDG_CACHE_HOME=/root/spot/.cache
 export XDG_DATA_HOME=/root/spot/.local/share
 #exec su spot -s /bin/sh -c "cd \"$CWD\"; \"$APP\" $ARGS"
 exec su spot -s /bin/sh -c "\"$APP\" $ARGS"
else #precaution
 exec "$APP" "$ARGS"
fi
# Very End of this file 'usr/sbin/run-as-spot' #
###END###
