#!/bin/sh
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#sends a request to /usr/sbin/savepuppyd to save the session.
#v4.01 19may2008 BK: request now to /sbin/pup_eventd (savepuppyd is history).
#v411 /tmp/snapmergepuppyrequest is processed in /sbin/pup_event_frontend_d. (from v403 i think)



#************
#KRG


OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = 2 ] && set -x


Version=1.1-KRG-MacPup_O2

usage(){
MSG="
$0 [ help | version ]
"
echo "$MSG
$2"
exit $1
}
[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0
[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }


trap "exit" HUP INT QUIT ABRT KILL TERM


#KRG
#************


yaf-splash -display :0 -font "8x16" -outline 0 -margin 4 -bg yellow -text "NOTICE:
Request to save current session is queued. Please wait,
another message will popup when the saving occurs..." &
RETVAL=$?
YAFPID=$!

touch /tmp/snapmergepuppyrequest

while [ -f /tmp/snapmergepuppyrequest ];do
 sleep 1
done

[ $RETVAL -eq 0 ] && kill $YAFPID


###END###
