#!/bin/sh
#BK Aug 2009, gpl

__old_header__(){  #BEGIN
###KRG Fr 31. Aug 23:34:58 GMT+1 2012

trap "exit 1" HUP INT QUIT KILL TERM

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

-V|--version : showing version information
-H|--help : show this usage information

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
exit $1
}

[ "`echo "$1" | grep -wE "\-help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wE "\-version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }

###KRG Fr 31. Aug 23:34:58 GMT+1 2012
}  ###__old_header__(){  #END

  _TITLE_=Puppy_Set_XFTdpi
_COMMENT_="Xdialog to set the letter pixel size"

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

export LANG=C #xdialog happy with this.

#read current dpi setting...
CURRDPI=`cat $HOME/.Xresources | grep "^Xft\\.dpi:" | tr '\t' ' ' | tr -s ' ' | cut -f 2 -d ' '`
[ ! $CURRDPI ] && CURRDPI=78
CURRINDEX=`expr $CURRDPI \/ 6`
CURRINDEX=`expr $CURRINDEX - 9`

CNT=0; RADIOBUTTONS=''
for oneDPI in 54 60 66 72 78 84 90 96 102 108
do
 STATUS='off'
 [ $CNT -eq $CURRINDEX ] && STATUS='on'
 RADIOBUTTONS="$RADIOBUTTONS $oneDPI $oneDPI $STATUS"
 CNT=`expr $CNT + 1`
done

echo CURRDPI=$CURRDPI CURRINDEX=$CURRINDEX
#XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --radiolist \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 0 ${RADIOBUTTONS}"
#XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --rangebox \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 50 120 $CURRDPI"
XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --spinbox \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 50 120 $CURRDPI fontsize"
#Xdialog --left --stdout --title="TEST" --spinbox "SPINBOX" 0 0 10 100 50 label

NEWDPI=`eval "$XDIALOG"`
[ $? -ne 0 ] && { echo "ERROR occured $0 at $LINENO. Nothing changed in .Xresources"; exit 1; }
echo NEWDPI=$NEWDPI

TMP1=`cat $HOME/.Xresources | grep -vEe '^Xft\.dpi:|^[[:blank:]]*Xft\.dpi:'`
echo "$TMP1" > $HOME/.Xresources
echo "Xft.dpi: $NEWDPI" >> $HOME/.Xresources
sync

###END###
