#!/bin/sh
#BK Aug 2009, gpl


  _TITLE_=Puppy_Set_XFTdpi
_VERSION_=1.0omega
_COMMENT_="Xdialog to set the letter pixel size"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

export LANG=C #xdialog happy with this.

#read current dpi setting...
CURRDPI=`cat $HOME/.Xresources | grep "^Xft\\.dpi:" | tr '\t' ' ' | tr -s ' ' | cut -f 2 -d ' '`
[ ! $CURRDPI ] && CURRDPI=78
CURRINDEX=`expr $CURRDPI \/ 6`
CURRINDEX=`expr $CURRINDEX - 9`

CNT=0; RADIOBUTTONS=''
for oneDPI in 54 60 66 72 78 84 90 96 102 108
do
 STATUS='off'
 [ $CNT -eq $CURRINDEX ] && STATUS='on'
 RADIOBUTTONS="$RADIOBUTTONS $oneDPI $oneDPI $STATUS"
 CNT=`expr $CNT + 1`
done

echo CURRDPI=$CURRDPI CURRINDEX=$CURRINDEX
#XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --radiolist \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 0 ${RADIOBUTTONS}"
#XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --rangebox \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 50 120 $CURRDPI"
XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --spinbox \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 50 120 $CURRDPI fontsize"
#Xdialog --left --stdout --title="TEST" --spinbox "SPINBOX" 0 0 10 100 50 label

NEWDPI=`eval "$XDIALOG"`
[ $? -ne 0 ] && { echo "ERROR occured $0 at $LINENO. Nothing changed in .Xresources"; exit 1; }
echo NEWDPI=$NEWDPI

TMP1=`cat $HOME/.Xresources | grep -vEe '^Xft\.dpi:|^[[:blank:]]*Xft\.dpi:'`
echo "$TMP1" > $HOME/.Xresources
echo "Xft.dpi: $NEWDPI" >> $HOME/.Xresources
sync

###END###
