#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014

  _TITLE_="Puppy_set-xftdpi"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/sbin/set-xftdpi"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}
# End new header
#
#BK Aug 2009, gpl

__old_default_info_header__(){
  _TITLE_=Puppy_Set_XFTdpi
_COMMENT_="Xdialog to select XFT dot per inch"

MY_SELF="$0"

#************
#KRG

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = 2 ] && set -x

Version=1.1-KRG-MacPup_O2

usage(){
MSG="
$0 [ help | version ]
"
echo "$MSG
$2"
exit $1
}

[ "`echo "$1" | grep -Ei "help|\-h"`" ] && usage 0 "$_COMMENT_"
[ "`echo "$1" | grep -Ei "version|\-V"`" ] && { echo "$0: $Version";exit 0; }

trap "exit" HUP INT QUIT ABRT KILL TERM

#KRG
#************
}

export LANG=C #xdialog happy with this.

#read current dpi setting...
CURRDPI=`cat $HOME/.Xresources | grep "^Xft\\.dpi:" | tr '\t' ' ' | tr -s ' ' | cut -f 2 -d ' '`
[ ! $CURRDPI ] && CURRDPI=78

CURRINDEX=`expr $CURRDPI \/ 6`
CURRINDEX=`expr $CURRINDEX - 9`

CNT=0; RADIOBUTTONS=''
for oneDPI in 54 60 66 72 78 84 90 96 102 108
do

 STATUS='off'
 [ $CNT -eq $CURRINDEX ] && STATUS='on'
 RADIOBUTTONS="$RADIOBUTTONS $oneDPI $oneDPI $STATUS"
 CNT=`expr $CNT + 1`
done

XDIALOG="Xdialog --left --stdout --title \"Set global font size\" --no-tags --radiolist \"Please choose dpi (dots per inch) for the screen.\nThe larger the value, the bigger that antialiased\nfonts will render on the screen. Adjust up or down if\nfonts are rendering too small or too big on screen.\n\nNote1: Some apps do not use antialiased rendering\n            and will not be affected by this setting.\n\nNote2: Change will only take affect after restarting X\" 0 0 0 ${RADIOBUTTONS}"

NEWDPI=`eval "$XDIALOG"`
[ $? -ne 0 ] && exit

TMP1=`cat $HOME/.Xresources | grep -v "Xft\\.dpi:"`

echo "$TMP1" > $HOME/.Xresources
echo "Xft.dpi: $NEWDPI" >> $HOME/.Xresources

sync

###END###
