#!/bin/sh
#SILICON MOTION hack around 111005
#added SILICON INTEGRATED SYSTEMS 111006
#boot to desktop

#makes xorgwizard-automatic run
. /etc/DISTRO_SPECS
[ "$DISTRO_XORG_AUTO" = "yes" ]&& exit
sed -i 's%no%yes%' /etc/DISTRO_SPECS

#fix xorg.conf
if [ ! -f /etc/X11/xorg.conf ];then xorgwizard-automatic
  else
  rm -f /etc/X11/xorg.conf
  xorgwizard-automatic
fi
  