#!/bin/sh
#(c) Copyright Barry Kauler 2007 www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
# Utility to select the timezone.
# Note, as Puppy will mostly be on PCs coexisting with Windows,
# hardware clock (CMOS) is set to local time (see /etc/rc.d/rc.local0)
#BK oct2007: updated for 3.02
#w019 april 2009: cli mode so can run from /etc/rc.d/rc.update
#100525 hardware clock can be utc or localtime (thanks to pizzasgood).
#100526 screen out UTC timezone, causes confusion (separate script to choose localtime or UTC).

  _TITTE_=Puppy_Set_Timezone
_COMMENT_="Dialog to select time zone"

MY_SELF="$0"

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
    for i in `seq 1 1 $DO_SHIFT`; do shift; done; }
_trap
}


export LANG=C
. /etc/clock #100525

XSTATUS="no"
[ -z $DISPLAY ] || XSTATUS="yes"
[ $1 ] && XSTATUS="no"

if [ -e /etc/localtime ];then
 CZONE="`readlink /etc/localtime`"
 [ "$CZONE" = "" ] && rm -f /etc/localtime
fi

if [ -e /etc/localtime ];then
 CZONE="`readlink /etc/localtime`"
 DEFTAG="`readlink /etc/localtime | sed -e 's%/usr/share/zoneinfo/%%'`"
else
 CZONE='/usr/share/zoneinfo/Etc/GMT-8' #these have opposite sign.
 DEFTAG='Etc/GMT-8'
fi

#if [ "`echo -n "$DEFTAG" | grep 'GMT' | grep '\+'`" = "" ];then
# DEFTAG="`echo -n "$DEFTAG" | sed -e 's%Etc/%%' | tr "\-" "\+"`"
#else
# DEFTAG="`echo -n "$DEFTAG" | sed -e 's%Etc/%%' | tr "\+" "\-"`"
#fi
DEFTAG="`echo -n "$DEFTAG" | sed -e 's%Etc/%%'`"

#100526 screen out UTC timezone, causes confusion...
ZONEINFO="`find /usr/share/zoneinfo -type f | grep -v '\.tab$' | grep -v 'UTC' | sed -e 's%/usr/share/zoneinfo/%%' | sed -e 's%Etc/%%' | tr ' ' '_' | sort`"

ZONECHOICES=""
for oneZONE in $ZONEINFO
do
 oneDESCR="."
 [ "$oneZONE" = "GMT" ] && continue
 [ "$oneZONE" = "GMT-0" ] && continue
 case $oneZONE in
  GMT+0)     oneDESCR='(London, Dublin, Edinburgh, Lisbon, Reykjavik, Casablanca)';;
  GMT-1)     oneDESCR='(Azores, Cape Verdes)';;
  GMT+1)     oneDESCR='(Paris, Berlin, Amsterdam, Brussels, Madrid, Stockholm Oslo)';;
  GMT-2)     oneDESCR='(mid-Atlantic)';;
  GMT+2)     oneDESCR='(Athens, Helsinki, Istanbul, Jerusalem, Harare)';;
  GMT-3)     oneDESCR='(Brasilia, Buenos Aires, Georgetown)';;
  GMT+3)     oneDESCR='(Kuwait, Nairobi, Riyadh, Moscow)';;
  GMT-4)     oneDESCR='(Caracas, La Paz, Canada)';;
  GMT+4)     oneDESCR='(Abu Dhabi, Muscat, Tblisi, Volgograd, Kabul)';;
  GMT-5)     oneDESCR='(Bogota, Lima, New York)';;
  GMT+5)     oneDESCR='(Islamabad, Karachi)';;
  GMT+5:30)  oneDESCR='(India)';;
  GMT-6)     oneDESCR='(Mexico City, Saskatchewan)';;
  GMT+6)     oneDESCR='(Almaty, Dhaka)';;
  GMT+6:30)  oneDESCR='(Cocos Islands)';;
  GMT-7)     oneDESCR='(Alberta, Montana, Arizona)';;
  GMT+7)     oneDESCR='(Bangkok, Jakarta)';;
  GMT-8)     oneDESCR='(Los Angeles)';;
  GMT+8)     oneDESCR='(Perth, Singapore, Hongkong)';;
  GMT-9)     oneDESCR='(Alaska)';;
  GMT+9)     oneDESCR='(Tokyo)';;
  GMT+9:30)  oneDESCR='(Darwin, Adelaide)';;
  GMT-10)    oneDESCR='(Alaska, Hawaii)';;
  GMT+10)    oneDESCR='(Guam)';;
  GMT+10:30) oneDESCR='(Lord Howe Island)';;
  GMT-11)    oneDESCR='(Samoa)';;
  GMT+11)    oneDESCR='(Magadan, Soloman Is.)';;
  GMT-12)    oneDESCR='(Eniwetok)';;
  GMT+12)    oneDESCR='(Wellington, Fiji, Marshall Islands)';;
  GMT+13)    oneDESCR='(Rawaki Islands)';;
  GMT+14)    oneDESCR='(Line Islands)';;
 esac
 ZONECHOICES="${ZONECHOICES}${oneZONE} \"${oneDESCR}\" "
done

if [ "$XSTATUS" = "yes" ];then
 ZONEDLG="Xdialog --stdout --title \"Puppy timezone selector\" --default-item $DEFTAG --menubox \"Please choose your timezone.\\nIf a city/region/country in your timezone is not listed, choose a GMT<number>\" 0 0 0 $ZONECHOICES"
 eval $ZONEDLG >/tmp/zoneretval
else
 ZONEDLG="dialog --aspect 10 --title \"Puppy timezone selector\" --default-item $DEFTAG --menu \"Please choose your timezone. If a city/region/country in your timezone is not listed, choose a GMT<number>\" 0 0 0 ${ZONECHOICES}"
 eval $ZONEDLG 2>/tmp/zoneretval
fi

[ $? -ne 0 ] && exit

ZONERETVAL="`cat /tmp/zoneretval`"

#if [ "`echo -n "$ZONERETVAL" | grep 'GMT' | grep '\+'`" = "" ];then
# ZONERETVAL="`echo -n "$ZONERETVAL" | tr "\-" "\+"`"
#else
# ZONERETVAL="`echo -n "$ZONERETVAL" | tr "\+" "\-"`"
#fi

#validity check...
[ "`echo "$ZONEINFO" | grep "$ZONERETVAL"`" = "" ] && exit

[ "`echo "$ZONERETVAL" | grep 'GMT'`" != "" ] && ZONERETVAL="Etc/$ZONERETVAL"

rm -f /etc/localtime
ln -s /usr/share/zoneinfo/$ZONERETVAL /etc/localtime

rm -f /etc/TZ #don't think need this anymore. also removed from /etc/profile.
#.../etc/profile now reads /etc/localtime and exports TZ variable.

#need to set Linux system time/date, from hardware clock...
#hwclock --hctosys --localtime
hwclock --hctosys --${HWCLOCKTIME} #100525
#...--hctosys reads cmos clock to system, referencing /usr/share/zoneinfo/localtime
#...--localtime means that cmos clock is set to local-time.

###END###
