#!/bin/sh
#BK called from udev rule in /etc/udev/rules.d/52-usb_modem_puppy.rules
#some variables:
#ACTION=add
#DEVLINKS=/dev/gsmmodem
#DEVNAME=/dev/ttyUSB0
#DEVPATH=/devices/pci0000:00/0000:00:1d.7/usb1/1-2/1-2:1.0/ttyUSB0/tty/ttyUSB0
#MAJOR=188
#MINOR=0
#SEQNUM=3815
#SUBSYSTEM=tty


if [ "$DEVLINKS" = "/dev/gsmmodem" ];then
#if [ -e /dev/gsmmodem ];then
 killall yaf-splash
 DISPLAY=":0" yaf-splash -placement center -close never -bg green -fontsize large -timeout 5 -text "USB Modem ready for use" &
else
 if pidof yaf-splash ;then exit ;fi
 DISPLAY=":0" yaf-splash -placement center -close never -bg yellow -fontsize large -timeout 30 -text "USB Modem inserted, please wait, configuring..." &
fi

