#!/bin/sh
#(c) copyright Barry Kauler, May 2013, bkhome.org
#License GPL3 (refer /usr/share/doc/legal).
# Called from /usr/sbin/loginmanager, to change back to 'root'.
# May also be called standalone.
#130527 first version.

NOWUSER="`whoami`"
[ "$NOWUSER" != "root" ] && exec sudo -A ${0} ${@}

export TEXTDOMAIN=user2root
export OUTPUT_CHARSET=UTF-8

  _TITLE_=user_to_root
_VERSION_=1.0omega
_COMMENT_="Alter files to default to USER 'root'"

MY_SELF="$0"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="/usr/sbin/loginmanager helper script
to change back to 'root' .
may also be called standalone.
Needs reboot.
Alters /etc/inittab [and /etc/minit/* fido to root]."
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap
}

#change auto login back to root...
rootEXPR="s%^tty1.*%tty1::respawn:/sbin/mingetty --autologin root tty1%"
STATUS=0
sed -i -e "$rootEXPR" /etc/inittab #110507 TaZOC bug fix.
STATUS=$((STATUS+$?))
#120409 if using minit instead of busybox init...
if [ -f /etc/minit/getty/1/params  ];then #see my minit pet pkg.
 EXPR2='s%^fido$%root%'
 sed -i -e "$EXPR2" /etc/minit/getty/1/params
 STATUS=$((STATUS+$?))
fi
#pupmessage -bg green -center -title "$(gettext 'Login Manager: OK')" "$(gettext 'Ok, you will be administrator at next boot')"
test "$STATUS" = 0 && xmessage -bg green -center -title "$(gettext 'Login Manager: OK')" "$(gettext 'Ok, you will be administrator at next boot')"
###END###
