#!/bin/sh
#(c) Copyright Barry Kauler 2006,2007 www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
## Abused by Dougal, Feb 2007
## Update: March 16th: fixed "OK" button when testing X
## Update: April 15th: fixed problem with MONTYPES format, added touchpad code
## Update: April 16th: removed MONTYPES, using a case-structure to set params
#v2.21 BK 9sept2007 bug fix: serial mouse setting was wrong.
#v3.93 BK 1dec2007: updated for dingo.
#v3.93 BK 2dec2007: bugfixes from Dougal and rerwin.
#v3.94 BK 24dec2007: recognise Classmate PC laptop.
#v3.95 BK 4jan2008: recognise eeepc laptop.
#v3.95 BK 8jan2008: bug that caused xorgwizard to run at every boot.
#v3.96 BK 22jan2008: special case submitted by rerwin.
#v3.97 BK 2feb2008: improved detection of Classmate laptop.
#v3.98 RE 7mar2008: added preferred mode parameter; corrected & added special cases submitted by rerwin.
#v3.99 BK 15apr2008: have restored the xrandrshell utility to the main GUI menu.
#v3.99 BK 15apr2008: workaround for xrandr and dual monitors.
#v3.99 RE 7apr2008: improve user interface for any Xvesa-hanging video adapters.
#v405 BK 22jul08: added support for 1024x600.
#v408 BK k2.6.25.16 serial mouse driver now a module 'sermouse'.
#v411 rerwin: mouse improvements.
#v411 moved choosemousefunc() to /etc/rc.d/functions4puppy4, want call from rc.sysinit.
#w000 path /usr/X11R7 no longer used.
#w002 no longer offering xvesa.
#w005 restored EXIT button in first dlg.
#w007 fix X if it is not a symlink.
#w019 april2009: restored Xvesa.
#w460 fixed X test screen, proper exit.
#w468 modify mouse detection message.
#w478 fix prevent 2 instances of xwin, do not 'exec xwin'.
#w480 bugfix, serial mouse choice lost if choose to tweak refresh.
#w482 allow switch between intel_drv.so and i810OLD_drv.so.


###KRG Fr 31. Aug 23:34:58 GMT+1 2012

trap "exit 1" HUP INT QUIT KILL TERM

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }
[ "$DEBUG" = "2" ] && set -x

Version='1.1'

usage(){
USAGE_MSG="
$0 [ PARAMETERS ]

-V|--version : showing version information
-H|--help : show this usage information

*******  *******  *******  *******  *******  *******  *******  *******  *******
$2
"
echo "$USAGE_MSG"
exit $1
}

[ "`echo "$1" | grep -wiE "help|\-H"`" ] && usage 0
[ "`echo "$1" | grep -wiE "version|\-V"`" ] && { echo "$0 -version $Version";exit 0; }

###KRG Fr 31. Aug 23:34:58 GMT+1 2012

########################################################################
#
#
#
#
#
# /dev/sda5:
# LABEL="MacPup430_F3"
# UUID="07443de5-1fab-4656-a3ab-7b1c14ccc8c8"
# TYPE="ext3"
# DISTRO_VERSION=430·#481·#416·#218·#478······#####change·this·as·required#####
# DISTRO_BINARY_COMPAT="puppy"·#"ubuntu"·#"puppy"·#####change·this·as·required#####
# case·$DISTRO_BINARY_COMPAT·in
# puppy)·#built·entirely·from·Puppy·v2.x·or·v3.x·or·4.x·pet·pkgs.
# DISTRO_NAME="Puppy"
# DISTRO_FILE_PREFIX="pup"·#"ppa"·#"ppa4"·#"pup2"··#pup4··###CHANGE·AS·REQUIRED,·recommend·limit·four·characters###
# DISTRO_COMPAT_VERSION="4"·#"2"··#4·····###CHANGE·AS·REQUIRED,·recommend·single·digit·5,·4,·3,·or·2###
# ;;
# esac
# PUPMODE=2
# KERNVER=2.6.34.7-i486
# SATADRIVES='·sda'
# USB_SATAD='·sdb'
# PUP_HOME='/'
# Linux·puppypc·2.6.34.7-i486·#1·SMP·Mon·Dec·20·16:26:36·GMT-8·2010·i686·GNU/Linux
# Xserver=/usr/X11R7/bin/Xorg
# $LANG=en_US
# today=Thu·Oct·27·17:06:25·CEST·2011
# TODO1 : add iconwipe
# TODO2 : add 2>/dev/null to ls -l
#
#
#
########################################################################

OUT=/dev/null;ERR=$OUT
[ "$DEBUG" ] && { OUT=/dev/stdout;ERR=/dev/stderr; }

tmpDir='/tmp/xorgwizard';mkdir -p "$tmpDir"
echo "
`date`" >>"$tmpDir"/xorgwizard.messages

[ "`tty`" = "not a tty" -o "`tty`" = '?' ] && { sleep 2s;chvt 1; }

##+++2012-01-30
if [ "`whoami`" = 'root' ];then
XORGCONFFILE=/etc/X11/xorg.conf
else
XORGCONFFILE=xorg.conf
fi
##+++2012-01-30

alias modprobe='modprobe -b' #+++2012-02-03

# redirect errors to file (to help debug):
#exec 2>"$tmpDir"/xorgwizard-errors.log

PSFND=`ps`
CURRENTX=`readlink /usr/bin/X`
if [ "$CURRENTX" = "" ];then #w007 fix if not a symlink.
 ln -snf Xorg /usr/bin/X
 CURRENTX='Xorg'
fi

. /etc/rc.d/functions4puppy4 #v411 has choosemousefunc().

MAIN1="
<wtitle>Xorg Video Wizard</wtitle>
<hbox>
 <vbox>
  <text><label>\"Welcome to the Puppy Linux
Xorg Video Wizard!\"</label></text>
  <text><label>\"The behaviour of Xorg is controlled
by a configuration file, /etc/X11/
xorg.conf. You have a choice here,
either to completely reconstruct
the /etc/X11/xorg.conf file, or
to modify the existing file.\"</label></text>
 </vbox>
 <vbox>
  <frame XorgWizard>
  <hbox>
   <text><label>XorgWizard completely reconstructs the /etc/X11/xorg.conf file, and X must not be running to do this. A reboot is required, and the Wizard will run in text mode, before X is launched.</label></text>
   <vbox>
    <button>
     <input file>/usr/local/lib/X11/mini-icons/wizard16.xpm</input>
     <action>EXIT:11</action>
    </button>
   </vbox>
  </hbox>
  <text><label>NOTE: You can also run XorgWizard manually, without rebooting, by exiting from X to the commandline (see Shutdown menu) then run xorgwizard.</label></text>
  </frame>

  <frame Edit xorg.conf>
   <hbox>
    <text><label>You can manually edit /etc/X11/xorg.conf, but note that you will need to exit from X afterward then restart X (see Shutdown menu). Click button to edit:</label></text>
    <vbox>
     <button>
      <input file>/usr/local/lib/X11/mini-icons/mini-x.xpm</input>
      <action>EXIT:15</action>
     </button>
    </vbox>
   </hbox>
  </frame>

  <frame xvidtune>
   <hbox>
    <text><label>If the screen is displaced or the width/height are wrong, xvidtune can get it right. This will modify the existing xorg.conf file. Use with caution:</label></text>
    <vbox>
     <button>
      <input file>/usr/local/lib/X11/mini-icons/mini-x.xpm</input>
      <action>EXIT:13</action>
     </button>
    </vbox>
   </hbox>
  </frame>

  <frame Mouse/keyboard Wizard>
   <hbox>
    <text><label>/etc/X11/xorg.conf has generic settings for mouse and keyboard and in most cases it is recommended to leave it as-is. Instead, use the MouseKeyboardWizard:</label></text>
    <vbox>
     <button>
      <input file>/usr/local/lib/X11/mini-icons/wizard16.xpm</input>
      <action>EXIT:16</action>
     </button>
    </vbox>
   </hbox>
  </frame>

  <frame Monitor gamma calibration>
   <hbox>
    <text><label>This will adjust the monitor colors, including brightness. Note, cannot save settings -- a project here for someone -- see /usr/share/doc/tkgamma.txt</label></text>
    <vbox>
     <button>
      <input file>/usr/local/lib/X11/mini-icons/mini-x.xpm</input>
      <action>EXIT:17</action>
     </button>
    </vbox>
   </hbox>
  </frame>

  <frame Resolution changer>
   <hbox>
    <text><label>It is possible to change screen resolutions without exiting from X:</label></text>
    <vbox>
     <button>
      <input file>/usr/local/lib/X11/mini-icons/mini-x.xpm</input>
      <action>EXIT:18</action>
     </button>
    </vbox>
   </hbox>
  </frame>

 </vbox>
</hbox>
"


#do this code block if X is running...
if [ ! "`echo -n "$PSFND" | grep "\\.xinitrc"`" = "" ];then

 RETSTR=`echo "$MAIN1" | gtkdialog2 --stdin`
 RETVAL=`echo "$RETSTR" | grep 'EXIT:' | cut -f 2 -d ':'`

 case $RETVAL in
  11) #XorgWizard.
   #rm /etc/mousedevice # Dougal: any reason for this?
   mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.prev 2>$ERR
   [ -e /usr/bin/Xvesa ] && ln -sf Xvesa /usr/bin/X
   NEXTWM=`cat /etc/windowmanager`
   echo -n "$NEXTWM" > /etc/windowmanager #this makes change permanent.
   echo -n "$NEXTWM" > /tmp/wmexitmode.txt
   echo -n "$NEXTWM" > /tmp/xwin/wmexitmode.txt
   echo 'ICONWIPE' > /tmp/pup_event_icon_change_flag  ##+++2011_10_30
   sync
   exec killall X
   ;;
  12) #xorgconfig
   xorgcfg
   xmessage -bg "#ff8080" -center -title "xorgcfg" "Changes to /etc/X11/xorg.conf will only take effect after X is restarted.

Click OK button to restart X..."
   exec restartwm
   ;;
  13) #xvidtune
   xmessage -bg violet -title "Xvidtune IMPORTANT HELP" "If you click the 'Show' button, the adjusted settings will be what
you want permanently. After hitting the 'Quit' button, you will be
given one last chance not to make the change permanent.
Thus:
'Show' to record the settings (for later inclusion into xorg.conf)
'Quit' to exit Xvidtune.

Please note that Xvidtune does not work with all video hardware, meaning
that changing the settings will cause no change on the screen." &
   XMSGPID=$!
   MODELINE0=`xvidtune | grep '^"[0-9]'`  ##"'geany
   kill $XMSGPID
   if [ ! "$MODELINE0" = "" ];then
    xmessage -bg orange -title "Xvidtune: Modeline" -buttons Write:10,Quit:11 "The new modeline is:
$MODELINE0

Note, you will have to restart X for it to take effect. If it messes
up X, edit from commandline 'mp /etc/X11/xorg.conf' and comment-out
the 'UseModes' line (do not delete it) in the Monitor section.

To insert this into /etc/X11/xorg.conf, click 'Write' button...
To exit without changing xorg.conf, click 'Quit' button..."
    if [ $? -eq 10 ];then
     PATTERNA="s/.*#modes0modeline0/ ModeLine $MODELINE0 #modes0modeline0/g"
     cat /etc/X11/xorg.conf | sed -e "$PATTERNA" > "$tmpDir"/xorg.conf.new
     sync
     echo "sed #.*UseModes/UseModes to /etc/X11/xorg.conf 1" >> "$tmpDir"/xorgwizard.messages && sleep 2s #9s
     cat "$tmpDir"/xorg.conf.new | sed -e 's/#.*UseModes/UseModes/g' > /etc/X11/xorg.conf
     sync
    fi
   fi
   exit
   ;;
  15) #edit xorg.conf
   exec defaulttexteditor /etc/X11/xorg.conf
   ;;
  16) #mouse/keyboard wizard
   exec input-wizard
   ;;
  17) #tkgamma
   exec tkgamma
   ;;
  18) #resolution changer
   exec xrandrshell
   ;;
 esac
 exit
fi
