#!/bin/sh

_restore_xorgwizard_files(){
cat "$0" >/tmp/xorg-setup.sh
mv $VERB /usr/sbin/xorg-setup /usr/sbin/xorgwizard
if test "$DEBUG"; then
cp $VERB -a /tmp/xorg-setup.sh /usr/sbin/xorg-setup
else
mv $VERB /tmp/xorg-setup.sh /usr/sbin/xorg-setup
fi
exit $?
}

. /etc/rc.d/PUPSTATE
test "$PUPMODE" = 5 || _restore_xorgwizard_files

cp $VERB -f /etc/X11/xorg.conf0 /etc/X11/xorg.conf
echo '' >> /etc/X11/xorg.conf

ddcprobe >/tmp/ddcprobe.txt
#weird (ddcprobe is very weird), on some hardware, edid monitor probe fails
#every alternate run of ddcprobe...
case "`cat /tmp/ddcprobe.txt`" in *edidfail*)
 sleep 1
 ddcprobe >/tmp/ddcprobe.txt
 ;;
esac

PROFILECHIP=`grep -m1 '^oem: ' /tmp/ddcprobe.txt | cut -f 2-4 -d ' ' | tr ' ' '_' | sed -e 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
PROFILEMONITOR=`grep '^monitorid: ' /tmp/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorname: '  /tmp/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^monitorrange: ' /tmp/ddcprobe.txt | head -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`
[ "$PROFILEMONITOR" ] || PROFILEMONITOR=`grep '^manufacture: '  /tmp/ddcprobe.txt | tail -n 1 | cut -f 2 -d ':' | tr -d ' ' | sed -e 's/[^0-9a-zA-Z]/_/g' | tr -s '_'`

echo "#PuppyHardwareProfile=${PROFILECHIP}${PROFILEMONITOR}" >> /etc/X11/xorg.conf
#create a copy of xorg.conf with the profile in the filename...
cp $VERB -af /etc/X11/xorg.conf /etc/X11/xorg.conf.${PROFILECHIP}${PROFILEMONITOR}

mv $VERB /usr/lib/xorg/modules/drivers/displaylink_drv.so /usr/lib/xorg/modules/drivers/displaylink_drv.so.not
_restore_xorgwizard_files
