#!/bin/ash
#usb/serial modem
#Barry Kauler, LGPL 2007

case $1 in
start)
#v405 if a different modem selected, quit...
#[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "usb/ttyUSB0" ] && exit
[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "ttyUSB0" ] && exit

#[ ! $1 ] && exit
#[ "$1" != "start" ] && exit

if [ "`lsmod | grep '^pl2303'`" != "" ];then
 #ln -snf usb/ttyUSB0 /dev/modem
 ln $VERB -snf ttyUSB0 /dev/modem
fi
;;
*):;;
esac
###END###
