#!/bin/sh

$APPDIR/func -update_playlist
. $APPDIR/gui_misc
. $APPDIR/gui_menu
. $APPDIR/gui_playlist
. $APPDIR/gui_navigation

[ "$FIRST_RUN" = "true" ] && FIRST_RUN_INFO="<vbox><frame>
 <hbox homogeneous=\"true\"><hbox>
 <pixmap icon_size=\"5\"><input file stock=\"gtk-info\"></input></pixmap>
 <text><label>$LOC523</label></text>
 </hbox></hbox></frame></vbox>"

[ "$FIRST_RUN2" = "true" ] && FIRST_RUN_INFO="<frame>
 <hbox>
 <pixmap icon_size=\"6\"><input file stock=\"gtk-info\"></input></pixmap>
 <text use-markup=\"true\"><label>\"<span color='"'red'"'>$LOC523</span>\"</label></text>
 </hbox></frame>"

GUI="
<window title=\"Pmusic\" icon-name=\"gtk-media-stop\" default_height=\"$HEIGHT\" default_width=\"$WIDTH\">
 <vbox>
  <menubar>
   $GUI_MENU_FILE
   $GUI_MENU_PLAYLIST
   $GUI_MENU_TOOLS
   $GUI_MENU_WINDOW
   $GUI_MENU_HELP
  </menubar>
  $GUI_NAVIGATION
  $GUI_PROGRESSBAR
  $GUI_PLAYLIST_FIELD
  <hbox>
   $GUI_CHECKBOX_LOOP
   $GUI_CHECKBOX_SHUFFLE
   <text><label>\"   \"</label></text>
   $GUI_BUTTON_CLEAR_PLAYLIST
   $GUI_BUTTON_PLAYLIST_HISTORY_BACK
   $GUI_BUTTON_PLAYLIST_HISTORY_FORWARD
   $GUI_BUTTON_ADD
  </hbox>
  $FIRST_RUN_INFO
 </vbox>
 <action signal=\"hide\">$APPDIR/func -write_config</action>
 <action signal=\"hide\">exit:Exit</action>
</window>"

########################   Add dialog   ##############################

INDEX_HEIGHT=100
. $APPDIR/gui_add

export Pmusic_sources="
<window title=\"Pmusic - Music-sources\" icon-name=\"gtk-media-stop\" default_height=\"400\">
 <vbox>
<hbox homogeneous=\"true\">
<hbox>
 <button>
  <label>$LOC223</label>
  <action>. $APPDIR/func -index_songs</action>
 </button>
 <button>
  <label>$LOC224</label>
  <action>. $APPDIR/func -index_playlists</action>
 </button>
 <button>
  <label>$LOC222</label>
  <action>. $APPDIR/func -radio</action>
 </button>
 <button>
  <label>CD</label>
  <action>. $APPDIR/func -read_cd &</action>
 </button>
 <button>
  <label>$LOC227</label>
  <action>. $APPDIR/func -show_bookmarks</action>
 </button>
 <button>
  <label>$LOC225</label>
  <action>. $APPDIR/func -index_recent</action>
 </button>
 <button>
  <label>$LOC226</label>
  <action>. $APPDIR/func -index_most_played</action>
 </button>
</hbox>
</hbox>

  $GUI_ADD_SEARCH
  $GUI_ADD_FIELD
  <hbox>
   $GUI_ADD_RADIOBUTTON_END
   $GUI_ADD_RADIOBUTTON_AFTER_SELECTION
   $GUI_ADD_BUTTON_ADD_RANDOM
   $GUI_ADD_BUTTON_ADD_ALL
  </hbox>
   $GUI_ADD_PROGRESS
 </vbox>
 <action signal=\"hide\">echo end > $WORKDIR/end_while_add</action>
</window>"

########################   playlist multiple   ##############################

. $APPDIR/gui_playlist_multiple

export Pmusic_playlist_multiple="
<window title=\"Pmusic - $LOC120\" icon-name=\"gtk-media-stop\">
 <vbox>
  $GUI_PLAYLIST_MULTIPLE
 </vbox>
</window>"

