#!/bin/bash

####$APPDIR/func -update_playlist & #playlist is refreshed later, so it should be safe to run in background
. $APPDIR/gui_misc
. $APPDIR/gui_menu
. $APPDIR/gui_toolbar
. $APPDIR/gui_playlist
. $APPDIR/gui_navigation
. $APPDIR/gui_add
. $APPDIR/gui_mixer
$APPDIR/func -update_index_check

GUI="
<window title=\"Pmusic\" icon-name=\"gtk-media-stop\" default_height=\"$HEIGHT\" default_width=\"$WIDTH\">
 <hbox>
 $GUI_ADD_FIELD
 <vbox width-request=\"370\">
 <vbox>
  $GUI_MENU
  $GUI_ADD_SEARCH
 </vbox>
 <vbox scrollable=\"true\">
  <text height-request=\"5\"><label>\"\"</label></text>
  <hbox homogeneous=\"true\"><hbox spacing=\"2\">
   $GUI_BUTTON_OVERVIEW
   $GUI_BUTTON_CD
   $GUI_BUTTON_SONG_INFO
   <text width-request=\"5\"><label>\"\"</label></text>
   $GUI_BUTTON_PLAYLIST_HISTORY_BACK
   $GUI_BUTTON_NEW
   $GUI_BUTTON_PLAYLIST_HISTORY_FORWARD
   $GUI_NAVIGATION
   $GUI_BUTTON_PLAYMODE
   $GUI_BUTTON_ADDMODE
  </hbox></hbox>
  $GUI_PROGRESSBAR
  $GUI_PROGRESS
  
  ##mixer
  <hbox homogeneous=\"true\">
   <hbox>
    <vbox width-request=\"130\">
     $GUI_BALANCE
    </vbox>
    $GUI_BALANCE_IMG
   </hbox>
   <hbox>
    $GUI_VOLUME_IMG
    <vbox width-request=\"130\">
     $GUI_VOLUME
    </vbox>
   </hbox>
  </hbox>"
  [ "`type pequalizer 2> /dev/null`" ] && GUI="$GUI<hbox homogeneous=\"true\">$GUI_PEQUALIZER</hbox>"
  GUI="$GUI<hbox homogeneous=\"true\">
   <hbox>
    <pixmap>
     <variable>ARTWORK</variable>
     <input file>$HOME/.pmusic/nowplaying_albumart.jpg</input>
     <width>340</width>
    </pixmap>
   </hbox>
  </hbox>
  $GUI_ADD_PROGRESS
 </vbox>
 $GUI_STATUSBAR
 </vbox>
 $GUI_PLAYLIST_FIELD
 </hbox>
 <action signal=\"hide\">$APPDIR/func_config -write_config</action>
 <action signal=\"hide\">exit:Exit</action>
</window>"
