#!/bin/sh

export WIN_DLG="<window title=\"SNS: Help on security\" icon-name=\"gtk-network\">
<vbox>
<text use-markup=\"true\"><label>\"<b>No security</b>
The wireless network is not encrypted, so anybody can access it. Some wireless routers are setup for MAC Address filtering, restricting which clients can access, so this is a form of security for an un-encrypted network.
There is no need to type any 'Key' as it is not used.\"</label></text>
<text use-markup=\"true\"><label>\"<b>WEP</b>
This is an 'older' method of encryption that is less secure than WPA. Basically, it is a case of 'the weakest link in the chain' -- if any client on the network supports only WEP then all clients must use WEP (and the wireless router must be set to WEP).
The 'Key' must be a hexadecimal number (composed of the digits 0-9 and a-f) and either 13 or 26 digits long.\"</label></text>
<text use-markup=\"true\"><label>\"<b>WPA</b>
This is more secure than WEP and is the recommended choice if your router and Linux driver supports it. There are ctually two types WPA and WPA2, but ticking the 'WPA' radiobutton will use whichever of these is available. Also, there are two encryption management schemes, known as 'TKIP' and 'AES' -- again, whichever is available will be automatically used.
The 'Key' (sometimes known as the 'passphrase' or 'password') can be composed of any numerical or alphanumeric characters, from 8 to 63 characters long (even spaces are allowed)\"</label></text>
<text><label>\"  \"</label></text>
</vbox>
</window>"

gtkdialog3 --program=WIN_DLG

###END###
