#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_chooser"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pburn-3.1.2/box_chooser"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
export chooser="
<window title=\"Pburn - $TITLE\" icon-name=\"gtk-cdrom\">
 <vbox>
  <chooser>
   <height>500</height><width>600</width>
   <variable>CHOOSER</variable>
  </chooser>
  <hbox>
   <button>
    <input file icon=\"gtk-cancel\"></input>
    <label>$LOC_CANCEL</label>
    <action>EXIT:cancel</action>
   </button>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
    <action>EXIT:OK</action>
   </button>
  </hbox>
 </vbox>
</window>"
I=$IFS; IFS=""
for STATEMENTS in  $($GTKDIALOG -p chooser --center); do
	eval $STATEMENTS
done
IFS=$I
if [ $EXIT = "OK" ]; then
	#check if hit is directory
	if [ "$GET_OUTDIR" = "true" ]; then
		if [ ! -d "$CHOOSER" ]; then 
			TXT1="$LOC317"
			. $APPDIR/box -ok
			exit
		fi
		echo "$CHOOSER" > $WORKDIR/OUTDIR
	fi
	if [ "$SLIDESHOW" = "true" ]; then
		echo "$CHOOSER" > $WORKDIR/BACKGROUND_MUSIC
	fi
fi
	# Very End of this file 'usr/local/pburn-3.1.2/box_chooser' #
###END###
