#!/bin/bash
AUDIO_FORMATS="`echo $AUDIO_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
VIDEO_FORMATS="`echo $VIDEO_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
IMAGE_FORMATS="`echo $IMAGE_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
echo "\

Usage: pburn [OPTION] [FILE]
[FILE] is a *.pbn or *.iso - if not, use the -i parameter

Options
  -c          Do NOT autodetect media. 
              Multisession settings will not be complete by default.
  -d [DIR]    Use [DIR] as default browser directory
  -f          Use raw-burn-mode.
              Burn content of $HOME/.pburn/pburn_symlink_tree,
              and always follow symlinks
  -g [ENGINE] Define what burn-engine to use. [ENGINE] can be:
                cdrtools
                cdrkit
              Pburn uses cdrtools if both is present.
  -h          Show this help message
  -i [FILE]   Import textfile with list of files
  -m [MODE]   Skip main gui. Go straight to [MODE]:
                data
                audio
                video
                iso
                blank
                copy-data
                copy-audio
                copy-video
  -r          Reset all settings/ Reinstall helpfile
  -v          Show Pburn version

Supported formats (with working ffmpeg):
Audio: $AUDIO_FORMATS
Video: $VIDEO_FORMATS
Image: $IMAGE_FORMATS"