#!/bin/ash

case $1 in
 start)
  #syslogd -m 0
  #klogd
  if [ -n "`pidof syslogd`" ] ; then
  echo "syslogd already running"
  else
  syslogd -m 0
  fi
  if [ -n "`pidof klogd`" ] ; then
  echo "klogd already running"
  else
  klogd
  fi
 ;;
 stop)
  if [ -n "`pidof klogd`" ] ; then
  echo "Stopping klogd"
  killall klogd
  fi
  if [ -n "`pidof syslogd`" ] ; then
  echo "Stopping syslogd"
  [ "`pidof acpid`" ] && killall acpid
  [ "`pidof udevd`" ] && killall udevd
  killall syslogd
  fi
 ;;
esac
