#!/bin/sh

PARAM="$1"
[ ! "$PARAM" ] && PARAM='none'
case $PARAM in
start)
smsd
;;
stop)
pids=`ps -C smsd |awk '{print $1}' | sed '1 d'`
for pid in $pids ; do
echo $pid
for i in `seq 1 1 64` ; do
[ ! "`ps -p $pid | sed '1 d'`" ] && echo && break
echo -n "$i."
kill -$i $pid
sleep 0.5s
done
done

;;
check)
ps -elF | grep smsd | grep -v grep
;;
*)
echo "'$PARAM' invalid . Valid parameters start|stop|check"
exit 1
;;
esac
exit 0
