#!/bin/sh

# Nethack save-file recovery script for Debian
#
# Ben Gertzfield (che@debian.org) 29 July 1997
# Copyright 1997 Ben Gertzfield. This script is released under the
# GNU General Public License, version 2 or later.

PATH=/bin:/usr/bin:/sbin:/usr/sbin

set -e

case "$1" in
  start)
    # Has the nethack package been removed?
    test -x /usr/lib/games/nethack/recover || exit 0

    # Are there any lock-files to recover?
    ls /var/lib/games/nethack/*.0 >/dev/null 2>&1 || exit 0

    # Yes; recover them.
    for file in /var/lib/games/nethack/*.0; do
	owner=$(ls -l $file | awk '{print $3}')
	echo "Recovering Nethack save file owned by $owner..."
	su --shell=/bin/sh --command="/usr/lib/games/nethack/recover $file" $owner 
	if (($?)); then
	    echo "error $?\!"
	else
	    echo "recovered."
	fi
    done
esac
