#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          gsm0710muxd
# Required-Start:    dbus
# Required-Stop:     dbus
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Muxer for gsm modems 
# Description:       Provides muxing functionality as described in gsm07.10
### END INIT INFO
NAME=gsm0710muxd
DEBUG=""
case "$1" in
	run)
		echo "Running $NAME: "
		/usr/sbin/$NAME \
			-x /sys/bus/platform/devices/neo1973-pm-gsm.0 \
			-a 2 \
			-f 100 \
			-s /dev/ttySAC0 \
			$DEBUG
	;;
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon --start --pidfile /var/run/${NAME}.pid \
		--make-pidfile --background --startas /usr/sbin/$NAME -- \
			-x /sys/bus/platform/devices/neo1973-pm-gsm.0 \
			-a 2 \
			-f 100 \
			-s /dev/ttySAC0 \
			$DEBUG
		echo "started process with pid `cat /var/run/${NAME}.pid`"
	;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon --stop --pidfile /var/run/${NAME}.pid \
		--oknodo
		rm -f /var/run/${NAME}.pid
		echo $NAME.
	;;
	force-reload|restart)
		$0 stop
		sleep 1
		exec $0 start
	;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
	;;
esac
exit 0
