#!/bin/sh
#Barry Kauler 2009. totally free code.

#if a modem found, quit...
[ -h /dev/modem ] && exit
[ ! $1 ] && exit
[ "$1" != "start" ] && exit

#Wait for firmware and driver to load.
/sbin/pup_event_backend_modprobe_protect --modcheck=hcfpcihw || exit #v432

 #v432 Don't select if HSF driver also loaded, to avoid hanging pupdial when connecting.
[ "`lsmod | grep '^hsfosspec '`" = "" ] \
 && ln -snf ttySHCF0 /dev/modem


###END###
