#!/bin/sh
which sfs_load &>/dev/null || exit
[ "$1" = "stop" ] && exec sfs_load --cli stop
[ "$1" = "start" ] || exit
[ -f /etc/rc.d/BOOTCONFIG ] || exit
. /etc/rc.d/BOOTCONFIG
[ "$EXTRASFSLIST" ] || exit
exec sfs_load --cli start
