#!/bin/ash

. /etc/rc.d/f4puppy5

FILE=/root/TUBE/FlashC0mPIo.flv   #Jonny Cash Hurt
FILE=/root/Videos/FlashTI3Ba1.flv #Rihanna
MEDIA_PLAYER=/usr/local/bin/mplayer

if test -f "$FILE"; then
 test "$DEBUG" -o "$VERBOSE" && amixer sget Master,0
 amixer $Q set Master,0 on
 amixer $Q set Master,0 100

 test "$DEBUG" -o "$VERBOSE" && amixer sget Mono,0
 amixer $Q set Mono,0 100

 test "$DEBUG" -o "$VERBOSE" && amixer sget PCM,0
 amixer $Q set PCM,0 100

 test "$DEBUG" -o "$VERBOSE" && amixer sget Speaker,0
 amixer $Q set Speaker,0 100

 test "$Q" && QUIET_OPT=-really-quiet
 $MEDIA_PLAYER $QUIET_OPT -loop 0 "$FILE"
fi
