#!/bin/bash
TMP_DIR=/tmp/Pprocess;mkdir -p $TMP_DIR
case $1 in
-logfile)
	if [ "$LOG_FILE" = top ]; then
		rxvt -name pburn -bg black -fg green -geometry 80x20 -title "Pprocess - Running processes" -e top
	fi
	Xdialog --title "Pprocess" --screen-center --fixed-font --no-ok --cancel-label "$LOC_CANCEL" --tailbox $LOG_FILE 500x500
	;;
-probe)
	CURRENTPS=`ps`
	if [ "`cat $TMP_DIR/pprocess-viewall`" = "false" ]; then
		echo "$CURRENTPS" | grep -v "\[*\]" | grep -v "VmSize" | grep -v " init " | tr -s ' ' | sed 's|^ *||;s, ,|,g' > $TMP_DIR/pprocess-ps
		echo "true" > $TMP_DIR/pprocess-viewall
	else
		echo "$CURRENTPS" | grep -v "VmSize" | grep -v " init " | tr -s ' ' | sed 's|^ *||;s, ,|,g' > $TMP_DIR/pprocess-ps
		echo "false" > $TMP_DIR/pprocess-viewall
	fi
	;;
-kill)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	TMP="-`echo "$KILL_SIGNAL" | cut -d " " -f 1`"
	if [  $TMP = "-0" ]; then TMP=""; fi
	kill $TMP `echo "$LIST" | awk '{print $1}'`
	;;
-high)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice -10 `echo "$LIST" | awk '{print $1}'`;;
-normal)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice 0 `echo "$LIST" | awk '{print $1}'`;;
-low)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice 10 `echo "$LIST" | awk '{print $1}'`;;
-refresh)
	#reset viewall
	if [ `cat $TMP_DIR/pprocess-viewall` = "true" ]; then
		echo "false" > $TMP_DIR/pprocess-viewall
	else
		echo "true" > $TMP_DIR/pprocess-viewall
	fi;;
-search)
	CURRENTPS=`ps`
	echo "$CURRENTPS" | grep $SEARCHSTRING > $TMP_DIR/pprocess-ps
	;;
esac
