#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pprocess/func"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
case $1 in
-logfile)
	if [ $LOG_FILE = top ]; then
		rxvt -name pburn -bg black -fg green -geometry 80x20 -title "Pprocess - Running processes" -e top
	fi
	Xdialog --title "Pprocess" --screen-center --fixed-font --no-ok --cancel-label "$LOC_CANCEL" --tailbox $LOG_FILE 500x500
	;;
-probe)
	CURRENTPS=`ps`
	if [ "`cat /tmp/pprocess-viewall`" = "false" ]; then
		echo "$CURRENTPS" | grep -v "\[*\]" | grep -v "VmSize" | grep -v " init " | sed -e 's/root............/\t/g' > /tmp/pprocess-ps
		echo "true" > /tmp/pprocess-viewall
	else
		echo "$CURRENTPS" | grep -v "VmSize" | grep -v " init " > /tmp/pprocess-ps
		echo "false" > /tmp/pprocess-viewall
	fi
	;;
-kill)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	TMP="-`echo "$KILL_SIGNAL" | cut -d " " -f 1`"
	if [  $TMP = "-0" ]; then TMP=""; fi
	kill $TMP `echo "$LIST" | awk '{print $1}'`
	;;
-high)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice -10 `echo "$LIST" | awk '{print $1}'`;;
-normal)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice 0 `echo "$LIST" | awk '{print $1}'`;;
-low)
	if [ ! "$LIST" ]; then
		TXT1="$LOC130"
		. "$PROGPATH"/box_ok
	fi
	renice 10 `echo "$LIST" | awk '{print $1}'`;;
-refresh)
	#reset viewall
	if [ `cat /tmp/pprocess-viewall` = "true" ]; then 
		echo "false" > /tmp/pprocess-viewall
	else
		echo "true" > /tmp/pprocess-viewall
	fi;;
-search)
	CURRENTPS=`ps`
	echo "$CURRENTPS" | grep $SEARCHSTRING > /tmp/pprocess-ps
	;;
esac
