#!/bin/bash
case $1 in
-action)
	if [ "$KILL" = "false" ] && [ "$CPU" = "false" ]; then
		TXT1="$LOC131"
		. "$PROGPATH"/box_ok
	fi
	if [ "$KILL" = "true" ]; then
		TMP="-`echo "$KILL_SIGNAL" | cut -d " " -f 1`"
		if [  $TMP = "-0" ]; then TMP=""; fi
		kill $TMP `echo "$LIST" | awk '{print $1}'`
	fi
	if [ "$CPU" = "true" ]; then
		case $CPU_PRIORITY in
			$LOC105) renice -10 `echo "$LIST" | awk '{print $1}'`;; #high
			$LOC106) renice 0 `echo "$LIST" | awk '{print $1}'`;; #normal
			$LOC107) renice 10 `echo "$LIST" | awk '{print $1}'`;; #low
		esac
	fi
	;;
-set_filter)
	echo "$FILTER_STRING" > /tmp/pprocess-filter
	;;
-filter)
	ps > /tmp/pprocess-ps_source
	FILTER_STRING=($(<"/tmp/pprocess-filter"))
	grep -i "$FILTER_STRING" /tmp/pprocess-ps_source > /tmp/pprocess-ps
	;;
esac
