#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_pprocess"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pprocess/pprocess"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#Pprocess - process manager
#Copyright 2007,2008,2009
#Sigmund Berglund

#------------------------------
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2.

#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. <http://www.gnu.org/licenses/>.
#------------------------------

VERSION="1.0"
#define paths
PROGPATH="`dirname $0`" #Pprocess directory
[ "$PROGPATH" = "." ] && PROGPATH="`pwd`"
export PROGPATH=$PROGPATH

echo "false" > /tmp/pprocess-viewall
echo "false" > /tmp/pprocess-button
#set language
ENVIRONMENT_LANG=`echo $LANG | sed "s/\(..\).*/\1/"` #detect environment language 
case $ENVIRONMENT_LANG in
	da)	export LANGUAGE="danish" ;;
	de)	export LANGUAGE="german" ;;
	en)	export LANGUAGE="english" ;;
	es)	export LANGUAGE="spanish" ;;
	fi)	export LANGUAGE="finnish" ;;
	fr)	export LANGUAGE="french" ;;
	gr)	export LANGUAGE="greece" ;;
	it)	export LANGUAGE="italian" ;;
	ja)	export LANGUAGE="japanese" ;;
	nb)	export LANGUAGE="norwegian" ;; #translation is norwegian bokmål
	nl)	export LANGUAGE="dutch" ;;
	nn)	export LANGUAGE="norwegian" ;; #Use norwegian bokmål, since there is no norwegian nynorsk
	ru)	export LANGUAGE="russian" ;;
	sv)	export LANGUAGE="swedish" ;;
	*)	export LANGUAGE="english" ;; #english for contries without translation
esac
. $PROGPATH/locals/english #always run to fill gaps in translation
. $PROGPATH/locals/$LANGUAGE 2> /dev/null

. $PROGPATH/func -probe
export PPROCESS="
<window title=\"Pprocess $VERSION - $LOC100 \"icon-name=\"gtk-execute\">
<hbox>
 <tree headers_visible=\"false\" rules_hint=\"true\">
  <label>hei</label>
  <width>520</width><height>200</height>
  <variable>LIST</variable>
  <input>cat /tmp/pprocess-ps</input>
 </tree>
 <vbox>
  <text><label>\"\"</label></text>
  <hbox>
   <button> 
    <label>\"$LOC101\"</label>
    <action>. $PROGPATH/func -kill</action>
    <action>. $PROGPATH/func -refresh</action>
    <action>. $PROGPATH/func -probe</action>
    <action>Refresh:LIST</action>
   </button>
   <vbox>
    <text><label>\"       \"</label></text>
    <text><label>\"\"</label></text>
    <text><label>\"\"</label></text>
    <text><label>\"\"</label></text>
   </vbox>
  </hbox>
  <text><label>\"\"</label></text>
  <notebook labels=\"$LOC102|$LOC103\">
   <vbox>
    <frame $LOC104>
     <hbox>
      <text><label>$LOC105</label></text>
      <button>
       <input file stock=\"gtk-go-up\"></input>
       <action>. $PROGPATH/func -high</action>
       <action>. $PROGPATH/func -refresh</action>
       <action>. $PROGPATH/func -probe</action>
       <action>Refresh:LIST</action>
      </button>
     </hbox>
     <hbox>
      <text><label>$LOC106</label></text>
      <button>
       <input file stock=\"gtk-remove\"></input>
       <action>. $PROGPATH/func -normal</action>
       <action>. $PROGPATH/func -refresh</action>
       <action>. $PROGPATH/func -probe</action>
       <action>Refresh:LIST</action>
      </button>
     </hbox>
     <hbox>
      <text><label>$LOC107</label></text>
      <button>
       <input file stock=\"gtk-go-down\"></input>
       <action>. $PROGPATH/func -low</action>
       <action>. $PROGPATH/func -refresh</action>
       <action>. $PROGPATH/func -probe</action>
       <action>Refresh:LIST</action>
      </button>
     </hbox>
    </frame>
    <frame $LOC108>
     <hbox>
      <button>
       <input file stock=\"gtk-fullscreen\"></input>
       <label>$LOC109</label>
       <action>echo true > /tmp/pprocess-button</action>
       <action>. $PROGPATH/func -probe</action>
       <action>Refresh:LIST</action>
      </button>
     </hbox>
     <hbox>
      <entry activates-default=\"true\">
       <variable>SEARCHSTRING</variable>
       <input>echo $LOC110</input>
       <width>100</width><height>25</height>
      </entry>
      <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
       <input file stock=\"gtk-find\"></input>
       <action>. $PROGPATH/func -search</action>
       <action>. $PROGPATH/func -refresh</action>
       <action>Refresh:LIST</action>
      </button>
     </hbox>
    </frame>
   </vbox>
   <vbox>
    <frame $LOC111>
    <combobox>
     <variable>KILL_SIGNAL</variable>
     <item>9 - Kill</item> 
     <item>0 - No signal</item> 
     <item>1 - Hangup</item> 
     <item>2 - Interrupt</item> 
     <item>3 - Quit</item> 
     <item>9 - Kill</item> 
     <item>14 - Alarm</item> 
     <item>15 - Terminate (soft kill)</item> 
     <item>23 - Stop</item> 
     <item>25 - Continue</item> 
    </combobox>
   </frame>
   <frame $LOC117>
    <tree rules_hint=\"true\" headers_visible=\"false\" exported_column=\"1\">
     <variable>LOG_FILE</variable>
     <label>a|b</label>
     <item>$LOC112|top</item>
     <item>$LOC113|/var/log/messages</item>
     <item>$LOC114|/var/log/Xorg.0.log</item>
     <item>$LOC115|/tmp/bootkernel.log</item>
     <item>$LOC116|/tmp/bootsysinit.log</item>
     <action>. $PROGPATH/func -logfile</action>
    </tree>
    </frame>  
   </vbox>
  </notebook>
  <hbox>
   <button>
    <input file stock=\"gtk-refresh\"></input>
    <label>$LOC_REFRESH</label>
    <action>. $PROGPATH/func -refresh</action>
    <action>. $PROGPATH/func -probe</action>
    <action>Refresh:LIST</action>
   </button>
   <button>
    <input file stock=\"gtk-quit\"></input>
    <label>$LOC_QUIT</label>
   </button>
  </hbox>
 </vbox>
</hbox>
</window>"
I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog3 --program=PPROCESS --center); do
	eval $STATEMENTS
done
IFS=$I
case $EXIT in
	*)			exit;;
esac
