#!/bin/sh
# GPL v3 License
# PS VOIP for Puppy Linux v 0.7 June 27 008
# created by Lobster, CEL, HairyWill
# tested by Eric, Grant and the Puppy Community
###################

#add a new buddies
#todo
#check the input is at least close to matching a valid address
#check that the buddy is not already listed


export DIALOG='<window width="500">
<vbox>
	<text><label>Enter the sip address for your new buddy</label></text>
	<entry>
		<variable>BUDDY</variable>
		<default>sip:</default>
	</entry>
	<hbox>
		<button ok></button>
	</hbox>
</vbox>
</window>'
for STATEMENTS in $(gtkdialog3 --program DIALOG --name "PSIP Add Buddy"); do
  eval $STATEMENTS
done

if [ "$EXIT" = "OK" ]; then
	#add buddy to the currently running session
	echo  -e "\n+b\n$BUDDY" >> $PJSIGNAL
	#subscribe to buddy
	echo  -e "\ns\n$BUDDY" >> $PJSIGNAL

	#add buddy to config file
	LINE=$(grep -n '^\-\-add-buddy' $PJCFG | tail -1 | cut -f 1 -d ':')
	((LINE++))
	echo $LINE
	echo >> $PJCFG ##just in case the insertion point is the last line
	sed  -i $LINE\i'--add-buddy '$BUDDY $PJCFG
fi