#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_dialog_incomingcall"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/psip/dialog_incomingcall"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
# GPL v3 License
# PS VOIP for Puppy Linux v 0.7 June 27 008
# created by Lobster, CEL, HairyWill
# tested by Eric, Grant and the Puppy Community
###################

[ "$PJDEBUG" ] && echo started dialog_incomingcall
[ "$PJDEBUG" ] && echo "$@"
CALLER="$(echo $1 | sed 's/sip://;s/@proxy01.sipphone.com//' )"
[ "$CALLER" ] || CALLER=Annonymous
export DIALOG='<window title="Incoming Call">
<vbox>
<text>
    <label>'$CALLER'</label>
  </text>
  <hbox>
	<button>
       	<input file>'$PJICONS'/answer.png</input>
		<action>echo -e "\nT\n3\na\n200\n" >> '$PJSIGNAL'</action>
	</button>
	<button>
		<input file>'$PJICONS'/textchat.png</input>
		<action>'$PJAPPDIR'/dialog_inputchat '$CALLER' </action>
	</button>
	<button>
       	<input file>'$PJICONS'/hangup.png</input>
		<action>echo -e "\nT\n1\nha\n" >> '$PJSIGNAL'</action>
		<action type="exit">reject</action>
	</button>
</hbox>
</vbox>
</window>'

[ ! "$(ps -efw | grep 'PSIP Incoming Call' | grep -v 'grep')" ] &&  gtkdialog3 --program DIALOG --name "PSIP Incoming Call"

[ "$PJDEBUG" ] && echo completed dialog_incomingcall