#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_dialog_disconnectedcall"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/psip/dialog_disconnectedcall"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
# GPL v3 License
# PS VOIP for Puppy Linux v 0.7 June 27 008
# created by Lobster, CEL, HairyWill
# tested by Eric, Grant and the Puppy Community
###################


[ "$PJDEBUG" ] && echo started dialog_disconnectedcall
REASON=$1
[ "$REASON" ] || REASON="no reason given"
for PID in $(ps -efw  | grep 'PSIP Disconnected Call' | grep -v 'grep' | cut -f 1-7 -d ' '); do
    [ ! "$PID" = "root" ] && kill $PID
done

MSG="${1}." #make sure gtkdialog has something to chew on if no argument passed
export DIALOG='<window title="PSIP Disconnected Call">
<vbox>
<text>
    <label>Call has been disconnected: '$REASON'</label>
  </text>
     <button ok></button>
</vbox>
</window>'

gtkdialog3 --program DIALOG --name "PSIP Disconnected Call"> /dev/null &



[ "$PJDEBUG" ] && echo finished dialog_disconnectedcall# Very End of this file 'usr/local/psip/dialog_disconnectedcall' #
###END###
