#!/bin/sh
# GPL v3 License
# PS VOIP for Puppy Linux v 0.7 June 27 008
# created by Lobster, CEL, HairyWill
# tested by Eric, Grant and the Puppy Community
###################


[ "$PJDEBUG" ] && echo started dialog_debugger

export DIALOG='<window title="PSIP Debugger" width="500">
<vbox>
	<button>
		<label>View Error Log</label>
		<action>gtklogfileviewer '$PJLOG' close 0 0 800 300 &</action>
	</button>
	<button>
		<label>Start Quality Log</label>
		<action>echo -e "\ndq\n" >> '$PJSIGNAL'</action>
		<action>touch '$PJTMP'/call-stats</action>
		<action>rxvt -g 80x18 -title "PSIP Call Quality Log" -rv -e tail -f '$PJTMP'/call-stats &</action>
		<action>echo "" >> '$PJTMP'/call-stats &</action>
		<action>echo "Hit the [Dump Call Quality] button to get the latest call stats." >> '$PJTMP'/call-stats &</action>
		<action>echo "This will only work when you have an active call." >> '$PJTMP'/call-stats &</action>
	</button>
	<button>
		<label>Dump Call Quality</label>
		<action>echo -e "\ndq\n" >> '$PJSIGNAL'</action>
	</button>
	<button>
		<label>Build Crash Report</label>
		<action>rxvt -e '$PJAPPDIR'/func_crashreport &</action>
	</button>
</vbox>
</window>'
gtkdialog3 --program DIALOG --name "PSIP Debugger" >/dev/null &

[ "$PJDEBUG" ] && echo finished dialog_debugger
