#!/bin/sh
# GPL v3 License
# PS VOIP for Puppy Linux v 0.7 June 27 008
# created by Lobster, CEL, HairyWill
# tested by Eric, Grant and the Puppy Community
###################


[ "$PJDEBUG" ] && echo started dialog_inputchat

BUDDY="$1" #this is a URL
[ "$(echo $BUDDY | grep '>')" -o "$(echo $BUDDY | grep '>')" ] && gxmessage "Houston, we have a problem. dialog_inputchat received a URL with an angle bracket:$BUDDY"
BUDDY_NAME=$(echo $BUDDY | sed 's/sip://;s/@.*//')
touch $HOME/.psip/PSIP_chatlog

WINDOW_NAME=foo
export $WINDOW_NAME="PSIP Chat $BUDDY_NAME"

export DIALOG='<window title="PSIP Chat '$BUDDY_NAME'">
<vbox>
<entry max_length="127" width_chars="100" activates-default="true">
      <variable>CHAT</variable>
    <input>echo</input>
    </entry>
     <hbox><button can-default="true" has-default="true">
            <label>Send</label>
            <action>echo $CHAT > '$PJTMP'/chat.tmp</action>
            <action>./func_sendchat '$BUDDY' &</action>
            <action type="refresh">CHAT</action>
      </button>
     <button cancel></button>
     </hbox>
    </vbox>
    </window>'

touch $HOME/.psip/PSIP_chatlog
if [ ! "$(ps | grep 'PSIP_chatlog' | grep -v 'grep')" ] ; then 
	if [ "$(which gtklogfileviewer)" ]; then
		gtklogfileviewer $HOME/.psip/PSIP_chatlog close 0 0 800 300 &
	else
		rxvt -title PSIP_chatlog -e tail -f $HOME/.psip/PSIP_chatlog &
	fi
fi
usleep 400000 #make sure the entry box is on top
EXISTING_INSTANCE=$(ps -efw | grep "$foo" | grep -v 'grep')
[ ! "$EXISTING_INSTANCE" ] && gtkdialog3 --program DIALOG --name "$foo" >/dev/null &
[ "$PJDEBUG" ] && echo finished dialog_inputchat