#!/bin/sh
CHAT=$(cat $PJTMP/chat.tmp) #should strip out newlines if we ever get to multiline posts
echo -e "\ni\n${1}\n${CHAT}\n" >> $PJSIGNAL
BUDDY_NAME="$(echo $1 | sed 's/sip://;s/@.*//')"
echo -e "$(date +%y/%m/%d-%T) [you->$BUDDY_NAME] ${CHAT}" >> $HOME/.psip/PSIP_chatlog