#!/bin/sh

# this script installs files from
# woof-code/rootfs-skeleton into the current running system
# was once launched from outside the local git repository KarlGodt_ForkWoof.Push.d
# now inside any subdirectory below top-level
# of local git repositoy dir, f.ex. woof2.git/utils/

ME_PROG=`realpath "$0"`
ME_DIR=${ME_PROG%/*}
cd "$ME_DIR" || exit 3

#cd "$ME_DIR"/KarlGodt_ForkWoof.Push.d/woof-code/rootfs-skeleton || exit
cd "$ME_DIR"/../woof-code/rootfs-skeleton || exit 4

FIND=`find . |sort`

while read found
do


found="${found#*/}"
#echo "$found"  # DEBUG
[ "$found" ] || continue
[ -d "$found" ] && continue

#[ "${found##*/}" = '.gitignore' ] && continue
#[ "${found##*/}" = 'EMPTYDIRMARKER' ] && continue
#test "`echo "$found" | grep -iE '\.gz$|\.png$|\.xpm$|\.wav$|\.au$'`" && continue

case $found in
*.gitignore|*EMPTYDIRMARKER|*.gz|*.jpg|*.png|*.xpm|*.wav|*.au) continue;;
esac

[ -e /"$found" ] || { mkdir -p /"${found%/*}"; cp -a ./"$found" /"$found"; continue; }

[ -L ./"$found" ] && { realpath ./"$found" || continue; }

diff -qs ./"$found" /"$found" && continue # 0 is eq, 1 is different
#echo "./$found and /$found differ"

cd "$ME_DIR"/KarlGodt_ForkWoof.Push.d || exit
/bin/cp -v -a --remove-destination "$ME_DIR"/KarlGodt_ForkWoof.Push.d/woof-code/rootfs-skeleton/"$found"  /"${found%/*}" || { cd "$ME_DIR"/KarlGodt_ForkWoof.Push.d/woof-code/rootfs-skeleton; continue; }
#git add woof-code/rootfs-skeleton/"$found" || { cd "$ME_DIR"/KarlGodt_ForkWoof.Push.d/woof-code/rootfs-skeleton; continue; }
#git commit -m "${found##*/} : Bulk Maintanance Replacement of today."

cd "$ME_DIR"/KarlGodt_ForkWoof.Push.d/woof-code/rootfs-skeleton
sleep 1


done<<EOI
`echo "$FIND"`
EOI

