#!/bin/bash

FILE=`echo "$*" | cut -b 2-`
if [ -z "$FILE" ]; then TXT1="<b>$LOC710</b>"
	. "$PROGPATH"box_ok
	exit 0
else
	echo > /tmp/pfind-error$PROGPID
	exec $FILEMANAGER -s "$FILE" 2> /tmp/pfind-error$PROGPID
	TXT1=`cat /tmp/pfind-error$PROGPID`
	if [ -n "$TXT1" ]; then . "$PROGPATH"box_ok; fi #error
fi


