#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func_run"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pfind/func_run"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#

PROGRAM=`echo "$*" | cut -b 2-`
if [ -z "$PROGRAM" ]; then TXT1="<b>$LOC710</b>"
	. "$PROGPATH"box_ok
	exit
else
	echo > /tmp/pfind-error$PROGPID
	"$PROGRAM" 2> /tmp/pfind-error$PROGPID
	TXT1=`cat /tmp/pfind-error$PROGPID`
	if [ -n "$TXT1" ]; then . "$PROGPATH"box_ok; fi #error
fi


# Very End of this file 'usr/local/pfind/func_run' #
###END###
