#!/bin/bash

audiofolder=/usr/local/EmbeddedBookmarks/audiobook-example/examplefolder/audiobooks

config=/root/.EmbeddedBookmarks/audiobooks.txt


cd $audiofolder

here=`pwd`

#-- find the autors

rm -f $config 2>/dev/null
touch $config

find . -type d | sort -n | sed "s#\./##" | grep -v '/' | grep -v "^\.$" | while read a;do


	echo "[category]$a" >>$config

	
	cd "$a"
	find . -type d | sort -n | sed "s#\./##" | grep -v '/' | grep -v "^\.$" | while read b;do

		echo "$b|-run=rox|$here/$a/$b" >>$config
	done
	cd "$here"
	

done


