#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_restartwm"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/nibbac/restartwm"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#Exit from window manager will cause return to xwin, which reads
#/tmp/wmexitmode.txt and will relaunch w.m.

NEXTWM="$1"
PREVIOUSWM="`cat /etc/windowmanager`"
[ "$NEXTWM" = "" ] && NEXTWM="$PREVIOUSWM" #v1.0.7 precaution.
echo -n "$NEXTWM" > /etc/windowmanager #this makes change permanent.
echo -n "$NEXTWM" > /tmp/wmexitmode.txt

#v403 give time for /sbin/pup_event_frontend_d to quit.
KCNT=0
while [ "`pidof pup_event_frontend_d`" != "" ];do
 sleep 0.5
 KCNT=`expr $KCNT + 1`
 [ $KCNT -gt 60 ] && break #30 secs.
done
sleep 0.2

sync
#exec killall $PREVIOUSWM
#exec killall X
killall X #default is SIGTERM.
##e17
pidof tempget && kill -2 `pidof tempget`

sleep 1           #v1.0.7
#exec killall -9 X #v1.0.7 make sure X is killed.
# Very End of this file 'usr/local/nibbac/restartwm' #
###END###
