#!/bin/ash
#Barry Kauler, LGPL 2008
#called from rc.services.
#note, when the modules agrmodem.ko and agrserial.ko load, they create
#/dev/ttyAGS3 if it does not already exist.


[ "$*" ] || exit
[ "$1" = "start" ] || exit
#if a different modem selected, quit... v405...
[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "ttyAGS3" ] && exit

[ "`lsmod | grep '^agrserial '`" = "" ] && exit
ln $VERB -sf ttyAGS3 /dev/modem
ln $VERB -sf ttyAGS3 /dev/ttySAGR
#...i think wvdialconf looks for /dev/ttySAGR
if [ "`uname -r`" = "2.6.25.16" ]; then
[ -e /usr/lib/AgereSoftModem/AgereMdmDaemon ] && ( exec /usr/lib/AgereSoftModem/AgereMdmDaemon & ) #424
#...Supports HDA version of drivers, for 2.6.25.16 kernel ony.
fi

#docs have this comment for agrsm...
## Outside the USA, a country setting may be needed
# Init3 = AT+CGI=hexadecimal_country_code

#future: write /etc/countryinfo, with MODEM_COUNTRY_STRING
#.../usr/sbin/gen_modem_init_string reads this variable (called from second
#entry to /etc/rc.d/rc.modem, in rc.local0).


###END###
