#!/bin/sh
#usb modem
#Barry Kauler, LGPL 2007

[ -h /dev/modem ] && exit

[ ! $1 ] && exit
[ "$1" != "start" ] && exit

[ "`lsmod | grep '^cdc_acm'`" = "" ] && exit
ln -snf ttyACM0 /dev/modem

###END###
