#!/bin/ash
#Barry Kauler, LGPL 2009


[ "$*" ] || exit
[ "$1" = "start" ] || exit
[ "`lsmod | grep '^hso '`" ] || exit
#If a different modem selected, quit...
MODEM=""
[ -h /dev/modem ] && MODEM="`readlink /dev/modem | grep -v '^ttyHS[0-9]$'`"
[ "$MODEM" ] && exit

#Determine network port (ttyHS?). Adapted from hso_connect script.
WAITMAX=10
WAITCNT=0
MODEM_PORT=""
until [ "$MODEM_PORT" != "" ];do
 TTYS=`find /sys/class/tty -name "ttyHS*"`
 for i in $TTYS; do
  if [ `grep Modem $i/hsotype` ];then
   MODEM_PORT=$i
   break
  fi
 done
 if [ "$MODEM_PORT" = "" ];then
  WAITCNT=$((WAITCNT + 1))
  [ "$WAITCNT" -gt $WAITMAX ] && echo "Script Hso: timeout" >> /tmp/udevtrace-modem.log && break
  sleep 1
 fi
done
MODEM="`echo $MODEM_PORT | cut -f 5 -d '/'`"
[ "$MODEM" = "" ] && echo "Script Hso: no ttyHS port" >> /tmp/udevtrace-modem.log && exit
#[ $WAITCNT -gt 0 ] &&
echo "Script Hso: $WAITCNT-second wait for port $MODEM" >> /tmp/udevtrace-modem.log

#Even if /dev/modem already set, ensure it matches detected modem.
[ -h /dev/modem ] && rm $VERB /dev/modem
ln $VERB -sf $MODEM /dev/modem
[ -h /dev/ttyS_HS ] && rm $VERB /dev/ttyS_HS
ln $VERB -sf $MODEM /dev/ttyS_HS #for pupdial probe

#the module doesn't seem to support any country setting, so...
if [ -f /etc/countryinfo ];then
 SPATTERN="s/^MODEM_COUNTRY_STRING.*/MODEM_COUNTRY_STRING=''/"
 cat /etc/countryinfo | sed -e "$SPATTERN" > /tmp/countryinfo
 sync
 mv $VERB -f /tmp/countryinfo /etc/countryinfo
fi
#.../usr/sbin/gen_modem_init_string reads this variable.

###END###
