#!/bin/ash
#Barry Kauler, LGPL 2007

[ "$*" ] || exit
[ "$1" = "start" ] || exit
#v405 if a different modem selected, quit...
[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "ttySV0" ] && exit

if [ "`lsmod | grep '^ltmodem '`" != "" ];then
 ln $VERB -sf ttySV0 /dev/modem
fi

#the module doesn't seem to support any country setting, so...
if [ -f /etc/countryinfo ];then
 SPATTERN="s/^MODEM_COUNTRY_STRING.*/MODEM_COUNTRY_STRING=''/"
 cat /etc/countryinfo | sed -e "$SPATTERN" > /tmp/countryinfo
 sync
 mv $VERB -f /tmp/countryinfo /etc/countryinfo
fi
#.../usr/sbin/gen_modem_init_string reads this variable (called from second
#entry to /etc/rc.d/rc.modem, in rc.local0).


###END###
