#!/bin/ash
#Barry Kauler, LGPL 2009

[ "$*" ] || exit
[ "$1" = "start" ] || exit
#If a different modem selected, quit...
[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "ttyUSB0" ] && exit

[ "`lsmod | grep '^moto_modem '`" ] || exit
[ -h /dev/modem ] || ln $VERB -sf ttyUSB0 /dev/modem

###END###
