#!/bin/sh
#Barry Kauler, LGPL 2009

#If a different modem selected, quit...
[ -h /dev/modem ] && [ "`readlink /dev/modem`" != "noz0" ] && exit

[ ! $1 ] && exit
[ "$1" != "start" ] && exit

[ "`lsmod | grep '^nozomi '`" = "" ] && exit
[ "`lsmod | grep -E '^hso |^option '`" != "" ] && exit
[ ! -h /dev/modem ] && ln -snf noz0 /dev/modem
[ ! -h /dev/ttySNOZ0 ] && ln -snf noz0 /dev/ttyS_NOZ0 #for pupdial probe

#the module doesn't seem to support any country setting, so...
if [ -f /etc/countryinfo ];then
 SPATTERN="s/^MODEM_COUNTRY_STRING.*/MODEM_COUNTRY_STRING=''/"
 cat /etc/countryinfo | sed -e "$SPATTERN" > /tmp/countryinfo
 sync
 mv -f /tmp/countryinfo /etc/countryinfo
fi
#.../usr/sbin/gen_modem_init_string reads this variable.

###END###
