#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_theme_switcher"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/jwmconfig2-mine/theme_switcher"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#(c) Copyright Jan 2008 Barry Kauler www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#written jan 2008 for Puppy Linux.

#  <text><label>\"${CHARPAD}\"</label></text>

ICONSETSGUI=""
for ONETHEME in `find /root/.jwm/themes/ -mindepth 1 -maxdepth 1 -type f | grep 'jwmrc' | sed -e 's/-jwmrc//' | tr '\n' ' '`
do
 ONETHEME="`basename $ONETHEME`"
 ICONSETSGUI="$ICONSETSGUI
 <hbox>
  <pixmap><input file>/root/.jwm/themes/${ONETHEME}-tray.png</input></pixmap>
  <pixmap><input file>/root/.jwm/themes/${ONETHEME}-window.png</input></pixmap>
  <vbox>
   <pixmap><input file>/usr/local/lib/X11/pixmaps/invisible96x8.png</input></pixmap>
   <button><label>${ONETHEME}</label></button>
  </vbox>
 </hbox>
"

done

export ICONSWITCHGUI="
<window title=\"Puppy JWM Theme Switcher\" icon-name=\"gtk-convert\">
 <vbox>
  <text><label>JWM is the window manager, handling window borders and tray (taskbar) appearance, whereas the GTK theme is inside each window. Choose a JWM theme that matches or compliments the current GTK theme</label></text>

  ${ICONSETSGUI}
  
  <hbox>
   <button><input file stock=\"gtk-quit\"></input><label>QUIT</label></button>
  </hbox>
 </vbox>
</window>"

echo "$ICONSWITCHGUI" > /tmp/iconswitchgui
#echo "$ICONSWITCHGUI" | gtkdialog3 --stdin
RETSTUFF="`gtkdialog3 --program=ICONSWITCHGUI`"

eval "$RETSTUFF"

NEWTHEME="$EXIT"
[ "$NEWTHEME" = "" ] && exit
[ ! -f /root/.jwm/themes/${NEWTHEME}-jwmrc ] && exit

if [ "$NEWTHEME" != "" ];then
 #select chosen theme...
 cp -f /root/.jwm/jwmrc-theme /root/.jwm/jwmrc-theme.bak
 cp -f /root/.jwm/themes/${NEWTHEME}-jwmrc /root/.jwm/jwmrc-theme
 #set correct backgrounds for applets...
 cp -f /root/.jwm/jwm_colors /root/.jwm/jwm_colors.bak
 cp -f /root/.jwm/themes/${NEWTHEME}-colors /root/.jwm/jwm_colors
 #...note, /root/.xinitrc reads this file to set background for absvolume.
 #...note, jwm_colors is written to by /usr/local/jwmconfig2/gtk2jwm script

. /root/.jwm/jwm_colors #gives MENU_BG, PAGER_BG

 #########
 #John Doe created code for the applet backgrounds, old jwmconfig, port here...
 TrayFile="/root/.jwmrc-tray"
 TrayFileBak="/root/.jwmrc-tray.bak"

 BackgroundColor="$MENU_BG" #"#ffc100"
 [ "$BackgroundColor" = "" ] && BackgroundColor='#ffc100'
 IndentedBackgroundColor="$PAGER_BG"
 [ "$IndentedBackgroundColor" = "" ] && IndentedBackgroundColor='#ffa100'
 

 function GetLineIndex
 {
	lineVal=`fgrep -in "$1" $TrayFile | awk -F":" '{print $1}'`
	#return `expr $lineVal`
	return $lineVal
 }

 cp -f $TrayFile $TrayFileBak

 GetLineIndex "blinkydelayed"
 linenumber=$?
 echo $linenumber

 GetLineIndex "xload -nolabel"
 linenumber2=$?
 echo $linenumber2

 lineNumber=`expr $linenumber`
 lineNumber2=`expr $linenumber2`

 blinkyline="			blinkydelayed -bg \"$BackgroundColor\""
 xloadline="			xload -nolabel -fg red -hl white -bg \"$IndentedBackgroundColor\""
if [ $linenumber -gt 0 ]; then
 sed -e "$linenumber"i"$blinkyline" -e "$linenumber"d $TrayFileBak > $TrayFile
fi
if [ $linenumber2 -gt 0 ]; then
 sed -e "$linenumber2"i"$xloadline" -e "$linenumber2"d $TrayFileBak > $TrayFile
fi
 #end John Doe's code.
 ########
 
 sync
 pidof jwm >/dev/null && jwm -restart
fi


###END###
