#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/you2pup/func"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#You2pup
#Copyright 2009 GPL
#Trio Tjandradjaja

case "$1" in

-download)

[ "$URL" = 'Copy & paste URL here' ] && { gxmessage -center "Please copy & paste URL";exit 0; }

VIDEO=`echo "$URL" | cut -d '=' -f2 `
#FILEDIR=`echo $FILE |sed 's!\(.*\)/.*!\1!'`

if [ "$DIRECTORY" = 'Choose a directory' ] ; then
gxmessage -center "Please choose a Directory"
else
    if [ "$FILE" = 'Type new file name' ] ; then
    gxmessage -center "Please type a new File Name"
    else
    mkdir -p "$DIRECTORY"
    #exec rxvt -title "$@" -e youtube.sh -f "$VIDEO" "$DIRECTORY"/"$FILE"
    exec rxvt -title "$@" -e youtube.sh "$VIDEO" "$DIRECTORY"
    fi
fi

;;

-convert)
if [ "$DIRECTORY" = 'Choose a directory' ] ; then
gxmessage -center "Please choose a Directory"
else
    if [ "$FILE" = 'Type new file name' ] ; then
    gxmessage -center "Please type a new File Name"
    else
    cd "$DIRECTORY"
    exec rxvt -title "$@" -e ffmpeg -i "$FILE.mp4" -f $NEWFILE "$FILE"."$NEWFILE"
    fi
fi
;;
-playori)
if [ "$FILE" = 'Type new file name' ] ; then
gxmessage -center "File not found"
else
exec defaultmediaplayer "$DIRECTORY"/"$FILE.mp4" &
fi
;;
-playnew)
if [ "$FILE" = 'Type new file name' ] ; then
gxmessage -center "File not found"
else
exec defaultmediaplayer "$DIRECTORY"/"$FILE"."$NEWFILE" &
fi
;;
esac
