#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_you2pup"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/you2pup/you2pup"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#you2pup
#Copyright 2009 GPL
#Trio Tjandradjaja

DIR="/usr/local/you2pup"

export you2pup="
<window title=\"You2Pup 1.3-2\">
 <vbox>
  <frame                                   Puppy YouTube MP4 Video Downloader                                    >
    <vbox>
    <pixmap><input file>/usr/share/icons/youtube.png</input></pixmap>
    <text><label>URL ex: http://www.youtube.com/watch?v=irf0zRW_jw4</label></text>
    <hbox>
    <entry tooltip-text=\"You can highlight URL in youtube page's URL box, then drag & drop to you2pup URL box\">
     <variable>URL</variable>
     <input>echo 'Copy & paste URL here'</input>
   </entry>
   <button>
   <label>Clear</label>
   <action>clear:URL</action>
   </button>
   </hbox>
   <text><label>New File Name</label></text>
   <hbox>
   <entry accept=\"directory\">
     <variable>DIRECTORY</variable>
     <input>echo 'Choose a directory'</input>
    </entry>
    <button>
     <input file icon=\"gtk-open\"></input>
     <action type=\"fileselect\">DIRECTORY</action>
    </button>
   <entry>
     <variable>FILE</variable>
     <input>echo 'Type new file name'</input>
   </entry>
   </hbox>
   </vbox>
   <hbox>
   <text><label>\"Click to play after download\"</label></text>
   <button>
    <input file stock=\"gtk-media-play\"></input>
    <label>\"Play\"</label>
    <action>. $DIR/func -playori</action>
   </button>
   <text><label>\"                                                \"</label></text>
   <button>
    <input file icon=\"gtk-go-down\"></input>
    <label>Download</label>
    <action>. $DIR/func -download</action>
   </button>
   </hbox>
  </frame>
  <hbox>
   <button>
    <input file icon=\"gtk-quit\"></input>
    <label>Quit</label>
   </button>
   <text><label>\"    \"</label></text>
   <frame Create new media file and play afterwards>
   <hbox>
   <text><label>Convert to</label></text>
  <combobox>
     <variable>NEWFILE</variable>
        <item>asf</item>
        <item>au</item>
        <item>avi</item>
        <item>dvd</item>
        <item>flv</item>
        <item>mov</item>
        <item>mp3</item>
        <item>mpeg</item>
        <item>ogg</item>
        <item>svcd</item>
        <item>swf</item>
        <item>vcd</item>
        <item>wav</item>
    </combobox>
    <button>
    <input file icon=\"gtk-refresh\"></input>
    <label>Convert</label>
    <action>. $DIR/func -convert</action>
   </button>
   <text><label>\"    \"</label></text>
   <button>
    <input file stock=\"gtk-media-play\"></input>
    <label>Play</label>
    <action>. $DIR/func -playnew</action>
   </button>
   </hbox>
   </frame>
    </hbox>
 </vbox>
</window>"

#execute gtkdialog
gtkdialog3 --center --program=you2pup
unset you2pup

#clear
exit 0
