#!/bin/bash
#you2pup
#Copyright 2009 GPL
#Trio Tjandradjaja
#Modified - April 2011 Trio Tjandradjaja

DIR="/usr/local/you2pup"

export you2pup="	
<window title=\"You2Pup 2.1.4\" allow-grow=\"false\">
 <vbox>
  <frame                              Puppy YouTube Multi Format Video Downloader                               > 
	<vbox>
	<pixmap><input file>/usr/share/pixmaps/you2pup.png</input></pixmap>
	<text><label>URL ex: http://www.youtube.com/watch?v=irf0zRW_jw4</label></text>
    <entry tooltip-text=\"You can highlight URL in youtube page's URL box, then drag & drop to you2pup URL box\"> 
     <variable>URL</variable>
	 <input>echo 'Step 1 - Copy & paste URL here'</input>
   </entry>
   <text><label>Choose download directory</label></text>
   <hbox>
   <entry accept=\"directory\">
     <variable>DIRECTORY</variable>
	 <input>echo 'Step 2 - Choose a directory'</input>
    </entry>
    <button>
     <input file icon=\"gtk-open\"></input>
     <action type=\"fileselect\">DIRECTORY</action>
    </button>
	<text><label>\"Step 3 -\"</label></text>
   <button>
    <input file icon=\"gtk-go-down\"></input>
    <label>Download</label>
    <action>. $DIR/func -download</action>
   </button>
   </hbox>   
   </vbox>
   </frame>
   <hbox>
   <button>
    <input file icon=\"gtk-quit\"></input>
    <label>Quit</label>
   </button>
   <button>
    <input file icon=\"gtk-open\"></input>
    <label>Go to DL Folder</label>
    <action>. $DIR/func -opendir</action>
   </button>
   </hbox>
   </vbox>
</window>"

#execute gtkdialog
gtkdialog3 --center --program=you2pup
unset you2pup

#clear
exit 0