#!/bin/ash
DEFAULT=aqualung
OPTIONS=-L\ -N\ 1

if test -f "$@"; then
 case "$@" in
 file:/*) jFILE="${@#*file:}"
         set - "$jFILE";;
 esac
fi

which $DEFAULT || { echo "$DEFAULT not installed in PATH ."; exit 1; }
exec $DEFAULT $OPTIONS "$@"
