#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/jwmthememaker/func"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#jwmthememaker
#Copyright 2009 GPL
#Trio Tjandradjaja

case "$1" in

-rgb2hex)
	rgb2hex `cat /tmp/color.tmp` > /tmp/color.tmp
	HEX=`cat /tmp/color.tmp` 
	echo "#$HEX" > /tmp/color.tmp
	;;

-makefile)
[ "$NAME" = 'Type in new theme name' ] && gxmessage -bg orange -center "Please type in new theme name" && exit 0
[ "$COLOR1" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR2" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR3" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR4" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR5" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR6" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR7" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR8" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ "$COLOR9" = 'Please choose a color' ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0

[ ! "$NAME" ] && gxmessage -bg orange -center "Please type in new theme name" && exit 0
[ ! "$COLOR1" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR2" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR3" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR4" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR5" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR6" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR7" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR8" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0
[ ! "$COLOR9" ] && gxmessage -bg orange -center "Please fill in all color boxes" && exit 0


Xdialog --title "JWM Maker Splash" --no-close --screen-center -no-buttons --infobox "Saving $NAME theme
Trio Tj - GPL 2009" 10 30
p=$!

	echo "#see /usr/local/jwmconfig2/theme-switcher script.
MENU_BG=$COLOR7
ACTIVE_BG=$COLOR1
FOREGROUND=$COLOR5
PAGER_BG=$COLOR7
FG_SELECTED=$COLOR5 " > $HOME/.jwm/themes/$NAME-colors

	echo "<JWM>

<WindowStyle>
    <Font>$FONT-$FONTSIZE</Font>
    <Width>3</Width>
    <Height>22</Height>     
    <Active>
       <Text>$COLOR5</Text>
       <Title>$COLOR1:$COLOR2</Title>
<!--       <Corner>$COLOR1</Corner> -->
       <Outline>$COLOR10</Outline>
    </Active>
    <Inactive>
       <Text>$COLOR6</Text>
       <Title>$COLOR3:$COLOR4</Title>         
<!--       <Corner>$COLOR3</Corner> -->
       <Outline>$COLOR10</Outline>
    </Inactive>
</WindowStyle> 

<TaskListStyle>
<Font>$FONT-$FONTSIZE</Font>
<ActiveForeground>$COLOR5</ActiveForeground>
<ActiveBackground>$COLOR1:$COLOR2</ActiveBackground>
<Background>$COLOR3:$COLOR4</Background>
</TaskListStyle>

	<!-- TRAY PROPERTIES -->

	<TrayStyle>
		<Font>$FONT-$FONTSIZE</Font>
		<Foreground>$COLOR6</Foreground>
		<Background>$COLOR7</Background>
	</TrayStyle>

	<!-- PAGER PROPERTIES -->

	<PagerStyle>
		<Outline>grey</Outline>
		<Foreground>$COLOR4</Foreground>
		<Background>$COLOR3</Background>
		<ActiveForeground>$COLOR1</ActiveForeground>
		<ActiveBackground>$COLOR2</ActiveBackground>
	</PagerStyle>

	<PopupStyle>
		<Font>$FONT-$FONTSIZE</Font>
		<Outline>$COLOR10</Outline>
		<Foreground>$COLOR9</Foreground>
		<Background>$COLOR8</Background>
	</PopupStyle>

	<MenuStyle>
		<Font>$FONT-$FONTSIZE</Font>
		<Foreground>$COLOR6</Foreground>
		<Background>$COLOR7</Background>
		<ActiveForeground>$COLOR5</ActiveForeground>
		<ActiveBackground>$COLOR1:$COLOR2</ActiveBackground>
	</MenuStyle>

</JWM>" > $HOME/.jwm/themes/$NAME-jwmrc

kill $p
	;;
-instantapply)
[ ! "`ls $HOME/.jwm/themes | grep $NAME`" ] && gxmessage -bg orange -center "$NAME has not been saved" && exit 0
NEWTHEME="$NAME"

exec gtk-theme-switch2 /usr/share/themes/$GTKTHEME &

if [ "$NEWTHEME" != "" ];then
 #select chosen theme...
 cp -f /root/.jwm/themes/${NEWTHEME}-jwmrc /root/.jwm/jwmrc-theme
 #set correct backgrounds for applets...
 cp -f /root/.jwm/themes/${NEWTHEME}-colors /root/.jwm/jwm_colors
 #...note, /root/.xinitrc reads this file to set background for absvolume.
 #...note, jwm_colors is written to by /usr/local/jwmconfig2/gtk2jwm script

. /root/.jwm/jwm_colors #gives MENU_BG, PAGER_BG

 #########
 #John Doe created code for the applet backgrounds, old jwmconfig, port here...
 TrayFile="/root/.jwmrc-tray"
 TrayFileBak="/root/.jwmrc-tray.bak"

 BackgroundColor="$MENU_BG" #"#ffc100"
 [ "$BackgroundColor" = "" ] && BackgroundColor='#ffc100'
 IndentedBackgroundColor="$PAGER_BG"
 [ "$IndentedBackgroundColor" = "" ] && IndentedBackgroundColor='#ffa100'
 

 function GetLineIndex
 {
	lineVal=`fgrep -in "$1" $TrayFile | awk -F":" '{print $1}'`
	#return `expr $lineVal`
	return $lineVal
 }

 cp -f $TrayFile $TrayFileBak

 GetLineIndex "blinkydelayed"
 linenumber=$?
 echo $linenumber

 GetLineIndex "xload -nolabel"
 linenumber2=$?
 echo $linenumber2

 lineNumber=`expr $linenumber`
 lineNumber2=`expr $linenumber2`
 
#Zigbert added this, because maybe somebody forgot to put
blinkyline="blinkydelayed -bg \"$BackgroundColor\""
xloadline=" xload -nolabel -fg red -hl white -bg \"$IndentedBackgroundColor\""


#fixed by hairywill 20-01-09 handle case where linenumber/2 is zero
[ ! "$lineNumber" = 0 ] && sed -ie "$lineNumber"d  $TrayFile && sed -ie "$lineNumber"i"$blinkyline" $TrayFile
[ ! "$lineNumber2" = 0 ] && sed -ie "$lineNumber2"d $TrayFile && sed -ie "$lineNumber2"i"$xloadline" $TrayFile
#sed -e "$lineNumber"i"$blinkyline" -e "$lineNumber"d -e "$lineNumber2"i"$xloadline" -e "$lineNumber2"d $TrayFileBak > $TrayFile
 #end John Doe's code.
 ########
 
#Trio-this to make absvolume follows theme without reboot
if [ -f /usr/bin/absvolume ];then
if [ "$MENU_BG" = "" ];then
killall absvolume
absvolume &
else
killall absvolume
absvolume -bg $MENU_BG &
fi
fi

 
 sync
 pidof jwm >/dev/null && jwm -restart
fi
;;
esac