#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_find_certs"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/PuppyBrowser/find_certs"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#

for ONEDB in `find /root/.mozilla/default/*.slt -maxdepth 2 -type f -name *.db | tr '\n' ' '`
do
 cp -f $ONEDB ${HOME}/.PuppyBrowser/mozilla/
done
# Very End of this file 'usr/local/PuppyBrowser/find_certs' #
###END###
