#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_cpu_freq"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/cpu-freq/cpu_freq"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#
#cpu_freq GUI
#Trio Tjandradjaja - GPL 2009

DIR="`dirname $0`"
[ "$DIR" = "." ] && DIR="`pwd`"
export DIR="$DIR"

case "$1" in
-start)

STATUSCPU0="`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`"
STATUSCPU1="`cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor`"
if [ ! "$STATUSCPU0" ] ; then
gxmessage -bg pink "Your CPU Frequency Scaling is not activated, 
please proceed" &
else
if [ ! "$STATUSCPU1" ] ; then
CPU1="CPU Frequency Scaling CPU 1 is not activated, 
or you don't have CPU 1, don't worry, please proceed"
else
CPU1="	$STATUSCPU1 

is already activated
Frequencies - Min: `cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq` Max: `cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq`"
fi

gxmessage -bg pink "Your CPU Frequency Scaling CPU 0 Status:

	$STATUSCPU0 

is already activated
Frequencies - Min: `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` Max: `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`

Your CPU Frequency Scaling CPU 1 Status:

$CPU1"
fi

export cpu_freq="	
<window title=\"CPU FREQUENCY SCALING 1.3-2\">
 <vbox>
  <frame Try to activate on demand CPU Frequency Scaling>
  
  <text><label>Don't worry, warnings will pop up to guide you</label></text>
  <text><label>\" \"</label></text>
  <text><label>Choose a module and click Activate</label></text>
  <hbox>
  <combobox> 
     <variable>MODULES</variable>
<item>acpi-cpufreq      # generic</item>
<item>p4-clockmod      # Intel</item>
<item>speedstep-centrino   # Intel Centrino</item>
<item>speedstep-ich      # Intel</item>
<item>speedstep-smi      # Intel</item>
<item>powernow-k6      # AMD</item>
<item>powernow-k7      # AMD</item>
<item>powernow-k8      # AMD</item>
<item>longrun      # Transmeta</item>
<item>longhaul      # VIA Technologies</item>
<item>e_powersaver      # VIA Technologies</item>
<item>cpufreq-nforce2   # nVidia</item>
<item>gx-suspmod      # Cyrix Media</item>
</combobox>
   <button>
<input file icon=\"gtk-apply\"></input>
    <label>Activate</label>
	<action>. $DIR/cpu_func -modules</action>
	<action>exit: 0</action>
   </button>
   </hbox>
    </frame>
  <hbox>
  <button tooltip-text=\"To use another module (if you're using pupsave from  different computer)\">
	<input file icon=\"gtk-delete\"></input>
    <label>Refresh Modules</label>
	<action>. $DIR/cpu_func -refresh</action>
   </button>
   <button>
    <input file icon=\"gtk-quit\"></input>
    <label>OUIT</label>
   </button>
  </hbox>
 </vbox>
</window>"

#execute gtkdialog
I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog3 --program=cpu_freq --center); do
	eval $STATEMENTS
done
IFS=$I
;;

-again)
export cpu_freq="	
<window title=\"CPU FREQUENCY SCALING 1.3-1\">
 <vbox>
  <frame Try to activate on demand CPU Frequency Scaling>
  
  <text><label>Don't worry, warnings will pop up to guide you</label></text>
  <text><label>\" \"</label></text>
  <text><label>Choose a module and click Activate</label></text>
  <hbox>
  <combobox> 
     <variable>MODULES</variable>
<item>acpi-cpufreq      # generic</item>
<item>p4-clockmod      # Intel</item>
<item>speedstep-centrino   # Intel Centrino</item>
<item>speedstep-ich      # Intel</item>
<item>speedstep-smi      # Intel</item>
<item>powernow-k6      # AMD</item>
<item>powernow-k7      # AMD</item>
<item>powernow-k8      # AMD</item>
<item>longrun      # Transmeta</item>
<item>longhaul      # VIA Technologies</item>
<item>e_powersaver      # VIA Technologies</item>
<item>cpufreq-nforce2   # nVidia</item>
<item>gx-suspmod      # Cyrix Media</item>
</combobox>
   <button>
<input file icon=\"gtk-apply\"></input>
    <label>Activate</label>
	<action>. $DIR/cpu_func -modules</action>
	<action>exit: 0</action>
   </button>
   </hbox>
    </frame>
  <hbox>
  <button tooltip-text=\"To use another module (if you're using pupsave from  different computer)\">
	<input file icon=\"gtk-delete\"></input>
    <label>Refresh Modules</label>
	<action>. $DIR/cpu_func -refresh</action>
   </button>
   <button>
    <input file icon=\"gtk-quit\"></input>
    <label>OUIT</label>
   </button>
  </hbox>
 </vbox>
</window>"

#execute gtkdialog
I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog3 --program=cpu_freq --center); do
	eval $STATEMENTS
done
IFS=$I
;;
esac# Very End of this file 'usr/local/cpu-freq/cpu_freq' #
###END###
