#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_tail"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pburn/box_tail"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

tailing (){
	echo "$TAIL_TITLE" 
	cat $WORKDIR/tail_percent
	sleep 1
	[ -s "$LOG" ] && tail -n 20 "$LOG" | tr '\r' '\n' | tail -n 20 > $WORKDIR/tail
	echo 100 > $WORKDIR/tail_percent
}
export -f tailing

echo 99 > $WORKDIR/tail_percent
echo -n > $WORKDIR/tail

export pburn_tail="
<window title=\"Pburn\">
<vbox>
 <progressbar>
  <input>"'while [ A != B ]; do tailing; done'"</input>
  <action>refresh:TAIL</action>
  <action>echo 99 > $WORKDIR/tail_percent</action>
 </progressbar>
 <edit>
  <variable>TAIL</variable>
  <input file>$WORKDIR/tail</input>
  <width>400</width><height>380</height>
 </edit>
 <hbox homogeneous=\"true\">
  <button>
   <label>$TAIL_BUTTON</label>
   <action>EXIT:tail_button</action>
  </button>
 </hbox>
</vbox>
</window>"

I=$IFS; IFS=""
for STATEMENTS in $($GTKDIALOG -p pburn_tail --center); do
	eval $STATEMENTS
done
IFS=$I

	