#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func_man"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pburn/func_man"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
AUDIO_FORMATS="`echo $AUDIO_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
VIDEO_FORMATS="`echo $VIDEO_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
IMAGE_FORMATS="`echo $IMAGE_FORMATS | tr -d '\' | tr -d '$' | tr -d '.'`"
echo "\

Usage: pburn [OPTION] [FILE]
[FILE] is a *.pbn or *.iso - if not, use the -i parameter

Options
  -c          Do NOT autodetect media. 
              Multisession settings will not be complete by default.
  -d [DIR]    Use [DIR] as default browser directory
  -f          Use raw-burn-mode.
              Burn content of $HOME/.pburn/pburn_symlink_tree,
              and always follow symlinks
  -g [ENGINE] Define what burn-engine to use. [ENGINE] can be:
                cdrtools
                cdrkit
              Pburn uses cdrtools if both is present.
  -h          Show this help message
  -i [FILE]   Import textfile with list of files
  -m [MODE]   Skip main gui. Go straight to [MODE]:
                data
                audio
                video
                iso
                blank
                copy-data
                copy-audio
                copy-video
  -r          Reset all settings/ Reinstall helpfile
  -v          Show Pburn version

Supported formats (with working ffmpeg):
Audio: $AUDIO_FORMATS
Video: $VIDEO_FORMATS
Image: $IMAGE_FORMATS"