#!/bin/bash
echo -e "pstopwatch \c" > /tmp/ptimer-exec
case $1 in
-stopwatch)
	if [ "$AUTOSTART" = "true" ]; then echo -e "-x \c" >> /tmp/ptimer-exec; fi
	if [ "$TENTH" = "false" ]; then echo -e "-s \c" >> /tmp/ptimer-exec; fi
	if [ "$COUNTDOWN" = "false" ]; then echo -e "-c \c" >> /tmp/ptimer-exec; fi
	if [ "$TIMER" = "true" ]; then echo -e "-t $ENTRY_TIMER \c" >> /tmp/ptimer-exec; fi
	;;
-clock)
	echo -e "-C \c" >> /tmp/ptimer-exec
	if [ "$CLOCK_ALARM" = "true" ]; then
		echo -e "-A $ENTRY_ALARM -l ::\"Alarm at ${ENTRY_ALARM/:/.}\" \c" >> /tmp/ptimer-exec
	else
		echo -e "-l \"::Clock\" \c" >> /tmp/ptimer-exec
	fi
	;;
-settings)
	for item in $ENTRY_WINDOWSIZE $ENTRY_FONTSIZE $ENTRY_FONT $SOUND_BEEP_LOW $SOUND_BEEP_HIGH $SOUND_ALARM
	do
	echo "$item" >>/tmp/ptimer_settings.dmp
	done
	;;
esac
if [ "$CHECK_WINDOWSIZE" ]; then echo "-w $ENTRY_WINDOWSIZE \c" >> /tmp/ptimer-exec; fi
if [ "$CHECK_FONT" ]; then echo "-f \"$ENTRY_FONT\":$ENTRY_FONTSIZE \c" >> /tmp/ptimer-exec; fi
if [ "$CHECK_SOUND" ]; then echo "-a \"$SOUND_ALARM\" -b \"$SOUND_BEEP_LOW\" -B \"$SOUND_BEEP_HIGH\" \c" >> /tmp/ptimer-exec; fi

chmod 700 /tmp/ptimer-exec
/tmp/ptimer-exec &
