#!/bin/bash
#Pburn
#version=3.1.x
#language=en_US:english
#translator=native

# |==================================|
# | <b>text</b>            Bold text |
# |==================================|

export LOC_OK="Ok"
export LOC_CANCEL="Cancel"
export LOC_INFO="Information"
export LOC_ERROR="Error"
export LOC_YES="Yes"
export LOC_NO="No"
export LOC_APPLY="Apply"
export LOC_QUIT="Exit"
export LOC_OPTIONS="Options"
export LOC_ISO="ISO-image"

export LOC001="CD/DVD/Blu-ray Burner"

#Menu
export LOC100="File"
 export LOC101="New"
 export LOC102="Open"
 export LOC103="Save"
 export LOC109="Save as"
 export LOC104="Import session(s) from disc"
 export LOC108="Import (play)list"
 export LOC107="Import ISO-image"
 export LOC105="Export to ISO-image"
 export LOC106="Preferences"
export LOC110="Edit"
 export LOC111="New directory"
 export LOC112="Rename"
 export LOC113="Remove"
 export LOC117="Search"
 export LOC150="Add selection"
 export LOC151="Add audio files"
 export LOC152="Add videos"
 export LOC153="Add images"
 export LOC154="Add all"
 export LOC116="Add content of (play)list"
 export LOC120="Burn"
 export LOC121="Data CD/DVD/Blu-ray"
 export LOC122="Audio CD"
 export LOC129="Video DVD/CD"
 export LOC124="ISO-image"
 export LOC123="Audio from TOC file"
 export LOC127="Audio from CUE file"
 export LOC125="Copy data disc"
 export LOC128="Copy audio CD"
 export LOC160="Copy/shrink video DVD"
 export LOC126="Blank CD/DVD-rw"
export LOC130="Tools"
 export LOC132="Eject disc"
 export LOC133="Load tray"
 export LOC134="Verify disc quality"
 export LOC135="Fixate"
 export LOC136="Disc info"
export LOC140="Help"
 export LOC141="About"

#Main gui
export LOC200="Burn mode"
export LOC201="Burn Data"
export LOC202="Burn Audio"
export LOC219="Burn Video"
export LOC203="Burn ISO-image"
export LOC204="Add data from here... (mouse-click-right)"
export LOC208="name"
export LOC211="right click"
export LOC212="...burn content of this list"
export LOC213="size"
export LOC214="Minimum size"
export LOC218="Min" #minutes
export LOC215="A data-disc contains files (and directories) for
PCs, mp3-players, Divx-players...
Add from the browser/search to the burn list."
export LOC216="An Audio CD can be used in ordinary CD-players.
Supported formats are: *.mp3 *.ogg *.wav *.wma ..."
export LOC217="1. Burn your movies and images, and play it on your TV.
    Formats: *.avi *.flv *.mpg *.wmv ... *.gif *.jpg *.png ...
2. Make an image slideshow with background music.
3. Burn a predefined DVD-video filesystem (video_ts)."
export LOC220="Desktop"
export LOC221="Home"
export LOC222="Free"
export LOC223="Added"
export LOC224="No CD"
export LOC225="read only"

###### SETTINGS #######
#General
export LOC227="Show hidden files in browser"
export LOC228="Search options / MIME settings"
export LOC229="General"
export LOC231="Show tooltips (restart required)"
export LOC232="Language"
export LOC233="Themes"
export LOC234="Search paths"
#Burn
export LOC235="Disc options"
export LOC236="Mediatype"
export LOC237="Multisession - Allow more burning on this disc later"
export LOC238="Close disc - Make disc unwritable after this burn"
export LOC239="Temporary storage"
export LOC240="On-the-fly - No temporary storage (DVD recommended)"
export LOC241="Use temporary storage (CD recommended)"
export LOC242="free"
export LOC243="Overburn"
#export iso-image
export LOC230="Where should the new ISO-image be saved?"
#file system
export LOC249="Filesystem"
export LOC250="Base filesystem"
export LOC251="Iso9660 level 1 - 8.3 chars. This is very compatible."
export LOC252="Iso9660 level 3 - max 31 uppercase chars and no spaces."
export LOC253="Extended filesystem"
export LOC254="Rockridge - Long filenames in Linux"
export LOC255="Joliet - Long filenames in Windows"
export LOC256="Follow symlink - (When off, 'size' will probably show more than you actually need)"
export LOC257="UDF - Allow large files < 4Gb (linux only)"
#devices
export LOC260="Burner device"
export LOC261="Device"
export LOC262="Media"
export LOC263="The CD burn speed"
export LOC264="The DVD burn speed"
export LOC267="Input device"
export LOC268="The device you want to copy from, may be the same as the burner device"
#audio
export LOC270="Burn mode"
export LOC271="Raw mode - Some burners support only this"
export LOC272="Track-at-once - Safe mode"
export LOC273="Disc-at-once - No gaps between songs"
export LOC440="Volume"
export LOC441="Normalize volume"
export LOC442="Tune volume level"
#CD-text
export LOC290="CD-text"
export LOC291="Activate CD-text"
export LOC292="Artist - Song"
export LOC293="Album title"
export LOC294="Album artist"
export LOC295="Retrieve CD-text from disc or internet"
#Video
export LOC700="TV standard"
export LOC701="Aspect ratio"
export LOC704="widescreen"
export LOC705="Country"
export LOC706="Pause between movies (in seconds)"
#slideshow
export LOC713="Activate image slideshow"
export LOC710="Slideshow"
export LOC711="View images (in seconds)"
export LOC712="Background music"
export LOC714="seconds"
export LOC715="images"
export LOC716="Only build Slideshow file (*.mpg) - NO burn"
export LOC717="Time"
#publish
export LOC274="Publish"
export LOC276="Publisher"
export LOC277="Preparer"
export LOC278="Project label"
#blank disc
export LOC400="Blank disc"
export LOC401="Fast blank - Erase table of context"
export LOC402="Blank complete - Erase all datas on disc"
export LOC403="Type"
#copy
export LOC420="Please insert the disk you want to copy in"
export LOC421="Since you are using the same drive for both read and write this will be done in two stages."
export LOC422="Copying to harddisk, please wait..."
export LOC423="Insert a blank disc in"
export LOC428="Copy"
export LOC429="and a blank disc into"
export LOC450="On-the-fly - No temporary storage (MUST BE 2 different drives)"
export LOC451="Use temporary storage (Can copy with only 1 drive)"
export LOC452="Reading content of disc ... Please wait ..."
#copy video
export LOC461="Title (Field shows title with most chapters):"
export LOC462="Copy the complete DVD - (requires most often to burn a dual layer DVD)"
export LOC463="Copy only movie - shrink to fit on a common (single-layer) DVD"
export LOC464="Subtitle channel (your language):"
export LOC465="Audiostream (for dubbed movie):"
#advanced
export LOC279="Advanced"
export LOC280="Refresh command"
export LOC281="Allow manual edit"
export LOC282="Edit burn-command (below) and pre-operations"
export LOC284="Define CPU-priority"

##### DIALOGS #####
#finished
export LOC406="Finished"
export LOC407="Operation finished!"
export LOC408="Repeat burn action"
export LOC470="Verify burn"
export LOC475="Note! <b>Verify may take time.</b> Depending on burnt complexity." 
export LOC471="No errors returned"
export LOC472="Errors found! Check the Pburn log"
export LOC473="Save ISO"
export LOC474="Insert new disc, and press OK."
export LOC476="Save Slideshow file"
export LOC477="Save log"
export LOC479="Eject disc when finished."
export LOC480="<b>Note!</b>
Depending on the linux kernel, you might need to reload disc to verify it correct. Please reload (eject and insert) disc and try again."

#error
export LOC750="Start burning once more"
export LOC751="Start all over again"

#encode
export LOC410="Select a toc file"
export LOC416="Select a cue file"
export LOC411="You are about to create a CD using the file"
export LOC413="Continue?"

#log
export LOC430="Emergency STOP"
export LOC431="Verifying disc"
export LOC434="Please wait..."
export LOC435="NB! Do not use disc while verifying..."
export LOC432="Verifying finished"
export LOC433="Burning progress"

#c2scan
export LOC500="
This scans the disc for C2 errors. The reader tries to interpolate these gaps in data, but if there are too many errors, it could give a reading failure. C2 errors can occur because the disc is physically out-of-balance (like a wheel which is out-of-round, or heavier on one side), in which case they may be avoided by reducing the burning speed.

<b>Start scanning disc and evaluate output.</b>"

#fixate
export LOC505="
It could happend that the burning process burns fine, but halts at the final fixating. The disc is like this not usable. Fixating disc builds data coordinates, so the disc will be readable.

<b>Start fixating disc.</b>"

#Disc info
export LOC506="Content of disc"
export LOC507="Md5sum"
export LOC508="No info"
export LOC509="Media size"
export LOC510="Free space"
export LOC511="Closed disc"

#tooltips
export LOC801="Go to burn options"
export LOC802="Exit Pburn"
export LOC803="Move item UP"
export LOC804="Move item DOWN"
export LOC805="Create new directory on the burn disc."
export LOC806="Rename item on the burn disc. 
This will NOT change source file."
export LOC807="Remove item from burn list.
This will NOT delete source file."
export LOC808="Add item to burn-list. (mouse-click-right)"
export LOC809="Search for filename"

##### ERRORS / MESSAGES#####
export LOC301="List is empty."
export LOC302="Nothing to burn."
export LOC303="<b>Can't find a valid Video-DVD.</b>
Please wait for the disc to spin up before trying again."
export LOC304="Please insert disc.
If disc is already in tray, - Please reload it."
export LOC306="File is not recognized as an iso-image.
It could still be valid.

Press 'Yes' to continue burn process."
export LOC307="<b>Inserted disc is not blank or writable</b>

- Burning <b>Audio/Video</b> requires a blank disc.
- Burning <b>Data</b> requires a writeable or blank disc.
- Burning <b>iso-image</b> may require a blank disc. You can mix data from the chosen iso-image with the content on the disc, but if burning a bootable disc it might be corupted. An exception is when updating the LIVE-disc to a newer version. Files in the new image will replace similar files on the disc. Press 'Continue' to add more data from the iso-image to the disc."
export LOC309="Specify only one iso-file."
export LOC311="Not a valid file!"
export LOC312="Imports external data"		#splash
export LOC313="Checking media...
Building command"		#splash
export LOC315="Imports session(s) from"		#splash
export LOC317="Selection is not a directory."
export LOC319="Pfilesearch is not installed. Search will not work."
export LOC321="Another ISO-image is already imported."
export LOC322='<b>You have chosen to burn an *.iso filesystem image.

Normally the filesystem should be unpacked onto the disc</b>, unless for some reason you want to put the *.iso on the disc as a single file.

What would you like to do?'
export LOC323="Pburn is already running, or it was previously exited incorrectly.
<b>Clear storage, and continue?</b>"
export LOC324="<b>Not valid file format.</b> Operation failed."
export LOC325="Volume: 'normalize' is not installed."
export LOC326="<b>vcdimager</b> must be installed to support Video CD (VCD/SVCD)."
export LOC327="<b>dvdauthor</b> must be installed to support Video DVD."
export LOC328="<b>vobcopy</b> must be installed to copy Video DVD."
export LOC329="<b>vamps</b> must be installed to shrink Video DVD."
export LOC331="Pburn can't open files from imported sessions."
export LOC332="<b>Nothing to add.</b> Select item in the left pane.

Note! You can also add by mouse right click on item."
export LOC333="Pburn's temporary storage directory is currently inside a virtual filesystem. This can cause problems when burning a large amount of data, so we recommend you change this setting to use a directory on a mounted hard drive.

<b>Temporary storage on a Windows FAT partition works mostly, but will fail for audio/video burning.</b> NTFS is fine."
export LOC334="It seems that your burner drive is not autodetected by Pburn, and it is set to /dev/cdrom. This will often work ok, but to be sure you should define (click on) the correct one."
export LOC335="See File->Preferences."
export LOC336="Adding content..."
export LOC337="Unpack filesystem" #Button: burn iso-image the normal way
export LOC338="Single file" #Button: burn iso-image as is
export LOC339="Continue with valid disc"
export LOC340="Blanking disc, please wait...

This operation runs a fast blank. If it for some reason fails to blank your disc, please use the 'blank complete' function from menu 'Burn'."
export LOC341="Burnt disc" #show md5sum of content of filesystem on burnt disc
export LOC342="Calculating md5sum, please wait ..."
export LOC343="Temporary storage should not be located inside
../pburn_symlink_tree/"
export LOC344="<b>Important!</b> Temporary storage does not exist, or points to an unmounted partition. Please change the location, or mount the partition. <b>NOW!</b>"
export LOC345="It's not a valid CD in tray."
export LOC346="Command 'close' is not installed."
export LOC347="No valid audio-CD inserted."
export LOC348="Missing dependency"
export LOC349="Already in burn list"
export LOC350="About burning a Puppy iso-image"
export LOC351="Normally we recommend to close session after burning an iso-image. Closed session is the only way to verify burning using md5sum. However, Puppy Linux supports writing user-data back to the Live-CD/DVD during shutdown - no harddrive is needed. To do this, the disc must be open for more burning. You should choose a multisession burn if you intend to use the CD/DVD as your personal storage."
export LOC352="The size of burn content is more than the official media size."
export LOC353="Do you want to activate Overburning?"



export LOC375="Disc is mounted. Please unmount, and try again."
export LOC377="No (play)list is selected."
export LOC378="The list seems to be a music playlist. Should Pburn number the songs to keep them in order?"
export LOC379="Create new directory"
export LOC380="Pburn can't rename files from imported sessions."
export LOC381="<b>Nothing is selected.</b>"
export LOC382="Pburn can't remove files from imported sessions."
export LOC383="File not found."
export LOC384="Unable to open file."
export LOC385="File already exists."
export LOC386="Do you want to overwrite existing file?"
export LOC387="No disc inserted"
export LOC388="<b>No blank disk detected, or no valid multisession disk.</b>"
export LOC389="<b>Not enough space in temporary storage.</b> Free up some space, or change the temporary storage location from menu 'File-Preferences-Burn'."
export LOC390="Unknown error."
export LOC391="Inserted disc is not writeable"
export LOC392="<b>Joliet error.</b>"
export LOC393="<b>Can't detect burner.</b>"
export LOC394="<b>Too much data for chosen burn-media.</b>"
export LOC397="<b>Can't blank this media.</b> Be sure to use a complete blank." 
export LOC398="<b>Media seems to be closed for more data.</b>"
export LOC399="See log for more information."
