#!/bin/bash

function_i_want(){
if [ "$@" ] ; then
 if [[ "$@" =~ 'beg' ]] ; then
  echo "issue 1 1 chat 'Hi, everyone :)'"
 elif [[ "$@" =~ 'end' ]] ; then
  echo "issue 1 1 chat 'I am about to leave.'"
  echo "issue 1 1 chat 'Anyone has a message for me ?'"
  sleep 10s
 else
  #echo "$@"
  echo 'issue 1 1 chat '"$*"
 fi
else
 echo "issue 1 1 chat 'Greetings !!!!'"
fi
}

_real(){
case $* in
'')    echo issue 1 1 chat 'Greetings !!!!'
begin) echo issue 1 1 chat 'Hi, everyone :)'
end)   echo issue 1 1 chat 'I am about to leave in 10 sec.'
echo issue 1 1 chat 'Anyone has a message to me ?'
 sleep 10;;
*) echo issue 1 1 chat "$*";;
esac
}

#function_i_want "$@"
_real "$*"

#echo "issue 1 1 chat 'Greetings !!!!'"
