#!/bin/bash
PETLIST='<hbox>
 <text><label>'"$LOC_320"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Gimp</input>
   <action>echo "Gimp" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_321"'</label></text>                        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Pwidgets</input>
   <action>echo "Pwidgets" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
<text><label>'"$LOC_322"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Audacity</input>
   <action>echo "Audacity" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_323"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/songbird.png</input>
   <action>echo "Songbird" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_324"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Wine</input>
   <action>echo "Wine" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_326"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/google.png</input>
   <action>echo "Google" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>'
########################################################################
NETLIST='<hbox>
 <text><label>'"$LOC_501"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Firefox</input>
   <action>echo "Firefox" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_502"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Seamonkey</input>
   <action>echo "Seamonkey" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_503"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Chromium</input>
   <action>echo "Chromium" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_504"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Opera</input>
   <action>echo "Opera" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_505"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Thunderbird</input>
   <action>echo "Thunderbird" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_506"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/kompozer.png</input>
   <action>echo "Kompozer" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>'
########################################################################
UPDATE='<text use-markup="true"><label>"<b>Lucid Puppy '"$LOC_315"'</b>"</label></text>
 <hbox homogeneous="true">
  <text><label>"'"$LOC_500B"' "</label></text>
 </hbox>
  <button>  
   <label>"Lucid Puppy '"$LOC_315"'"</label>                                             
   <input file>/root/.quickpet/icons/lupu.png</input>
   <action>LUPU_UPDATE</action>
  </button>'
########################################################################
MOREPETS='<hbox>
 <text><label>'"$LOC_601"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Vlc.png</input>
   <action>echo "Vlc" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_602"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/dia.png</input>
   <action>echo "Dia" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_603"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/cinelerra.png</input>
   <action>echo "Cinelerra" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_604"'</label></text>                        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/Java.png</input>
   <action>echo "jre" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_605"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/pdfedit.png</input>
   <action>echo "Pdfedit" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>
<hbox>
 <text><label>'"$LOC_606"'</label></text>        
  <button relief="2">                                              
   <input file>/root/.quickpet/icons/inkscape.png</input>
   <action>echo "Inkscape" > /tmp/thepet</action>
   <action>GETPET</action>
  </button>
</hbox>'
########################################################################
DRIVERS='<hbox homogeneous="true">
   <text><label>'"$LOC_390"'</label></text> 
 </hbox>
 <hbox homogeneous="true">
   <text use-markup="true"><label>"<i>'"$LOC_389"'</i>"</label></text> 
 </hbox>
 <hbox>  
 <text><label>'"$LOC_392vid"'</label></text>        
   <button relief="2" tooltip-text='\"$LOC_392ttvid\"'>     
     <input file>/root/.quickpet/icons/display.png</input>
     <action>graphics</action>    
   </button>
 </hbox>
 <hbox>  
 <text><label>'"$LOC_392a"'</label></text>        
   <button relief="2" tooltip-text='\"$LOC_392tt\"'>     
     <input file>/root/.quickpet/icons/nvidia.png</input>
     <action>NVIDIA</action>     
   </button>
 </hbox>
 <hbox>  
 <text><label>'"$LOC_392x"'</label></text>        
   <button relief="2">     
     <input file>/root/.quickpet/icons/xorg.png</input>
     <action>echo "Xorg_High" > /tmp/thepet</action>  
     <action>GETPET</action>  
   </button>
 </hbox>'