#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pfilesearch/func"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

PID=$$

-about)
	export pfilesearch_about="
<window title=\"pfilesearch - about\" icon-name=\"gtk-find\">
 <vbox>
  <notebook labels=\"About|License|Credits\">
   <vbox>
    <pixmap icon_size=\"6\"><input file stock=\"gtk-find\"></input></pixmap>
    <text use-markup=\"true\"><label>\"<b>pfilesearch $VERSION - File finder</b>\"</label></text>
    <text use-markup=\"true\"><label>Sigmund Berglund, Copyright 2007-2009</label></text>
    <text><label>\"\"</label></text>
     <button>
      <label>\"http://www.murga-linux.com/puppy/viewtopic.php?t=15136\"</label>
      <action>$BROWSER http:\/\/www.murga-linux.com\/puppy\/viewtopic.php?t=15136</action>
     </button>
   </vbox>
   <vbox>
    <text use-markup=\"true\"><label>\"pfilesearch is released under the <b>GNU General Public License</b> (GPL). You have the right to use and modify this software in any way you like, so long as any derivative works remain under a GPL license.\"</label></text>
    <text use-markup=\"true\"><label>\"This program is distributed in the hope that it will be useful, but <b>WITHOUT ANY WARRANTY</b>. See the GNU General Public License homepage for more details.\"</label></text>
    <hbox>
     <button>
      <label>\"http://www.gnu.org/licenses/\"</label>
      <action>$BROWSER http:\/\/www.gnu.org\/licenses\/</action>
     </button>
    </hbox>
   </vbox>
   <vbox>
    <edit><default>\"Translators:
French - Jean-Jacques Moulinier (esmourguit)
German - Thorsten Köbe (aragon)
Greece - (The Hamsters)
Italian - Angelo Gemmi
Japanese - Shigekazu Satoh (himajin)
Norwegian - Sigmund Berglund (zigbert)
Russian -  Valeriy Danilin
Spanish - Jacob S. Preciado (Proudog)

Others:
Disciple for contribution and bugfixing.
klhrevolutionist for ideas, code support and help with config file
Trapster for sed syntax.
...and more\"</default></edit>
   </vbox>
  </notebook>
  <hbox>
   <button>
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
   </button>
  </hbox>
 </vbox>
</window>"
	$GTKDIALOG --program pfilesearch_about --center
	;;
esac
