#!/bin/ash


[ "$HAVE_F4PUPPY5PROCESS" ] && return 0

# REM: debugging and logging related functions
#

# REM:


_say_session_leaders(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "^[DRSTWXZ]s") || match($1, "^[DRSTWXZ][NLl<]*s")) print}'
}

_say_high_priority(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "^[DRSTWXZ]<") || match($1, "^[DRSTWXZ][NLls]*<")) print}'
}

_say_low_priority(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "^[DRSTWXZ]N") || match($1, "^[DRSTWXZ][Lls<]*N")) print}'
}

_say_locked(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "^[DRSTWXZ]L") || match($1, "^[DRSTWXZ][Nls<]*L")) print}'
}

_say_multi_threaded(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "^[DRSTWXZ]l") || match($1, "^[DRSTWXZ][NLs<]*l")) print}'
}

_say_foreground(){
ps -A -o stat,tty,pid,args | awk '{if (match ($1, "+")) print}'
}




### END ###
  HAVE_F4PUPPY5PROCESS=1
_HAVE_F4PUPPY5PROCESS_=1
### END ###
