#!/bin/ash

[ "$HAVE_F4PUPPY5SECURITY" ] && return 0

# REM: SECURITY for to handle user permissions
#

# REM:

#============ Secure tests to filter out links =======================================
_stest_f()
{
test -e "$*" || return 2
test -L "$*" && return 3
test -f "$*" && return 0
return 1
}

#= readable to source
_stest_fr(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep '^\-r' && return 0
else
test -f "$*" -a -r "$*" && return 0
fi
test -f "$*" || return 4
return 1
}

#= writable to write to
_stest_fw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^\-.w' && return 0
else
test -f "$*" -a -w "$*" && return 0
fi
test -f "$*" || return 4
return 1
}

_stest_frw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^\-rw' && return 0
else
test -f "$*" -a -r "$*" -a -w "$*" && return 0
fi
test -f "$*" || return 4
return 1
}

#= file and xecutable
_stest_fx(){
test -e "$*" || return 2
test -L "$*" && return 3
test -f "$*" -a -x "$*" && return 0
test -f "$*" || return 4
return 1
}

#= file and has size
_tsest_fs(){
test -e "$*" || return 2
test -L "$*" && return 3
test -f "$*" -a -s "$*" && return 0
test -f "$*" || return 4
return 1
}

#= file readable and size
_stest_frs(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 [ "`ls -dl "$*" | grep '^\-r'`" -a -s "$*" ] && return 0
else
test -f "$*" -a -r "$*" -a -s "$*" && return 0
fi
test -f "$*" || return 4
return 1
}

_stest_d()
{
test -e "$*" || return 2
test -L "$*" && return 3
test -d "$*" && return 0
return 1
}

_stest_drwx()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^drwx' && return 0
else
test -d "$*" -a -r "$*" -a -w "$*" -a -x "$*" && return 0
fi
test -d "$*" || return 4

return 1
}

_stest_drx()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^dr.x' && return 0
else
test -d "$*" -a -r "$*" -a -x "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_dwx()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^d.wx' && return 0
else
test -d "$*" -a -w "$*" -a -x "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_drw()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^drw' && return 0
else
test -d "$*" -a -r "$*" -a -w "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_dr()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^dr' && return 0
else
test -d "$*" -a -r "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_dw()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^d.w' && return 0
else
test -d "$*" -a -w "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_dx()
{
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using ls -dl
if [ "`whoami`" = "root" ]; then
 ls -dl "$*" | grep $Q '^d..x' && return 0
else
 test -d "$*" -a -x "$*" && return 0
fi
test -d "$*" || return 4
return 1
}

_stest_p()
{
test -e "$*" || return 2
test -L "$*" && return 3
test -p "$*" && return 0
return 1
}

_stest_S()
{
test -e "$*" || return 2
test -L "$*" && return 3
test -S "$*" && return 0
return 1
}

_stest_c(){
test -e "$*" || return 2
test -L "$*" && return 3
test -c "$*" && return 0
return 1
}

_stest_crw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^crw' && return 0
else
test -c "$*" -a -r "$*" -a -w "$*" && return 0
fi
test -c "$*" || return 4
return 1
}

_stest_cr(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^cr' && return 0
else
test -c "$*" -a -r "$*" && return 0
fi
test -c "$*" || return 4
return 1
}

_stest_cw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^c.w' && return 0
else
test -c "$*" -a -w "$*" && return 0
fi
test -c "$*" || return 4
return 1
}


_stest_b(){
test -e "$*" || return 2
test -L "$*" && return 3
test -b "$*" && return 0
return 1
}

_stest_brw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^brw' && return 0
else
test -b "$*" -a -r "$*" -a -w "$*" && return 0
fi
test -b "$*" || return 4
return 1
}

_stest_br(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^br' && return 0
else
test -b "$*" -a -r "$*" && return 0
fi
test -b "$*" || return 4
return 1
}

_stest_bw(){
test -e "$*" || return 2
test -L "$*" && return 3

# REM: shell test ignores permissions for root somehow,
# so using stat -c %A
if [ "`whoami`" = "root" ]; then
 stat -c %A "$*" | grep $Q '^b.w' && return 0
else
test -b "$*" -a -w "$*" && return 0
fi
test -b "$*" || return 4
return 1
}


###END###
_HAVE_F4PUPPY5SECURITY_=1  ## WARN : DO NOT EXPORT !!
  HAVE_F4PUPPY5SECURITY=1
###END###
