#!/bin/ash

#v403 change desktop icon to unmounted status, called from pup_event_frontend_d, pmount...
icon_unmounted_func() {
#echo icon_unmounted_func $* >&2
 #passed params: drivename category  ex: sda1 usbdrv

 DRVICON="drive48.png" #default.
 case "$2" in "usbdrv") DRVICON="usbdrv48.png" ;;
                "card") DRVICON="card48.png"   ;;
              "floppy") DRVICON="floppy48.png" ;;
            "optical" ) DRVICON="optical48.png";;
 esac

# #find out if already done...
# if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
#  #GLOBLINES="`cat /root/.config/rox.sourceforge.net/ROX-Filer/globicons | tr '\n' '|' | sed -e 's%</rule>|%\n%g'`"
#  diPATTERN='/root/.pup_event/drive_'"${1}"'"'
#  #[ "`echo "$GLOBLINES" | grep "$diPATTERN" | grep "$DRVICON"`" ] && return 0
#  grep -A1 "$diPATTERN" /root/.config/rox.sourceforge.net/ROX-Filer/globicons | grep $Q "$DRVICON" && return 0
# fi
# #[ "`echo "${ATADRIVES}" | grep "${1}"`" ] || sleep 1 #110722 usb drive, LED light briefly flashes after unmounted, so wait a bit. ATADRIVES is in /etc/rc.d/PUPSTATE.

 DISP=${DISPLAY%.*}
 if test -f /etc/windowmanager.$DISP; then
   read CURRENTWM </etc/windowmanager.$DISP
  case $CURRENTWM in enlightenment_start) return 0;; esac
 fi

#echo 'rox -R..:'
 echo "<?xml version=\"1.0\"?>
<env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
 <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
  <SetIcon>
   <Path>/root/.pup_event/drive_${1}</Path>
   <Icon>/usr/local/lib/X11/pixmaps/${DRVICON}</Icon>
  </SetIcon>
 </env:Body>
</env:Envelope>"  | rox -R
#echo icon_unmounted_func END
}

icon_mounted_func() {
#echo icon_mounted_func $* >&2
 #passed params: drivename category  ex: sda1 usbdrv

 if /bin/df | grep -w "^/dev/$1" | awk '{print $NF}'  | grep $Q -E '^/initrd/|^/$' ;then
  #only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
  #also, full hd install has partition mntd on '/'.
  DRVICON="drive_mntd_boot48.png" #default.
  case "$2" in "usbdrv") DRVICON="usbdrv_mntd_boot48.png" ;;
                 "card") DRVICON="card_mntd_boot48.png"   ;;
               "floppy") DRVICON="floppy_mntd_boot48.png" ;;
              "optical") DRVICON="optical_mntd_boot48.png";;
  esac
 else
  DRVICON="drive_mntd48.png" #default.
  case "$2" in "usbdrv") DRVICON="usbdrv_mntd48.png" ;;
                 "card") DRVICON="card_mntd48.png"   ;;
               "floppy") DRVICON="floppy_mntd48.png" ;;
              "optical") DRVICON="optical_mntd48.png";;
  esac
 fi

 ##find out if already done...
 #if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
 # #GLOBLINES="`cat /root/.config/rox.sourceforge.net/ROX-Filer/globicons | tr '\n' '|' | sed -e 's%</rule>|%\n%g'`"
 # diPATTERN='/root/.pup_event/drive_'"${1}"'"'
 # #[ "`echo "$GLOBLINES" | grep "$diPATTERN" | grep "$DRVICON"`" ] && return 0
 # grep -A1 "$diPATTERN" /root/.config/rox.sourceforge.net/ROX-Filer/globicons | grep $Q "$DRVICON" && return 0
 ##fi

 DISP=${DISPLAY%.*}
 if test -f /etc/windowmanager.$DISP; then
   read CURRENTWM </etc/windowmanager.$DISP
  case $CURRENTWM in enlightenment_start) return 0;; esac
 fi

 echo "<?xml version=\"1.0\"?>
<env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
 <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
  <SetIcon>
   <Path>/root/.pup_event/drive_${1}</Path>
   <Icon>/usr/local/lib/X11/pixmaps/${DRVICON}</Icon>
  </SetIcon>
 </env:Body>
</env:Envelope>"  | rox -R
}


icon_mounted_boot() {
#echo icon_mounted_boot $* >&2
 #passed params: drivename category  ex: sda usbdrv

  #only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
  #also, full hd install has partition mntd on '/'.
  DRVICON="drive_mntd_boot48.png" #default.
  case "$2" in "usbdrv" ) DRVICON="usbdrv_mntd_boot48.png" ;;
                  "card") DRVICON="card_mntd_boot48.png"   ;;
                "floppy") DRVICON="floppy_mntd_boot48.png" ;;
               "optical") DRVICON="optical_mntd_boot48.png";;
  esac

 ##find out if already done...
 #if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
 # #GLOBLINES="`cat /root/.config/rox.sourceforge.net/ROX-Filer/globicons | tr '\n' '|' | sed -e 's%</rule>|%\n%g'`"
 # diPATTERN='/root/.pup_event/drive_'"${1}"'"'
 # #[ "`echo "$GLOBLINES" | grep "$diPATTERN" | grep "$DRVICON"`" ] && return 0
 # grep -A1 "$diPATTERN" /root/.config/rox.sourceforge.net/ROX-Filer/globicons | grep $Q "$DRVICON" && return 0
 #fi

 DISP=${DISPLAY%.*}
 if test -f /etc/windowmanager.$DISP; then
   read CURRENTWM </etc/windowmanager.$DISP
  case $CURRENTWM in enlightenment_start) return 0;; esac
 fi

 echo "<?xml version=\"1.0\"?>
<env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
 <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
  <SetIcon>
   <Path>/root/.pup_event/drive_${1}</Path>
   <Icon>/usr/local/lib/X11/pixmaps/${DRVICON}</Icon>
  </SetIcon>
 </env:Body>
</env:Envelope>"  | rox -R
}

icon_remove_func() {
 #passed param is drive icon to remove from desktop. ex: sda

 DISP=${DISPLAY%.*}
 if test -f /etc/windowmanager.$DISP; then
   read CURRENTWM </etc/windowmanager.$DISP
  case $CURRENTWM in enlightenment_start) return 0;; esac
 fi

 echo "<?xml version=\"1.0\"?>
<env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
 <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
  <UnsetIcon>
   <Path>/root/.pup_event/drive_${1}</Path>
  </UnsetIcon>
 </env:Body>
</env:Envelope>"  | rox -R
}
