#!/bin/ash

. /etc/rc.d/f4puppy5

 _choosemousefunc(){
 #originally in functions4puppy4
 #w468 called from xorgwizard.
 MOUSEINTRO="Only very old PCs may have a serial mouse.
These are recognised by the fairly large rectangular plug,
technically known as a DB9 or the even larger DB25
(where the 9 or 25 refers to the number of pins in the plug).
Press the UP and DOWN arrow keys to choose your mouse type,
then press the ENTER key:"
 #DETECTEDMOUSEDEV="`cat /etc/mousedevice`"
 read DETECTEDMOUSEDEV </etc/mousedevice
 case $DETECTEDMOUSEDEV in
  ttyS*)
   MOUSEMENU1a='serial';   MOUSEMENU1b='(mouse in very old computers)'
   MOUSEMENU2a='usb/ps-2'; MOUSEMENU2b='(mouse or touchpad in all modern computers)'
  ;;
  *)
   MOUSEMENU1a='usb/ps-2'; MOUSEMENU1b='(mouse or touchpad in all modern computers)'
   MOUSEMENU2a='serial';   MOUSEMENU2b='(mouse in very old computers)'
  ;;
 esac
 dialog --no-cancel --menu "${MOUSEINTRO}\n\n
Please choose mouse type..." 0 0 0 "$MOUSEMENU1a" "$MOUSEMENU1b" "$MOUSEMENU2a" "$MOUSEMENU2b" 2> /tmp/testmsx
 [ $? -ne 0 ] && return 1
 CHOSENMOUSETYPE="`cat /tmp/testmsx`"
 case $CHOSENMOUSETYPE in
 serial)
  dialog --no-cancel --menu "Serial port mouse plugged into...\nUse UP/DOWN ARROW keys, ENTER key to finish" 0 0 0 ttyS0 "COM1 (most likely)" ttyS1 COM2 ttyS2 COM3 ttyS3 COM4 2> /tmp/testmsx
  [ $? -ne 0 ] && return 1
  MOUSEDEV="`cat /tmp/testmsx`"
  modprobe sermouse
  ln -snf $MOUSEDEV /dev/mouse
  echo "$MOUSEDEV" > /etc/mousedevice
  cat /etc/X11/xorg.conf | sed -e 's/\W\+Option\W\+"Protocol"\W\+"\(\(\w\+\/\w\+\)\|\(\w\+\)\)\W\+#mouse0protocol/  Option      "Protocol" "Microsoft" #mouse0protocol/' > /tmp/xorg.conf.tmp2
 ;;
 *)
  echo "input/mice" > /etc/mousedevice
  ln -snf input/mice /dev/mouse
  cat /etc/X11/xorg.conf | sed -e 's/\W\+Option\W\+"Protocol"\W\+"\(\(\w\+\/\w\+\)\|\(\w\+\)\)\W\+#mouse0protocol/  Option      "Protocol" "IMPS\/2" #mouse0protocol/' > /tmp/xorg.conf.tmp2
 ;;
 esac
 _sync
 cp -f /tmp/xorg.conf.tmp2 /etc/X11/xorg.conf
 [ "$DEBUG" ] || rm -f /tmp/xorg.conf.tmp2
} #choosemousefunc()
