#!/bin/sh
#the way this file is written, it is best to start Icewm with just "icewm"

#exit 0 # exit because while still in /root/Startup and porting its code to /usr/sbin/delayedrun
        #comment it now since .icewm/toolbar contains
        # prog "Refresh Tray Icons" mini-turn /root/.icewm/z-start-icetrayapps

DIR=$HOME/icewm
CURWM=`cat /etc/windowmanager|head -c5` #this is a workaround if icewm was started with "icewm-session"
if [[ "$CURWM" != icewm ]];then exit 0
fi

. $HOME/.icewm/theme
THEMEDIR="/usr/share/icewm/themes"
. ${THEMEDIR}/${Theme}

NUMCOLOR=`echo $ColorNormalTaskBarApp|grep "rgb:"`
if [[ $NUMCOLOR = "" ]];then BG=""
        else PRE_BG=`echo $ColorNormalTaskBarApp|cut -d ':' -f2|sed 's%/%%g'`
                 BG="#${PRE_BG}"
fi

if [[ "$Theme" = "GoldenSand/default.theme" ]];then BG="#C6AD73"
fi

if [ "$BG" = "" ];then OPT_ARG=""
        else OPT_ARG="-bg ${BG}"
fi

echo "$OPT_ARG"

#let's get started #battery and numlockx usually start ok, so they are omitted
killall icewmtray
icewmtray &
/root/Startup/powerapplet_tray &
sleep 1

FWALL=`ls /root/Startup|grep firewall`
if [[ -x /root/Startup/${FWALL} ]];then exec $FWALL &
        sleep 3
fi

killall retrovol
if [ "$OPTARG" = "" ];then retrovol -hide &
                else retrovol $OPT_ARG -hide &
fi
sleep 2

killall blinky
$DIR/blinky $OPT_ARG &
sleep 2

$DIR/freememapplet_tray &

exit
###END###

