#! /bin/bash
echo 0 > $WORKDIR/splash
echo 'Please wait ...' > $WORKDIR/progresstext
export pmusic_splash='
<window title="Pmusic" icon-name="gtk-media-stop">
<vbox>
 <frame>
  '"$SPLASH
  <text><input file>$WORKDIR/splashtext</input></text>
 </frame>
 <progressbar>
  <input>"'while [ "$I" != "100" ]; do I=`cat '$WORKDIR'/splash`; J=`cat '$WORKDIR'/progresstext`; echo $I; echo "$J (${I}%)"; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
</vbox></window>'
$GTKDIALOG -p pmusic_splash --center

