#! /bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_splash_progress"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pmusic/box_splash_progress"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#
echo 0 > $WORKDIR/splash
echo 'Please wait ...' > $WORKDIR/progresstext
export pmusic_splash='
<window title="Pmusic" icon-name="gtk-media-stop">
<vbox>
 <frame>
  '"$SPLASH
  <text><input file>$WORKDIR/splashtext</input></text>
 </frame>
 <progressbar>
  <input>"'while [ "$I" != "100" ]; do I=`cat '$WORKDIR'/splash`; J=`cat '$WORKDIR'/progresstext`; echo $I; echo "$J (${I}%)"; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
</vbox></window>'
$GTKDIALOG -p pmusic_splash --center

# Very End of this file 'usr/local/pmusic/box_splash_progress' #
###END###
