#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_input"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pmusic/box_input"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#
if [ "`which gtkdialog3 2> /dev/null`" ]; then GTKDIALOG="gtkdialog3"; else GTKDIALOG="gtkdialog"; fi #puppy specific
if [ -z "$FRAME" ]; then FRAME=" "; fi

export inputbox="
<window title=\"Pmusic\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <entry activates-default=\"true\">
    <variable>INPUT</variable>
    <input>echo \"${DEFAULT}\"</input>
   </entry>
  </frame>
  <hbox>
   <button>
    <input file icon=\"gtk-cancel\">
    </input><label>$LOC_CANCEL</label>
    <action type=\"exit\">cancel</action>
   </button>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
    <action type=\"exit\">ok</action>
   </button>
  </hbox>
 </vbox>
</window>"
for STATEMENTS in $($GTKDIALOG -p inputbox --center); do
	eval $STATEMENTS
done
TXT1=""; DEFAULT=""; FRAME=""; IMG="" #reset to avoid alien text in next box
# Very End of this file 'usr/local/pmusic/box_input' #
###END###
