#! /bin/bash
export pmusic_splash='
<window title="Pmusic">
<vbox>
 <frame>
  '"$SPLASH
  <text><input file>$WORKDIR/splashtext</input></text>
 </frame>
 <progressbar>
  <input>"'while [ "$I" != "100" ]; do I=`cat '"$WORKDIR"'/pmusic-splash`; echo $I; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
</vbox></window>'
$GTKDIALOG -p pmusic_splash --center

