#!/bin/bash
IFS=$'\n'

TMP="`ps`"
for I in `echo "$TMP" | grep "aplay" | awk '{print $1}'`; do kill -9 $I 2> /dev/null; done
for I in `echo "$TMP" | grep "ffmpeg" | awk '{print $1}'`; do kill -9 $I 2> /dev/null; done
for I in `echo "$TMP" | grep 'func_player -playing' | awk '{print $1}'`; do kill -9 $I 2> /dev/null; done
killall cdda2wav