#!/bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_func_store_playlist"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pmusic/func_store_playlist"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#Pmusic
#Copyright 2008,2009,2010
#Sigmund Berglund
IFS=$'\n'

export WORKDIR=$HOME/.pmusic/tmp
mkdir $HOME/.pmusic/storage_playlist/ > /dev/null 2>&1
DATO="`date +%Y\_%m\_%d\_\(%H:%M:%S\)`"

#check if list is not empty
if [ -s $WORKDIR/playlist ]; then
        ls -1 $HOME/.pmusic/storage_playlist/ > $WORKDIR/tmp
        while read I; do
                [ ! "`diff $HOME/.pmusic/storage_playlist/"$I" $WORKDIR/playlist`" ] && exit
        done < $WORKDIR/tmp
        #---
        cp $WORKDIR/playlist $HOME/.pmusic/storage_playlist/"Playlist_""$DATO"
        echo "Playlist_""$DATO" > $WORKDIR/PLAYLIST_NAME
        #keep only the 30 newest in storage
        ls -1 $HOME/.pmusic/storage_playlist/ | tail -n 30 > $WORKDIR/tmp_ls
        ls -1 $HOME/.pmusic/storage_playlist/ > $WORKDIR/tmp_ls2
        while read I; do
                [ ! "`grep -F "$I" $WORKDIR/tmp_ls`" ] && rm $HOME/.pmusic/storage_playlist/"$I"
        done < $WORKDIR/tmp_ls2
fi
exit 0

# Very End of this file 'usr/local/pmusic/func_store_playlist' #
###END###
