#!/bin/bash
GUI_MENU_FILE="
<menu>
 <menuitem icon=\"gtk-new\">
  <label>$LOC111</label>
  <action>$APPDIR/func_store_playlist</action>
  <action>$APPDIR/func -new</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-open\">
  <label>$LOC101...</label>
  <action>. $APPDIR/func -show_add_window -browse</action>
  <action type=\"launch\">Pmusic_sources</action>
  <action>Refresh:INDEX</action>
 </menuitem>
 <menuitem icon=\"gtk-cdrom\">
  <label>$LOC105</label>
  <action>$APPDIR/func -play_cd</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-save\">
  <label>$LOC102...</label>
  <action>. $APPDIR/func -save</action>
 </menuitem>
 <menuitem icon=\"gtk-save-as\">
  <label>$LOC106...</label>
  <action>$APPDIR/func -copy_files &</action>
 </menuitem>
 <separator></separator>
 <menuitem icon=\"gtk-refresh\">
  <label>$LOC104...</label>
  <action>$APPDIR/func -update_index &</action>
 </menuitem>
 <menuitem icon=\"gtk-about\">
  <label>$LOC241...</label>
  <action>. $APPDIR/func -manage_bookmarks &</action>
 </menuitem>
 <menuitem icon=\"gtk-preferences\">
  <label>$LOC103...</label>
  <action>$APPDIR/func -preferences &</action>
 </menuitem>
 <separator></separator>
 <menuitem icon=\"gtk-quit\">
  <label>$LOC_QUIT</label>
  <action>$APPDIR/func -write_config</action>
  <action>EXIT:quit</action>
 </menuitem>
 <label>$LOC100</label>
</menu>"

GUI_MENU_SOURCES="
<menu>
 <menuitem>
  <label>$LOC223</label>
  <action>. $APPDIR/func -index_songs</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC224</label>
  <action>. $APPDIR/func -index_playlists</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC222</label>
  <action>. $APPDIR/func -radio</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>CD</label>
  <action>$APPDIR/func -read_cd &</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC227</label>
  <action>. $APPDIR/func -show_bookmarks</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC225</label>
  <action>. $APPDIR/func -index_recent</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC226</label>
  <action>. $APPDIR/func -index_most_played</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>

 <separator></separator>

 <menuitem icon=\"gtk-add\">
  <label>$LOC232</label>
  <action>$APPDIR/func -add_random</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-add\">
  <label>$LOC230</label>
  <action>$APPDIR/func -add_all</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>

 <separator></separator>

  <menuitem icon=\"gtk-sort-ascending\">
  <label>$LOC233 $LOC236 $LOC237</label>
  <action>$APPDIR/func -index_sort_file</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_TITLE - $LOC234</label>
  <action>$APPDIR/func -index_sort_title</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_ARTIST - $LOC234</label>
  <action>$APPDIR/func -index_sort_artist</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_ALBUM - $LOC234</label>
  <action>$APPDIR/func -index_sort_album</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_TRACK - $LOC234</label>
  <action>$APPDIR/func -index_sort_track</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_YEAR - $LOC234</label>
  <action>$APPDIR/func -index_sort_year</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem>
  <label>$LOC233 $LOC236 $LOC_GENRE - $LOC234</label>
  <action>$APPDIR/func -index_sort_genre</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <label>$LOC170</label>
</menu>"

GUI_MENU_PLAYLIST="
<menu>
 <menuitem icon=\"gtk-edit\">
  <label>$LOC131</label>
  <action>$APPDIR/func -edit_tags</action>
 </menuitem>
 <menuitem icon=\"gtk-find\">
  <label>$LOC135</label>
  <action>$APPDIR/func -search_for_song_in_playlists</action>
 </menuitem>
 <separator></separator>
 <menuitem icon=\"gtk-convert\">
  <label>$LOC132...</label>
  <action>$APPDIR/func -rename</action>
  <action>Refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-copy\">
  <label>$LOC133...</label>
  <action>$APPDIR/func -copy</action>
  <action>Refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-delete\">
  <label>$LOC134...</label>
  <action>$APPDIR/func -delete</action>
  <action>Refresh:PLAYLIST</action>
 </menuitem>
 <separator></separator>
 <menuitem>
  <label>$LOC120</label>
  <action type=\"launch\">Pmusic_playlist_multiple</action>
 </menuitem>
 <separator></separator>
 <menuitem icon=\"gtk-undo\">
  <label>$LOC118</label>
  <action>. $APPDIR/func -undo</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <menuitem icon=\"gtk-redo\">
  <label>$LOC119</label>
  <action>. $APPDIR/func -redo</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <separator></separator>
 <menuitem icon=\"gtk-about\">
  <label>$LOC136</label>
  <action>$APPDIR/func -bookmark_playing</action>
  <action>. $APPDIR/func -show_bookmarks</action>
  <action>clear:INDEX</action>
  <action>refresh:INDEX</action>
 </menuitem>
 <menuitem icon=\"gtk-remove\">
  <label>$LOC113</label>
  <action>. $APPDIR/func -remove_from_list -message</action>
  <action>refresh:PLAYLIST</action>
 </menuitem>
 <label>$LOC110</label>
</menu>"

#include menuitems for related apps if exist
echo -e "\c" > $WORKDIR/plugins
type ppg-gui.sh > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-id3\"><label>Podcast-grabber - $LOC149...</label><action>$APPDIR/func -plugins podcast-grabber</action></menuitem>" >> $WORKDIR/plugins
type pmetatagger > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-id3\"><label>Pmetatagger - $LOC141...</label><action>$APPDIR/func -plugins pmetatagger</action></menuitem>" >> $WORKDIR/plugins
type ripoff > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-cdrom\"><label>Ripoff - $LOC146...</label><action>$APPDIR/func -plugins ripoff</action></menuitem>" >> $WORKDIR/plugins
type asunder > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-cdrom\"><label>Asunder - $LOC146...</label><action>$APPDIR/func -plugins asunder</action></menuitem>" >> $WORKDIR/plugins
type alsamixer > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-mixer\"><label>Alsamixer - $LOC147...</label><action>$APPDIR/func -plugins alsamixer</action></menuitem>" >> $WORKDIR/plugins
type rox > /dev/null 2>&1 && echo "<menuitem icon=\"gtk-open\"><label>Rox - $LOC1410...</label><action>$APPDIR/func -show_location</action></menuitem>" >> $WORKDIR/plugins
PLUGINS="`cat $WORKDIR/plugins`"

GUI_MENU_TOOLS="
<menu>
 <menuitem icon=\"gtk-bold\">
  <label>$LOC144...</label>
  <action>$APPDIR/func_lyrics -gui &</action>
 </menuitem>
 <menuitem>
  <label>$LOC148...</label>
  <action>. $APPDIR/func_mixer -get_levels</action>
  <action>$APPDIR/func_mixer -gui &</action>
 </menuitem>
 <separator></separator>
 $PLUGINS
 <separator></separator>
 <menuitem>
  <label>$LOC155...</label>
  <action>$APPDIR/func_player -jump_to</action>
 </menuitem>
 <menuitem>
  <label>$LOC159...</label>
  <action>$APPDIR/func -calc_length</action>
 </menuitem>
 <menuitem>
  <label>$LOC158</label>
  <action>$APPDIR/func -time_format</action>
 </menuitem>
 <label>$LOC140</label>
</menu>"

GUI_MENU_PLAY="
<menu>
 <menuitem>
  <label>$LOC151</label>
  <action>$APPDIR/func_player -play</action>
 </menuitem>
 <menuitem>
  <label>$LOC152</label>
  <action>$APPDIR/func_player -stop</action>
 </menuitem>
 <menuitem>
  <label>$LOC153</label>
  <action>$APPDIR/func_player -next</action>
 </menuitem>
 <menuitem>
  <label>$LOC154</label>
  <action>$APPDIR/func_player -back</action>
 </menuitem>
 <separator></separator>
 <menuitem>
  <label>$LOC156</label>
  <action>$APPDIR/func_player -forward</action>
 </menuitem>
 <menuitem>
  <label>$LOC157</label>
  <action>$APPDIR/func_player -rewind</action>
 </menuitem>
 <label>$LOC150</label>
</menu>"

ITEMS=`ls "$APPDIR"/presets | awk '{print "<menuitem><label>"$1"</label><action>. $APPDIR/func -update_playlist</action><action>pmusic -p "$1"</action></menuitem>"}'`

GUI_MENU_WINDOW="
<menu>
 $ITEMS
 <label>$LOC180</label>
</menu>"

GUI_MENU_HELP="
<menu>
 <menuitem icon=\"gtk-about\">
  <label>$LOC191...</label>
  <action>$APPDIR/func -about &</action>
 </menuitem>
 <menuitem icon=\"gtk-help\">
  <label>$LOC192...</label>
  <action>$APPDIR/func -faq &</action>
 </menuitem>
 <label>$LOC190</label>
</menu>"

GUI_MENU="
<menubar>
 $GUI_MENU_FILE
 $GUI_MENU_SOURCES
 $GUI_MENU_PLAYLIST
 $GUI_MENU_TOOLS
 $GUI_MENU_PLAY
 $GUI_MENU_WINDOW
 $GUI_MENU_HELP
</menubar>"
# Very End of this file 'usr/local/pmusic/gui_menu' #
###END###
