#!/bin/bash

#define active mixer level
. $APPDIR/func_mixer -get_levels

if [ -f "$APPDIR/themes/$THEME/arrow_left.png" ]; then
	ICON_ARROW_LEFT="<input file>$APPDIR/themes/$THEME/arrow_left.png</input>"
	ICON_ARROW_RIGHT="<input file>$APPDIR/themes/$THEME/arrow_right.png</input>"
else
	ICON_ARROW_LEFT="<input file stock=\"gtk-go-back\"></input>"
	ICON_ARROW_RIGHT="<input file stock=\"gtk-go-forward\"></input>"
fi

GUI_VOLUME="
<vbox>
 <hbox>
  <button relief=\"2\">
   $ICON_ARROW_LEFT
   <action>$APPDIR/func_mixer -down_VOL_L</action>
   <action>refresh:VOL_L</action>
   <action>refresh:VOL_R</action>
  </button>
  <text width-request=\"50\">
   <input>cat $WORKDIR/VOL_L</input>
   <variable>VOL_L</variable>
  </text>
  <button relief=\"2\">
   $ICON_ARROW_RIGHT
   <action>$APPDIR/func_mixer -up_VOL_L</action>
   <action>refresh:VOL_L</action>
   <action>refresh:VOL_R</action>
  </button>
  <text width-request=\"50\"><label>$LOC431</label></text>
 </hbox>
 <hbox>
  <button relief=\"2\">
   $ICON_ARROW_LEFT
   <action>$APPDIR/func_mixer -down_VOL_R</action>
   <action>refresh:VOL_L</action>
   <action>refresh:VOL_R</action>
  </button>
  <text width-request=\"50\">
   <input>cat $WORKDIR/VOL_R</input>
   <variable>VOL_R</variable>
  </text>
  <button relief=\"2\">
   $ICON_ARROW_RIGHT
   <action>$APPDIR/func_mixer -up_VOL_R</action>
   <action>refresh:VOL_L</action>
   <action>refresh:VOL_R</action>
  </button>
  <text width-request=\"50\"><label>$LOC432</label></text>
 </hbox>
</vbox>"

GUI_BUTTON_MUTE="
<button tooltip-text=\" $LOC405 \">
 <input file stock=\"gtk-stop\"></input>
 <action>. $APPDIR/func_mixer -mute</action>
</button>"

GUI_EQUALIZER="
<vbox>
 <hbox>
  <text><label>\"  $LOC434\"</label><visible>$EQUALIZER_VISIBLE</visible></text>
  <button relief=\"2\">
   $ICON_ARROW_LEFT
   <visible>$EQUALIZER_VISIBLE</visible>
   <action>$APPDIR/func_mixer -down_TREBLE</action>
   <action>refresh:TREBLE</action>
  </button>
  <text width-request=\"50\">
   <input>cat $WORKDIR/TREBLE</input>
   <variable>TREBLE</variable>
   <visible>$EQUALIZER_VISIBLE</visible>
  </text>
  <button relief=\"2\">
   $ICON_ARROW_RIGHT
   <visible>$EQUALIZER_VISIBLE</visible>
   <action>$APPDIR/func_mixer -up_TREBLE</action>
   <action>refresh:VOL_TREBLE</action>
  </button>
 </hbox>
 <hbox>
  <text><label>\"  $LOC433\"</label><visible>$EQUALIZER_VISIBLE</visible></text>
  <button relief=\"2\">
   $ICON_ARROW_LEFT
   <visible>$EQUALIZER_VISIBLE</visible>
   <action>$APPDIR/func_mixer -down_BASS</action>
   <action>refresh:BASS</action>
  </button>
  <text width-request=\"50\">
   <input>cat $WORKDIR/BASS</input>
   <variable>BASS</variable>
   <visible>$EQUALIZER_VISIBLE</visible>
  </text>
  <button relief=\"2\">
   $ICON_ARROW_RIGHT
   <visible>$EQUALIZER_VISIBLE</visible>
   <action>$APPDIR/func_mixer -up_BASS</action>
   <action>refresh:BASS</action>
  </button>
 </hbox>
</vbox>"

GUI_MIXER="
<hbox homogeneous=\"true\">
 <vbox>
  <hbox>
   $GUI_VOLUME
   <vbox homogeneous=\"true\">
    $GUI_BUTTON_MUTE
   </vbox>
   $GUI_EQUALIZER
  </hbox>
 </vbox>
</hbox>"


# Very End of this file 'usr/local/pmusic/gui_mixer' #
###END###
