#! /bin/bash
export pcd_splash='
<window title="pcd">
<vbox>
 <frame>
  <pixmap icon_size="6"><input file stock="gtk-cdrom"></input></pixmap>
  <text use-markup="true"><label>"<b>pCD - CD-audio player</b>"</label></text>
  <text><input file>'"$WORKDIR/pcd-splashtext</input></text>
 </frame>
 <progressbar>
  <label>Sigmund Berglund,   GPL 2009</label>
  <input>"'while [ "$I" != "100" ]; do I=`cat '"$WORKDIR"'/pcd-splash`; echo $I; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
</vbox></window>'
gtkdialog3 --program=pcd_splash --center

