#! /bin/bash
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_splash"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pcd/box_splash"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
export pcd_splash='
<window title="pcd">
<vbox>
 <frame>
  <pixmap icon_size="6"><input file stock="gtk-cdrom"></input></pixmap>
  <text use-markup="true"><label>"<b>pCD - CD-audio player</b>"</label></text>
  <text><input file>'"$WORKDIR/pcd-splashtext</input></text>
 </frame>
 <progressbar>
  <label>Sigmund Berglund,   GPL 2009</label>
  <input>"'while [ "$I" != "100" ]; do I=`cat '"$WORKDIR"'/pcd-splash`; echo $I; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
</vbox></window>'
gtkdialog3 --program=pcd_splash --center

