#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_pstreamvid"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pstreamvid/pstreamvid"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#
#pstreamvid
#Trio Tjandradjaja - GPL 2009

WIDGET_DIR="`dirname $0`"
[ "$WIDGET_DIR" = "." ] && WIDGET_DIR="`pwd`"
export WIDGET_DIR="$WIDGET_DIR"
#WIDGET_DIR="/usr/local/pstreamvid/"
	
ls -1 /$WIDGET_DIR/channels/ | awk '{print $1}' > /$WIDGET_DIR/tmp/channels

if [ "`cat /usr/local/pstreamvid/tmp/fullscreen`" = "on" ] ; then
RADIOBUTTONS="<radiobutton>
		<label>ON</label>
		<variable>ON</variable>
		<action>echo "on" > /usr/local/pstreamvid/tmp/fullscreen</action>
		</radiobutton>
		<radiobutton>
		<label>OFF</label>
		<variable>OFF</variable>
		<action>echo "off" > /usr/local/pstreamvid/tmp/fullscreen</action>
		</radiobutton>"
else
RADIOBUTTONS="<radiobutton>
		<label>OFF</label>
		<variable>OFF</variable>
		<action>echo "off" > /usr/local/pstreamvid/tmp/fullscreen</action>
		</radiobutton>
		<radiobutton>
		<label>ON</label>
		<variable>ON</variable>
		<action>echo "on" > /usr/local/pstreamvid/tmp/fullscreen</action>
		</radiobutton>"
fi

#this variable contains the actual gtkdialog code
export Pstreamvid="	
<window title=\"Pstreamvid 1.3\">
<vbox>
 <hbox>
 <text><label>\"  Streaming Video Controller       \"</label></text>
 <pixmap><input file>/usr/local/lib/X11/pixmaps/multimedia24.png</input></pixmap>
 </hbox>
  <frame Choose Your Channel>
   <tree>
    <label>Available Channels</label>
    <height>250</height><width>200</width>
	<variable>CHANNEL</variable>	
    <input>cat /$WIDGET_DIR/tmp/channels</input>
   </tree>
  </frame>
  
  <hbox><text><label>\"Fullscreen Mode      \"</label></text>$RADIOBUTTONS</hbox>
  <notebook labels=\"gXine|Mplayer\">
  
  <frame Press F key to toggle full screen>
  <vbox>
  <hbox>
  <button>
    <input file icon=\"gtk-delete\"></input>
    <label>Remove</label>
    <action>. $WIDGET_DIR/functions -remove</action>
  	<action>refresh:CHANNEL</action>
   </button>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-stop.xpm</input>
    <label>Off</label>
    <action>. $WIDGET_DIR/functions -off &</action>
   </button>
   <button>
    <input file icon=\"gtk-go-forward-ltr\"></input>
    <label>Play </label>
    <action>. $WIDGET_DIR/functions -apply &</action>
   </button>
   <text><label>\"\"</label></text>
   </hbox>
   </vbox>
   </frame>
  
  <frame Press F key to toggle full screen> 
   <vbox>
   <hbox>
  <button>
    <input file icon=\"gtk-delete\"></input>
    <label>Remove</label>
    <action>. $WIDGET_DIR/functions -remove</action>
  	<action>refresh:CHANNEL</action>
   </button>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-stop.xpm</input>
    <label>Off</label>
    <action>. $WIDGET_DIR/functions -offmplayer &</action>
   </button>
   <button>
    <input file icon=\"gtk-go-forward-ltr\"></input>
    <label>Play </label>
    <action>. $WIDGET_DIR/functions -applymplayer &</action>
   </button>
   <text><label>\"\"</label></text>
   </hbox>
   </vbox>
   </frame>
   
   </notebook>
   
   
   <frame Add New Channel>
     <hbox>
       <text><label>Name</label></text>
       <entry max_length=\"25\">
       <variable>NAME</variable>
	   <input>echo 'Please type channel name'</input>
       </entry>
  </hbox>
  <hbox>
       <text><label>URL</label></text>
	   <text><label>\" \"</label></text>
       <entry max_length=\"1000\">
       <variable>URL</variable>
	   <input>echo 'Please copy & paste URL'</input>
       </entry>
  </hbox>
  <hbox>
     <button>	
    <input file icon=\"gtk-quit\"></input>
    <label>Quit</label>
    
   </button>
   <button>
    <input file icon=\"gtk-add\"></input>
    <label>Add Channel</label>
    <action>. $WIDGET_DIR/functions -add_channel</action>
	<action>refresh:CHANNEL</action>
	<action>refresh:NAME</action>
	<action>refresh:URL</action>
   </button>
   <text><label>\"     \"</label></text>
   </hbox>
  </frame>
 </vbox>
</window>"

gtkdialog3 --program=Pstreamvid --center

unset Pstreamvid

#clear
exit 0
