#!/bin/bash
#Pmusic
#version=2.2.2
#language=en_US:english
#translator=native

# |==================================|
# | <b>text</b>            Bold text |
# | \n                      New line |
# |==================================|

set -a

LOC_ADVANCED="Advanced"
LOC_ALBUM="Album"
LOC_APPLY="Apply"
LOC_ARTIST="Artist"
LOC_BALANCE="Balance"
LOC_BROWSE="Browse"
LOC_CANCEL="Cancel"
LOC_COUNTRY="Country"
LOC_DOWN="down"
LOC_EQUALIZER="Equalizer"
LOC_ERROR="Error"
LOC_FILENAME="Filename"
LOC_GENRE="Genre"
LOC_INFO="Info"
LOC_INSTALL="Install"
LOC_LEFT="left"
LOC_LYRICS="Lyrics"
LOC_MISC="Misc"
LOC_NO="No"
LOC_OK="Ok"
LOC_PATH="Path"
LOC_PLAY="Play"
LOC_QUIT="Quit"
LOC_REMOVE="Remove"
LOC_RENAME="Rename"
LOC_RIGHT="right"
LOC_SEARCH="Search"
LOC_SIZE="Size"
LOC_TITLE="Title"
LOC_TRACK="Track"
LOC_UP="up"
LOC_VIEW="View"
LOC_VOLUME="Volume"
LOC_WARNING="Warning"
LOC_YEAR="Year"
LOC_YES="Yes"


#Menu
LOC100="File"
 LOC101="Open - Music sources"
 LOC102="Save playlist"
 LOC103="Preferences"
 LOC104="My Music manager"
 LOC105="Play CD-audio"
 LOC106="Radio manager"
 LOC107="Podcast manager"
 LOC108="Eject CD"
 LOC109="Bookmark manager"
 LOC1010="WebMusic manager"
LOC110="Playlist"
 LOC111="New playlist"
 LOC114="Copy / Convert / Rip / Record"
 LOC115="Burn tracks"
 LOC116="Tag all tracks in list"
 LOC118="Go back in playlist history"
 LOC119="Go forward in playlist history"
 LOC131="Track info"
 LOC132="Rename source file"
 LOC133="Copy source file"
 LOC134="Delete source file"
 LOC136="Remove from playlist (mid-button)"
 LOC137="Rename playlists"
 LOC138="Show location"
LOC140="Track"
 LOC141="Track info"
 LOC142="Bookmark playing track"
 LOC151="Pause"
 LOC152="Stop"
 LOC153="Next track"
 LOC154="Previous track"
 LOC155="Jump to time" #time
LOC160="Sort"
LOC170="Music-sources"
LOC172="Overview"
LOC175="List"
LOC180="View"
 LOC181="Now Playing"
LOC190="Help"
 LOC191="About"
 LOC192="Frequently asked questions"
 LOC195="Dependency check"

#main window
LOC202="Buffering...Please wait"
LOC203="No connection"
LOC204="Corrupted file"
LOC205="Playback error"
LOC207="Unknown format"

#right-click menu
LOC210="Rate"

#Add
LOC220="Add"
LOC221="Web Music"
LOC222="Radio"
LOC223="Tracks"
LOC224="Collections"
LOC225="Recent played"
LOC226="Rating"
LOC227="Bookmarks"
LOC228="My Music"
LOC230="Add all"
LOC232="Add random"
LOC233="Sort"
LOC236="by" #sort BY filename/artist....
LOC237="File/address"
LOC238="Files"
LOC240="Bookmark source content"
LOC246="Add new track to the end of playlist"
LOC247="Add new track right below the playing track"

#ID3
LOC251="Advanced tagging

For advanced tagging you can use commands instead of
static text in the fields. This is very useful to track-titles
which almost never will be equal to another one. Some examples:

Filename is 'artist - title.mp3'. Command to grab title will be:
exe:echo 'FILENAME' | awk -F ' - ' '{print \\\$2}'

Album might be the name of the directory:
exe:echo 'DIRNAME'

Track-title in an e-book could be named like this:
exe:echo 'Mybook - Track COUNT'

And then the rules:
- Line must start with exe:
- Builtin variables are FILENAME, DIRNAME and COUNT
- Never use \"
- Place a \ in front of $"

LOC252="Clear tags"
LOC253="Comment"
LOC255="No matches! Be aware that this search ONLY includes collections (playlists) that are indexed."
LOC256="Save tags"
LOC258="Note that clearing tag means to add a space to the tag"
LOC259="This will edit the ID3 information of <b>ALL</b> tracks in the shown list. Untouched tags will NOT be removed. This means you can add one of the tags to all your files without removing the others."

#Preferences
LOC260="General"
LOC261="Playlist"
LOC262="Theme"
LOC263="Options"
LOC264="Give Pmusic higher CPU-priority (to avoid stutter)"
LOC265="Convert _underscores_ to blank"
LOC266="Convert %20 to blank"
LOC267="Window preset"
LOC268="Set name of multiple playlists"
LOC270="Language"
LOC271="Gap between tracks (in seconds)"
LOC272="Speaker channel"
LOC273="Playback"
LOC275="Show tooltips"
LOC279="Show icon in tray"
LOC800="CD device"
LOC801="Sound card"
LOC802="Auto is the recommended choice , but there are 2
reasons for setting your soundcard:
<b>1)</b> If there is installed more than 1 card you might
want to define which one to use.
<b>2)</b> If you struggles with bad sound quality, defining
your card could improve playback.

NOTE!
By setting the souncard you also bound the alsa driver to
Pmusic. This means other programs won't play audio as long
as Pmusic is active. On the other hand, <b>Pmusic won't
play if sound driver is in use by other program.</b>"
LOC807="Edit manually"
LOC808="Default file-browser path"
LOC811="Default search sources"
LOC812="Files in defined path(s) - Slower."

LOC830="Max NEW podcasts to download from a url"
LOC831="Podcast save directory"
LOC840="Meta-info"
LOC841="Use meta tags (if present) when adding track to playlist"
LOC842="Prefer meta info (over meta tags) from imported m3u playlist"
LOC843="Download album art for playing track"
LOC844="Auto-load meta information in Souce-window (if not already indexed)"
LOC845="Do load meta-tags of the first number of tracks"

#Save
LOC281="File"
LOC282="Include Path"
LOC283="Without paths, the definition is relative, and the playlist will work even if you move your music to another location. The downside is that the playlist must be in the same directory as the songs."
LOC284="Bookmark playlist"
LOC285="Make saved playlist available when you choose 'Bookmarks' from Music sources."

#Copy
LOC289="Burn tracks"
LOC290="Export"
LOC291="Target directory"
LOC292="Add Numbering to keep sort order"
LOC293="Audio format"
LOC294="Bitrate (bits/sec)"
LOC295="Samplerate (hz)"
LOC296="Channels"
LOC297="Convert"
LOC298="Specify output stream   (required to record internet streams)"
LOC299="Destination"
LOC2910="Bookmark target directory"

#update index
LOC300="Index your Music"
LOC301="My Music is an index (snapshot) of music on your system. It activates Pmusics superfast search-engine"
LOC302="Define where to look for your music."
LOC303="Advanced filters (much slower)"
LOC304="Use Meta-tags when indexing"
LOC306="Don't index directories"
LOC307="Update only news since last index"
LOC308="Start indexing"
LOC309="Index music directory"
LOC310="Pmusic will generate music collections (albums) by meta-tags if selected. In addtition, Pmusic can generate collections based on directory structure."
LOC311="Indexing songs..."
LOC312="Indexing albums..."
LOC313="Indexing directories..."
LOC314="Update index"
LOC315="Statistics"
LOC316="Last indexing" #date
LOC317="Filters"
LOC318="|    Index is missing.\n|    Please go to 'My Music manager'\n|     (File-menu), to index all your music.\n|    You will then find tracks and collections here." #keep \n| for newline
LOC319="Include Youtube tracks"

#tooltips
LOC400="Go BACK in playlist history"
LOC401="Go FORWARD in playlist history"
LOC405="Mute sound"
LOC406="- Free-search: 'nig tnt' finds 'TNT - Desperate night'.
- Add files and URLs to playlist.
- Browse paths."
LOC407="Define which sources to search"
LOC409="Show Music-source window"
LOC411="Fetch playing song"
LOC412="Search the web for lyrics"
LOC413="Play mode: Which track should be next
- Straight: Follow playlist
- Loop: Start over again when last track is played
- Shuffle: Play a random track"
LOC414="Add track:
- after playing track
- as last track"

#presets
LOC440="Left wing"
LOC441="Right wing"

#Bookmarks
LOC460="Path / URL"
LOC461="Name"
LOC462="Move bookmarks by dragging them up/down
Right-click for more options"
LOC465="The 'name' is what shows up when you add music"
LOC466="The 'path / URL' is the acual adress to the bookmarked target"
LOC468="You can include the timestamp of the playing track. This means that clicking on this bookmark later will start the track from current time-position."
LOC469="Keep timestamp"
LOC471="Add item to playlist"
LOC472="Sort bookmark list ascending"
LOC473="Sort bookmark list descending"
LOC474="Clear content of fields"
LOC475="This is a temporary track, and you can't bookmark it"

#radio
LOC490="This is a one-click download and install of the radio-station index.

The index file will be 500Kb+ when installed, and give you access to 5000+ radio stations."
LOC491="The installable index might be to old for you, so is possible to build a new index, based on the very recent info at radiosure.com. - Depending on your system, this will take some time.

The radio-database is static, which means user can't edit manually. To include new URLs, you should add a bookmark or contact www.radiosure.com to include wanted stream-adress. Be aware that Pmusic ONLY uses ffmpeg as its backend. This limits the supported stream-formats to mp3/ogg."
LOC492="Connecting"
LOC493="|    Radio Stations database is not built.\n|    Please go to the radio manager (File-menu),\n|    and activate thousands of radio stations.\n|    Afterwards you will find all stations here." #keep \n| for newline
LOC494="Radio stations"
LOC495="Downloading radio index. Please wait..."

#Podcast
LOC600="Podcast"
LOC601="Name"
LOC602="URL"
LOC603="Keep podcast in X days before destruction"
LOC604="Days"
LOC605="Archive"
LOC606="Check for new podcasts NOW"
LOC607="Schedule Podcast checking"
LOC608="Find a podcast on the web"
LOC609="Add new Podcast to list"
LOC610="Remove selected Podcast from list"
LOC611="Manually edit podcast list in text editor"
LOC612="Downloading"
LOC613="Show textfile with info about removed podcasts"
LOC614="Building schedule template ... Please wait"
LOC615="Delete podcast"
LOC616="Do you want to delete downloaded podcasts in addition to the podcast information?"
LOC617="No podcasts - run manager in File-menu."
LOC618="Define podcast"
LOC619="Add to podcast list"
LOC620="Download podcasts in list"

#WebMusic
LOC630="|WebMusic browsing requires an index.\n|See the WebMusic manager (File-menu)." #keep \n| for newline
LOC631="The WebMusic index is a file containing the information of all music at jamendo.com. Pmusic will play WebMusic tracks without this index file, but it will benefit of it when it comes to browsing and advanced searching.

The index file will be 38Mb+ when installed, and contains info about 257000+ music tracks."
LOC632="The installable index may not hold the latest tracks at jamendo.com. You can build the index file yourself of the very recent info.

Depending on your system this process may take some hours."
LOC633="Date of index"
LOC634="WebMusic Tracks"
LOC635="Reading index. A moment..."
LOC636="|    There is no index file available,\n|    so search will be very limited\n|    - No multitag search\n|    - Max results is 500 pr search.\n|    - See WebMusic manager in the File menu." #keep \n| for newline
LOC637="Build index"


#track info
LOC650="Show alternative track information
based on ARTIST and TITLE"
LOC651="Search for info"
LOC652="Searching more info..."
LOC653="Save and exit"
LOC654="Discography"
LOC655="<b>Webpages</b> - doubleclick to browse"
LOC656="Type" #type of webpage
LOC657="Search for track in indexed collections"
LOC659="Please add (parts of) Artist and/or Title, and Search for info."
LOC660="Alternative tag information"
LOC661="If correct tag-info is not shown in list, it could be that it is not added to the musicbrainz.org database. But most likely the syntax differs from the database. The trick is to cut the Artist/Title info if it contains several words (keep remaining words complete). This will give a wider search, and you can sync the tags with the musicbrainz db."
LOC662="Save new info and close window"
LOC663="Trying to fetch info from internet\nPlease wait..."
LOC664="Reading stream info\nPlease wait..."
LOC665="Searching for lyrics in"
LOC666="_______________
To clear one of the tag fields, you just enter a space (' ') in the field and Save.
_______________
To search internet for alternative tags, you do NOT need to write the whole name of Artist or Title. But, what you write must be complete words.
_______________
If you want to tag several files in one click, check out the global tagging tool in the Playlist/Music-sources menu." #help text
LOC667="Nothing found"
LOC668="Length"
LOC669="Not able to connect to internet."
LOC670="Album art"
LOC671="Stream"

#CD-audio
#preset
LOC700="Rip CD"
LOC701="Copy and convert tracks in list"
LOC702="Copy CD"
LOC703="Burn a new disc"
LOC704="Read CD"
LOC705="Refresh disc info"
#---
LOC708="Probing disc, please wait..."
LOC709="No tracks detected"
#Rip - Export window
LOC720="Name"
LOC721="Define name of new files"
LOC722="Track-number"
LOC723="Add meta-information to new files"
LOC724="Works for" #Works for .mp3 .ogg ... 
LOC725="Build playlist (m3u-file) of tracks"
LOC730="Reading CD"

#Others
LOC503="already exists"
LOC504="Do you want to overwrite existing file?"
LOC505="is not installed"
LOC506="Importing playlist"
LOC507="not found"
LOC508="Jump in song to time"
LOC509="Selection is not a directory"
LOC510="Building a playlist with too many songs could affect your system critically"
LOC511="Should all" #this line is connected with the next line
LOC512="songs be added"
LOC513="Master volum most often is a mono channel, and does not support different level for left and right speaker. You must specify correct channel for your system to get mixer volume to work as a balance controller."
LOC514="Adding random song(s) from shown add-list.

<b>How many songs should be added?</b>"
LOC515="Generating playlist"
LOC516="<b>Add all songs in this directory.</b>

Adding recursively will also include songs in all sub-directories."
LOC517="Add recursively"
LOC519="Source not detected"
LOC521="No valid audio-CD inserted"
LOC522="No disc inserted"
LOC524="You can't jump in a stream."
LOC525='Filename is empty!
Be aware that use of some special chars (like \"|) in filename clears value.'
LOC526="Pmusic is not able to Delete the source file. Do you want to remove the file from the Music Index?"
LOC527="No FAQ available on local system. Downloading from internet...Please wait..."
