#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_which_ati_pkg"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/video_upgrade/which_ati_pkg"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in 1; do shift; done; }

_trap

}
# End new header
#
#101112 fixed path include supported_chips
#110827 ati db entry may have dep |+linux_kernel&eq2.6.32|, so insert 'q'.

DEVICEID="$1"
PET_DB_FILE="$2" #exs: Packages-puppy-wary5-official, Packages-puppy-lucid-official, Packages-puppy-5-official
dPATTERN='|'"$DEVICEID"'$'

. /usr/local/video_upgrade/supported_chips #101112

echo -n "" > /tmp/vuw_ati_pkg

KERNELVER="`uname -r`"
#110827 ati db entry may have dep |+linux_kernel&eq2.6.32|, so insert 'q'...
kPATTERN='[kq]'"`echo -n "$KERNELVER" | sed -e 's%\.%\\\.%g'`"
PETS_ATI="`grep '^ati_fglrx\-' /root/.packages/${PET_DB_FILE} | grep -i "${kPATTERN}" | cut -f 8 -d '|'`"


if [ "`echo "$ATICHIPS_10_10" | grep -i "$dPATTERN"`" != "" ];then
 PET="`echo "$PETS_ATI" | grep '^ati_fglrx\-10\.10\-' | tail -n 1`"
 echo -n "$PET" > /tmp/vuw_ati_pkg
 echo "PET=$PET"
 exit
fi
# Very End of this file 'usr/local/video_upgrade/which_ati_pkg' #
###END###
