#!/bin/bash
# set the PATH variable
#

    # REM: bash builtin PATH:
    #   PATH=/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
    # REM: ash builtin PATH:
    #   PATH=/sbin:/usr/sbin:/bin:/usr/bin

[ "$PATH" ] || PATH=/bin:/sbin:/usr/bin:/usr/sbin

Q=-q
test -f /etc/rc.d/f4puppy5 && . /etc/rc.d/f4puppy5
DEBUG=1
_debug "PATH='$PATH'"

#TR=`which tr`
TR=`type -P tr`
[ -x "$TR" ] || TR=/bin/tr
[ -x "$TR" ] || unset TR

#GREP=`which grep`
GREP=`type -P grep`
[ -x "$GREP" ] || GREP=/bin/grep
[ -x "$GREP" ] || unset GREP

#READLINK=`which readlink`
READLINK=`type -P readlink`
[ -x "$READLINK" ] || READLINK=/bin/readlink
[ -x "$READLINK" ] || unset READLINK

_debug "TR='$TR' GREP='$GREP' READLINK='$READLINK'"
[ "$TR" -a "$GREP" -a "$READLINK" ] || { return 1 2>>$ERR || exit 1 2>>$ERR; }

export PATH=""

for x in {,/usr,/usr/local,/opt}/{,/*}/{bin,sbin} {$HOME/my-applications,/root/my-applications}/{bin,sbin} ; do

    x=`echo "$x" | "$TR" -s '/'`
    [ -d "$x" ] || continue
    echo "$PATH" | "$GREP" $Q -w "$x" && continue
    #[ -L "$x" ] && { RL=`"$READLINK" -f "$x"`;
    #echo "$PATH" | "$GREP" -w "$RL" && continue; }
    [ -L "$x" ] && continue
    [ -L "${x%/*}" ] && continue
    #[ "$PATH" ] && { [ -d $x ] && PATH="$PATH:$x"; } || { [ -d $x ] && PATH="$x"; }
    [ "$PATH" ] && PATH="$PATH:$x" || PATH="$x"

done

if [ "$PATH" ]; then
 :
else
 PATH=/bin:/sbin:/usr/bin:/usr/sbin
 _warn "Could not create PATH variable, using defaults"
fi

export PATH ##+++2012-07-06
_info "PATH set to '$PATH'"
