#!/bin/sh

#perl -V:man.dir
#man1dir='/usr/share/man/man1';
#man3dir='/usr/share/man/man3';

_say_perl_env_vars(){
# from man perlfaq8 :
cat >&1 <<EoI
   How do I add a directory to my include path (@INC) at runtime?
       Here are the suggested ways of modifying your include path, including
       environment variables, run-time switches, and in-code statements:

       the PERLLIB environment variable
                   $ export PERLLIB=/path/to/my/dir
                   $ perl program.pl

       the PERL5LIB environment variable
                   $ export PERL5LIB=/path/to/my/dir
                   $ perl program.pl

       the perl -Idir command line flag
                   $ perl -I/path/to/my/dir program.pl

       the use lib pragma:
                   use lib "$ENV{HOME}/myown_perllib";

       The last is particularly useful because it knows about machine
       dependent architectures.  The lib.pm pragmatic module was first
       included with the 5.002 release of Perl.
EoI
}

#bash-3.00# html2ps
#Can't locate loadable object for module Image::Magick in @INC (@INC contains: #/usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld
#/usr/lib/perl5/5.10.1
#/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld
#/usr/lib/perl5/site_perl/5.10.1
#/usr/lib/perl5/site_perl/5.8.8
#/usr/lib/perl5/site_perl
#.) at /usr/bin/html2ps line 482
#Compilation failed in require at /usr/bin/html2ps line 482.
#&Image::Magick::constant not defined. The required ImageMagick libraries are not installed or not installed properly.
#END failed--call queue aborted at /usr/bin/html2ps line 482.

export PERLLIB='/usr/lib/perl5'
export PERL5LIB='/usr/lib/perl5'

#bash-3.00# export PERL5LIB='/usr/lib/perl5'
#bash-3.00# html2ps
#Can't load '/usr/lib/perl5/auto/Image/Magick/Magick.so' for module Image::Magick:
#libperl.so.5.10: cannot open shared object file: No such file or directory at
# /usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld/DynaLoader.pm line 200.
# at /usr/bin/html2ps line 482
#Compilation failed in require at /usr/bin/html2ps line 482.
#&Image::Magick::constant not defined. The required ImageMagick libraries are not installed or not installed properly.
#END failed--call queue aborted at /usr/bin/html2ps line 482.

#find /usr -name "libperl*.so*"
#/usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld/CORE/libperl.so

# man perlfaq2
#perl -le 'print for @INC'
#/usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld
#/usr/lib/perl5/5.10.1
#/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld
#/usr/lib/perl5/site_perl/5.10.1
#/usr/lib/perl5/site_perl/5.8.8
#/usr/lib/perl5/site_perl

#bash-3.00# perl -V
#Summary of my perl5 (revision 5 version 10 subversion 1) configuration:
#
#  Platform:
#    osname=linux, osvers=2.6.30.9-i586-dpup005-celeron2g, archname=i686-linux-thread-multi-ld
#    uname='linux puppypc 2.6.30.9-i586-dpup005-celeron2g #6 smp sat jan 15 13:35:51 gmt-8 2011 i686 gnulinux '
#    config_args=''
#    hint=recommended, useposix=true, d_sigaction=define
#    useithreads=define, usemultiplicity=define
#    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
#    use64bitint=undef, use64bitall=undef, uselongdouble=define
#    usemymalloc=n, bincompat5005=undef
#  Compiler:
#    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
# -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
#    optimize='-O2',
#    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
#    ccversion='', gccversion='4.2.2', gccosandvers=''
#    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
#    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
#    ivtype='long', ivsize=4, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
#    alignbytes=4, prototype=define
#  Linker and Libraries:
#    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
#    libpth=/usr/local/lib /lib /usr/lib
#    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
#    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
#    libc=/lib/libc-2.6.1.so, so=so, useshrplib=true, libperl=libperl.so
#    gnulibc_version='2.6.1'
#  Dynamic Linking:
#    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E
# -Wl,-rpath,/usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld/CORE'
#   cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector'
#
#
#Characteristics of this binary (from libperl):
#  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
#                        PERL_IMPLICIT_CONTEXT PERL_MAD PERL_MALLOC_WRAP
#                        USE_ITHREADS USE_LARGE_FILES USE_LONG_DOUBLE
#                        USE_PERLIO USE_REENTRANT_API
#  Built under linux
#  Compiled at May  1 2012 22:41:37
#  @INC:
#    /usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld
#    /usr/lib/perl5/5.10.1
#    /usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld
#    /usr/lib/perl5/site_perl/5.10.1
#    /usr/lib/perl5/site_perl/5.8.8
#    /usr/lib/perl5/site_perl

#bash-3.00# export PERL5LIB=/usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld:/usr/lib/perl5/5.10.1:/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld:/usr/lib/perl5/site_perl/5.10.1:/usr/lib/perl5/site_perl:/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld/Image/Magick:/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld/Image/Magick/Magick:/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld/auto/Image/Magick
#bash-3.00# html2ps
#Can't load '/usr/lib/perl5/site_perl/5.10.1/i686-linux-thread-multi-ld/Image/Magick/Magick.so'
# for module Image::Magick: libgomp.so.1: shared object cannot be dlopen()ed at /usr/lib/perl5/5.10.1/i686-linux-thread-multi-ld/DynaLoader.pm line 200.
# at /usr/bin/html2ps line 482
#Compilation failed in require at /usr/bin/html2ps line 482.
#&Image::Magick::constant not defined. The required ImageMagick libraries are not installed or not installed properly.
#END failed--call queue aborted at /usr/bin/html2ps line 482.
#bash-3.00# perl --version
#This is perl, v5.10.1 (*) built for i686-linux-thread-multi-ld
