#!/bin/bash
# set the PKG_CONFIG_PATH variable
#

__old_func__(){
export PKG_CONFIG_PATH=""
for x in {/usr,/opt}{,/*}/{share,lib?*,lib}/pkgconfig $HOME/lib{?*,}/pkgconfig ; do
    [ -d $x ] && PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$x"
done
}

PKG_CONFIG_PATH='';

#DIRS=`find /usr -maxdepth 5 -type d -name "pkgconfig"`

for n in `seq 1 1 4` ;
do
DIRS=`find /usr -mindepth $n -maxdepth $n -type d -name pkgconfig | sort -d`
for dir in $DIRS; do PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$dir" ; done
done

PKG_CONFIG_PATH="${PKG_CONFIG_PATH/#:/}"
export PKG_CONFIG_PATH
