#!/bin/bash

export PYTHON="/usr/bin/python"

PYTHONPATH='';

#DIRS=`find /usr -maxdepth 5 -type d -name python*`

for n in `seq 1 1 4` ;
do
DIRS=`find /usr -mindepth $n -maxdepth $n -type d \( -wholename "*/bin/*python*" -o -wholename "*python*/bin" \) | sort -d`
for dir in $DIRS ; do PYTHONPATH="${PYTHONPATH}:$dir" ; done
done

PYTHONPATH="${PYTHONPATH/#:/}"
export PYTHONPATH

#PYTHONSTARTUP: file executed on interactive startup (no default)
#
#PYTHONPATH   : ':'-separated list of directories prefixed to the
#               default module search path.  The result is sys.path.
#PYTHONHOME   : alternate <prefix> directory (or <prefix>:<exec_prefix>).
#               The default module search path uses <prefix>/pythonX.X.
#PYTHONCASEOK : ignore case in 'import' statements (Windows).
#
#PYTHONIOENCODING: Encoding[:errors] used for stdin/stdout/stderr.
#
#PYTHONHASHSEED: if this variable is set to 'random', the effect is the same
#   as specifying the -R option: a random value is used to seed the hashes of
#   str, bytes and datetime objects.  It can also be set to an integer
#   in the range [0,4294967295] to get hash values with a predictable seed.














