#!/bin/ash

#/dev/vc/8 ls -l = /dev/tty8

#File="/tmp/Xerrs.`uname -r`.`date +%d%b%Y`.Xorg.log"
#File="`grep -m1 -w 'ErrLog=' /usr/bin/xwin`"

File="`/bin/find /tmp/xwin/[Xx]errs* -cmin +1 -cmin -4`"
while [ -z "$File" ]; do
sleep 2
File="`/bin/find /tmp/xwin/[Xx]errs* -cmin +1 -cmin -4`"
#sleep 2
done

#if test -f "$File.*" ; then
#/bin/cat "$File" | /bin/tail -n 20
 /bin/tail -n 20 "$File"
#fi

sleep 60



