#!/bin/ash

#/dev/vc/8 ls -l = /dev/tty8

#File="/tmp/Xerrs.`uname -r`.`date +%d%b%Y`.Xorg.log"
#File="`grep -m1 -w 'ErrLog=' /usr/bin/xwin`"

File="`find /tmp/xwin/[Xx]errs* -cmin -4`"
while [ -z "$File" ]; do
File="`find /tmp/xwin/[Xx]errs* -cmin -4`"
sleep 2
done

while [ running ];
do
[ "`pidof poweroff reboot`" ] && exit
#if test -f "$File.*" ; then
/bin/cat "$File" | /bin/tail -n 20
#fi

sleep 60
echo "
"

done


