#!/bin/sh

VERSION="0.6.1-1.sp"
# Determine the path to this application.
CURDIR="`pwd`"
APPDIR=`dirname "$0"`
cd "${APPDIR}"
APPDIR="`pwd`"
APPDIR_ESC=$(echo "$APPDIR" | sed 's/ /\\ /g') #escaping spaces for gtkdialog
export APPDIR
cd "${CURDIR}"
LOG=/tmp/backg.log
echo "$0:$*" >>"$LOG"

[[ "$*" ]] && { [ -f "${APPDIR}"/AppRun.exe ] && exec "${APPDIR}"/AppRun.exe "$*"; }

gui_part_func(){
# Radio buttons
CENTREBUTTON="<radiobutton>
<label>\"$LOC_CENTRE\"</label>
<action>echo Centre > \"\$HOME\"/.config/wallpaper/backgroundmode</action>
<action>$APPDIR_ESC/slideshow -stop</action>
<action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
<action>echo \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
<action type=\"refresh\">TEXT</action>
</radiobutton>"
TILEBUTTON="<radiobutton>
<label>\"$LOC_TILE\"</label>
<action>echo Tile > \"\$HOME\"/.config/wallpaper/backgroundmode</action>
<action>$APPDIR_ESC/slideshow -stop</action>
<action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
<action>echo \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
<action type=\"refresh\">TEXT</action>
</radiobutton>"
SCALEBUTTON="<radiobutton>
<label>\"$LOC_SCALE\"</label>
<action>echo Scale > \"\$HOME\"/.config/wallpaper/backgroundmode</action>
<action>$APPDIR_ESC/slideshow -stop</action>
<action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
<action>echo \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
<action type=\"refresh\">TEXT</action>
</radiobutton>"
STRETCHBUTTON="<radiobutton>
<label>\"$LOC_STRETCH\"</label>
<action>echo Stretch > \"\$HOME\"/.config/wallpaper/backgroundmode</action>
<action>$APPDIR_ESC/slideshow -stop</action>
<action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
<action>echo \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
<action type=\"refresh\">TEXT</action>
</radiobutton>"


case $OLDMODE in
 Centre)
 RADIOBUTTONS="$CENTREBUTTON
 $TILEBUTTON
 $SCALEBUTTON
 $STRETCHBUTTON"
 ;;
 Tile)
 RADIOBUTTONS="$TILEBUTTON
 $CENTREBUTTON
 $SCALEBUTTON
 $STRETCHBUTTON"
 ;;
 Scale)
 RADIOBUTTONS="$SCALEBUTTON
 $CENTREBUTTON
 $TILEBUTTON
 $STRETCHBUTTON"
 ;;
 Stretch)
 RADIOBUTTONS="$STRETCHBUTTON
 $CENTREBUTTON
 $TILEBUTTON
 $SCALEBUTTON"
 ;;
esac
}
. "$APPDIR"/common.sau
gui_part_func


am_i_image(){
if [ "$OLDIMAGE" = "" ]; then
	OLDIMAGE="[none]"
	DIR="/usr/share/backgrounds"
else
	DIR=`dirname "$OLDIMAGE"`
	[ "$DIR" = "$HOME/.pwidgets" ] && DIR="/usr/share/backgrounds"
fi

echo "$OLDIMAGE" > "$HOME"/.config/wallpaper/bg_img
# Reset mode
echo $OLDMODE > "$HOME"/.config/wallpaper/backgroundmode

#add button for sidebar if installed
if [ -f "$HOME"/.pwidgets/pwidgetsrc ];then #icon fix 20110624, also in the main xml code for "edit" and "view"
 SIDEBAR='<button><label>Sidebar</label><input file stock="gtk-media-pause"></input><action>/usr/local/pwidgets/widgets/plugins/sidebar/sidebar &</action></button>'
fi

#show image #20110624 01micko, requires new gtkdialog
CURRENTIMG=`cat "$HOME"/.config/wallpaper/bg_img`
ln -sf "$CURRENTIMG" /tmp/current_wallpaper_selection.jpg


swapimagefunc()
{
	rm -f /tmp/current_wallpaper_selection.jpg
	ISIMAGE="`echo $IMAGE|grep -iE 'jpg$|png$|jpeg$|gif|JPEG$|JPG$|tiff$|background$'`"
	if [ "$ISIMAGE" = "" ];then IMAGE="/usr/share/doc/puppylogo96.png" #if file is not an image
	fi
	ln -sf "$IMAGE" /tmp/current_wallpaper_selection.jpg
}
export -f swapimagefunc

PREVDIR=`pwd`
cd "$DIR"
}
am_i_image

export BG_DLG="
<window title=\"$LOC_MAIN\" icon_name=\"preferences-desktop-wallpaper\">
 <vbox>
  <menubar>
   <menu>
    <menuitem icon=\"multimedia-player\">
     <label>\"$LOC_SLIDESHOW\"</label>
     <action>$APPDIR_ESC/slideshow -start \$IMAGE &</action>
    </menuitem>
    <menuitem icon=\"gtk-preferences\">
     <label>$LOC_OPTIONS</label>
     <action>$APPDIR_ESC/functions -preferences &</action>
    </menuitem>
    <separator></separator>
    <menuitem icon=\"gtk-quit\">
     <label>\"$LOC_QUIT\"</label>
     <action>EXIT:abort</action>
    </menuitem>
    <label>\"$LOC_FILE\"</label>
   </menu>
   <menu>
    <menuitem stock=\"gtk-about\">
     <action>$APPDIR_ESC/functions -about</action>
    </menuitem>
    <label>\"$LOC_HELP\"</label>
   </menu>
  </menubar>
  <hbox>
   <vbox>
    <frame $LOC_FILE_FRAME>
     <chooser>
      <height>180</height><width>500</width>
      <variable>IMAGE</variable>
      <action>$APPDIR_ESC/slideshow -stop</action>
      <action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
      <action>echo \"$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
      <action signal=\"button-release-event\">swapimagefunc</action>
      <action signal=\"button-release-event\" type=\"refresh\">PIXMAP</action>
     </chooser>
     <frame $LOC_CURRENT_IMAGE>
      <hbox height-request=\"190\" homogeneous=\"true\">
       <pixmap>
        <height>180</height><width>270</width>
        <variable>PIXMAP</variable>
        <input file>/tmp/current_wallpaper_selection.jpg</input>
       </pixmap>
      </hbox>
     </frame>
    </frame>
   </vbox>
   <vbox>
    <frame $LOC_MODE>
     $RADIOBUTTONS
    </frame>
    <frame $LOC_ACTIONS>
     <button>
      <label>\"$LOC_APPLY\"</label>
      <input file stock=\"gtk-apply\"></input>
      <action>$APPDIR_ESC/slideshow -stop</action>
      <action>$APPDIR_ESC/set_bg \"\$IMAGE\"</action>
      <action>echo \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bg_img</action>
      <action>[ \"$(which fixwidgets)\" ] && fixwidgets -wallpaper_setter &</action>
      <action type=\"refresh\">TEXT</action>
     </button>
     <button>
      <label>\"$LOC_CLEAR\"</label>
      <input file stock=\"gtk-clear\"></input>
      <action>$APPDIR_ESC/slideshow -stop</action>
      <action>$APPDIR_ESC/set_bg -clear</action>
      <action type=\"refresh\">TEXT</action>
     </button>
     $SIDEBAR
     <button>
     <label>\"$LOC_EDIT\"</label>
      <input file stock=\"gtk-edit\"></input>
      <action>$IMGEDITOR \"\$IMAGE\" &</action>
     </button>
     <button height-request=\"30\">
      <label>\"$LOC_VIEW\"</label>
      <input file>\"/usr/local/lib/X11/mini-icons/mini-eye.xpm\"</input>
      <action>$VIEWER \"\$IMAGE\" &</action>
     </button>
     <button>
      <label>\"$LOC_FILER\"</label>
      <input file stock=\"gtk-directory\"></input>
      <action>dirname \"\$IMAGE\" > \"\$HOME\"/.config/wallpaper/bgdir</action>
      <action>$APPDIR_ESC/functions -filer &</action>
     </button>
     <button>
      <input file stock=\"gtk-close\"></input>
      <label>\"$LOC_CLOSE\"</label>
     </button>
    </frame>
   </vbox>
  </hbox>
 </vbox>
 <action signal=\"hide\">exit:Exit</action>
</window>
"
#GTKDEBUG=-d
gtkdialog4 $GTKDEBUG --program BG_DLG

cd "$PREVDIR"
