#!/bin/sh
VERSION="0.6.1-1.sp"
#IMGPATH="`dirname $1`"
#IMG="`basename $1`"
IMGPATH=`dirname "$*"`
IMG=`basename "$*"`
LOG=/tmp/backg.log
echo "$0:$*" >>"$LOG"
# check filetype
#FTYPE=`echo "$IMG" | rev | cut -f 1 -d '.' | rev`
FTYPE="${IMG##*\.}"
case $FTYPE in
 svg)
 #cp -f "${IMGPATH}${IMG}" "$HOME"/.config/wallpaper/thumb.png
 cp -f "$*" "$HOME"/.config/wallpaper/thumb.png
 ;;
 png|gif|jpg|jpeg)
 resamplefixedheight "$*" "$HOME"/.config/wallpaper/thumb.png 32
 ;;
 *)
 #cp -f /usr/share/icons/Tango/scalable/mimetypes/image-x-generic.svg "$HOME"/.config/wallpaper/thumb.png
 cp -f /usr/share/icons/Tango/scalable/mimetypes/image-x-generic.svg "$HOME"/.config/wallpaper/thumb.png
 ;;
esac
 
