#!/bin/ash

PROG='/etc/profile'

. /etc/rc.d/f4puppy5

[ -f /etc/.bashrc ] && . /etc/.bashrc

####profile.d
#v2.16 this need arose when considering SFS files that may require special env. variables.
#this code is lifted straight from Vector...
# Append any additional sh scripts found in /etc/profile.d/:
#for profile_script in /etc/profile.d/*.sh ; do
#if [ ! -f /etc/profile.d/firstun ] ; then #krg

for profile_script in /etc/profile.d/* ; do #w482 any files.
case $profile_script in *.txt) continue;; esac

 echo " starting sourcing $profile_script .. "
. $profile_script

done
unset profile_script

#personal customisation file...
#[ -r /etc/profile.local ] && . /etc/profile.local
if [ -r /etc/profile.local ] ; then
 echo " sourcing /etc/profile.local ... "
 . /etc/profile.local
fi

#v2.12
# init and rc.sysinit create this nox marker file, run once only at login ...
if [ -f /tmp/bootcnt.touch ];then
 # xorgwizard creates this file :
 #[ -f /etc/resolutionfix ] && eval `cat /etc/resolutionfix`
 [ -f /etc/resolutionfix ]
 case $? in 0) . /etc/resolutionfix;; 1) true;;esac
fi

echo '1 : '"`date +%M:%S:%N`"

if [ ! -f /usr/bin/X ];then
echo '100 : '"`date +%M:%S:%N`"
 #v2.00r1 now support a text-mode-only puppy...
 if [ -f /usr/local/bin/elinks ];then
 echo '110 : '"`date +%M:%S:%N`"
  if [ -f /tmp/bootcnt.touch ];then
   echo '120 : '"`date +%M:%S:%N`"
   rm -f /tmp/bootcnt.touch
   exec /usr/local/bin/elinks file:///usr/share/doc/index.html
  fi
 else
  echo
  echo "\\033[1;31mSorry, cannot start X. Link /usr/bin/X missing."
  echo -n "(suggestion: type 'xorgwizard' to run the Xorg Video Wizard)"
  echo -e "\\033[0;39m"
 fi

else

 if [ "`basename $(tty)`" = "tty1" ] ; then

 if [ -f /tmp/bootcnt.touch ];then
  rm -f /tmp/bootcnt.touch

   _DATE_=`date +%F`
   dmesg > /tmp/bootkernel.log.profile.$_DATE_
   echo >> /tmp/bootkernel.log.profile.$_DATE_
   date >> /tmp/bootkernel.log.profile.$_DATE_
   if [ -z "`cat /proc/cmdline | grep -i 'nox'`" ] ; then
    echo -e "\\033[1;34m""Starting now xwin from '$PROG' '$0'""\\033[0;39m"
    echo '300 : '"`date +%M:%S:%N`"
    [ "$DEBUG" ] && sleep 5s
    exec xwin
   else
    echo -e "\\033[1;34m""Booted with nox parameter . Staying in console mode""\\033[0;39m"
   fi

 fi

 fi

fi

echo "finished running '$PROG' '$0' :"
echo "`date`"
echo '1 : '"`date +%M:%S:%N`"
echo
###END###
