#!/bin/sh
#
# New header by Karl Reimer Godt, September 2014
  _TITLE_="Puppy_box_ok"
_VERSION_=1.0omega
_COMMENT_="$_TITLE_:Puppy Linux shell script [to TODO here]"

MY_SELF="/usr/local/pschedule/box_ok"
MY_PID=$$

test -f /etc/rc.d/f4puppy5 && {
[ "$HAVE_F4PUPPY5" ] || source /etc/rc.d/f4puppy5

ADD_PARAMETER_LIST=""
ADD_PARAMETERS=""
_provide_basic_parameters

TWO_HELP=''; TWO_VERSION=''; TWO_VERBOSE=''; TWO_DEBUG=''; ## Set to anything if code requires further down (ie. custom usage or version message)
ADD_HELP_MSG="$_COMMENT_"
_parse_basic_parameters "$@"
[ "$DO_SHIFT" ] && [ ! "${DO_SHIFT//[[:digit:]]/}" ] && {
  for oneSHIFT in `seq 1 1 $DO_SHIFT`; do shift; done; }

_trap

}
# End new header
#

if [ -z "$FRAME" ]; then FRAME="Info"; fi
export ok_box="
<window title=\"Pbackup\" icon-name=\"gtk-refresh\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT2\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT3\"</label></text>
  </frame>
  <hbox>
   <button>
    <input file icon=\"gtk-apply\"></input>
    <label>Ok</label>
   </button>
  </hbox>
 </vbox>
</window>"
gtkdialog3 --program=ok_box --center
TXT1=""; TXT2=""; TXT3=""; IMG=""; FRAME="" #reset to avoid alien text in next box
# Very End of this file 'usr/local/pschedule/box_ok' #
###END###
