#! /bin/bash

#MINUTE=`cat /tmp/pschedule-cronminute`
#HOUR=`cat /tmp/pschedule-cronhour`
#DAY=`cat /tmp/pschedule-cronday`
#MONTH=`cat /tmp/pschedule-cronmonth`
#WEEKDAY=`cat /tmp/pschedule-cronweekday`

if [ "$MINUTE" = "any" ]; then MINUTE="*"; fi
if [ "$HOUR" = "any" ]; then HOUR="*"; fi
if [ "$DAY" = "any" ]; then DAY="*"; fi

case "$MONTH" in
	"January")		MONTH="1";;
	"February")		MONTH="2";;
	"March")		MONTH="3";;
	"April")		MONTH="4";;
	"May" )			MONTH="5";;
	"June")			MONTH="6";;
	"July")			MONTH="7";;
	"August")		MONTH="8";;
	"September")	MONTH="9";;
	"October")		MONTH="10";;
	"November")		MONTH="11";;
	"December")		MONTH="12";;
	*)				MONTH="*";;
esac
case "$WEEKDAY" in
	"Monday")		WEEKDAY="1";;
	"Tuesday")		WEEKDAY="2";;
	"Wedensday")	WEEKDAY="3";;
	"Thursday")		WEEKDAY="4";;
	"Friday")		WEEKDAY="5";;
	"Saturday")		WEEKDAY="6";;
	"Sunday")		WEEKDAY="0";;
	*)				WEEKDAY="*";;
esac

if [ "$MINUTE" = "00" ]; then MINUTE="0"; fi
if [ "$MINUTE" != "0" ] && [ "$MINUTE" -lt "10" ]; then MINUTE=`echo "$MINUTE" | tr -d 0`; fi
if [ "$HOUR" = "00" ]; then HOUR="0"; fi
if [ "$HOUR" != "0" ] && [ "$HOUR" -lt "10" ]; then HOUR=`echo "$HOUR" | tr -d 0`; fi
DAY=`echo "$DAY" | tr -d .`

echo "$MINUTE"		> /tmp/pschedule-cronminute
echo "$HOUR"		> /tmp/pschedule-cronhour
echo "$DAY"			> /tmp/pschedule-cronday
echo "$MONTH"		> /tmp/pschedule-cronmonth
echo "$WEEKDAY"		> /tmp/pschedule-cronweekday
echo "$MINUTE $HOUR $DAY $MONTH $WEEKDAY" > /tmp/pschedule-cron
