#!/bin/ash
#the way this file is written, it is best to start Icewm with just "icewm"

. /etc/rc.d/f4puppy5

#DIR=$HOME/icewm
DIR=/usr/share/icewm

DISP=${DISPLAY%.*}
DISP=${DISP:-':0'}

CURWM=`head -c5 /etc/windowmanager` #this is a workaround if icewm was started with "icewm-session"
test -s /etc/windowmanager.$DISP && CURWM=`head -c5 /etc/windowmanager.$DISP`
[ "$CURWM" = "icewm" ] || exit 0

test -f $HOME/.icewm/theme && . $HOME/.icewm/theme
THEMEDIR="/usr/share/icewm/themes"
test -f ${THEMEDIR}/${Theme} && . ${THEMEDIR}/${Theme}
NUMCOLOR=`echo $ColorNormalTaskBarApp|grep "rgb:"`
if [ "$NUMCOLOR" = "" ];then BG=""
    else PRE_BG=`echo $ColorNormalTaskBarApp|cut -d ':' -f2|sed 's%/%%g'`
         BG="#${PRE_BG}"
fi
if [ "$Theme" = "GoldenSand/default.theme" ];then BG="#C6AD73"
fi

if [ "$BG" = "" ];then OPTARG=""
    else OPTARG="-bg ${BG}"
fi
echo "$0:OPTARG=$OPTARG"

#let's get started #battery and numlockx usually start ok, so they are omitted
#killall icewmtray
pidof icewmtray >>$OUT || exec icewmtray &
pidof powerapplet_tray >>$OUT || exec /root/Startup/powerapplet_tray &
sleep 1
FWALL=`ls /root/Startup|grep firewall`
for fw in $FWALL; do
if [ -x "/root/Startup/${FWALL}" ];then exec $FWALL &
    sleep 3
fi
done
#killall retrovol
if pidof retrovol >>$OUT; then :; else
if [ "$OPTARG" = "" ];then
     retrovol -hide &
else retrovol $OPTARG -hide &
fi
sleep 2
fi

pidof blinky >>$OUT && killall blinky
test -x $DIR/blinky && exec $DIR/blinky $OPTARG &
sleep 2
if test -x $DIR/freememapplet_tray; then
pidof freememapplet_tray >>$OUT || exec $DIR/freememapplet_tray &
fi

exit 0
###END###
