#!/bin/sh
#restore /usr/bin/restartwm #see /usr/sbin/wmswitcher #not urgent so we give it "z" prefix, more of a precaution
#cp -f /usr/bin/.restartwm.bak /usr/bin/restartwm
exit 0
FUTUREWM=`grep -we '^NEXTWM=' /usr/bin/restartwm`
[ "$FUTUREWM" ] || exit 1
echo "rpl -v '$FUTUREWM' 'NEXTWM=\"\$1\"' /usr/bin/restartwm" >/tmp/wmrestore
        . /tmp/wmrestore
        #rm -f /tmp/wmrestore
